// packages/react/src/components/Toolbar/Toolbar.tsx
import React from 'react';
import { Box } from '../Layout/Box.js';
import { HStack } from '../Layout/Stack.js';
import { Text } from '../Typography/Text.js';
import { Button } from '../Button/Button.js';
import './Toolbar.css';

export interface ToolbarProps extends React.HTMLAttributes<HTMLElement> {
  search?: React.ReactNode;
  filters?: React.ReactNode;
  actions?: React.ReactNode;
  selectedCount?: number;
  bulkActions?: React.ReactNode;
  onClearSelection?: () => void;
  className?: string;
  'aria-label'?: string;
}

export const Toolbar: React.FC<ToolbarProps> = ({
  search,
  filters,
  actions,
  selectedCount = 0,
  bulkActions,
  onClearSelection,
  className = '',
  'aria-label': ariaLabel = 'Toolbar',
  ...props
}) => {
  const isBulkActive = selectedCount > 0;

  return (
    <Box
      role="toolbar"
      aria-label={ariaLabel}
      p={3}
      isCard
      className={`ds-toolbar ${isBulkActive ? 'ds-toolbar--bulk-active' : ''} ${className}`}
      {...props}
    >
      {isBulkActive ? (
        <HStack
          justify="between"
          align="center"
          wrap
          gap={3}
          className="ds-toolbar__bulk-row"
          style={{ width: '100%' }}
        >
          <HStack align="center" gap={3} className="ds-toolbar__bulk-info">
            <span className="ds-toolbar-selection-pill ds-toolbar__selection-pill">
              <Text as="span" size="sm" weight="semibold">
                {selectedCount} selected
              </Text>
            </span>
            {onClearSelection && (
              <Button
                variant="ghost"
                size="sm"
                className="ds-toolbar__deselect-btn"
                onClick={onClearSelection}
              >
                Deselect all
              </Button>
            )}
          </HStack>
          <HStack align="center" gap={2} wrap className="ds-toolbar__bulk-actions">
            {bulkActions}
          </HStack>
        </HStack>
      ) : (
        <HStack
          justify="between"
          align="center"
          wrap
          gap={4}
          className="ds-toolbar__standard-row"
          style={{ width: '100%' }}
        >
          <HStack
            align="center"
            gap={3}
            wrap
            className="ds-toolbar__leading"
            style={{ flex: '1 1 auto', minWidth: 'var(--layout-toolbar-leading-min-w)' }}
          >
            {search && (
              <div className="ds-toolbar-search-slot ds-toolbar__search-slot">{search}</div>
            )}
            {filters && (
              <div className="ds-toolbar-filters-slot ds-toolbar__filters-slot">{filters}</div>
            )}
          </HStack>
          {actions && (
            <div className="ds-toolbar-actions-slot ds-toolbar__trailing">{actions}</div>
          )}
        </HStack>
      )}
    </Box>
  );
};

// packages/angular/src/components/toolbar/toolbar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ds-toolbar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      role="toolbar"
      [attr.aria-label]="ariaLabel || 'Toolbar'"
      class="ds-toolbar"
      [class.ds-toolbar--bulk-active]="selectedCount > 0"
      [class]="customClass"
      (keydown)="onToolbarKeyDown($event)"
    >
      <!-- Bulk Selection Mode -->
      <div *ngIf="selectedCount > 0" class="ds-toolbar__bulk-row">
        <div class="ds-toolbar__bulk-info">
          <span class="ds-toolbar__selection-pill">
            {{ selectedCount }} selected
          </span>
          <button
            type="button"
            class="ds-toolbar__deselect-btn"
            (click)="onClearSelection.emit()"
          >
            Deselect all
          </button>
        </div>
        <div class="ds-toolbar__bulk-actions">
          <ng-content select="[slot=bulk-actions]"></ng-content>
        </div>
      </div>

      <!-- Standard Controls Mode -->
      <div *ngIf="selectedCount === 0" class="ds-toolbar__standard-row">
        <div class="ds-toolbar__leading">
          <div class="ds-toolbar__search-slot">
            <ng-content select="[slot=search]"></ng-content>
          </div>
          <div class="ds-toolbar__filters-slot">
            <ng-content select="[slot=filters]"></ng-content>
          </div>
        </div>
        <div class="ds-toolbar__trailing">
          <ng-content select="[slot=actions]"></ng-content>
          <ng-content></ng-content>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./toolbar.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsToolbarComponent {
  @Input() selectedCount = 0;
  @Input() ariaLabel = 'Actions toolbar';
  @Input() customClass = '';

  @Output() onClearSelection = new EventEmitter<void>();

  constructor(private elementRef: ElementRef<HTMLElement>) {}

  /**
   * Implements roving tabIndex / arrow key navigation across child buttons, inputs, and controls.
   */
  onToolbarKeyDown(event: KeyboardEvent): void {
    if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) {
      return;
    }

    const host = this.elementRef.nativeElement;
    const focusableSelector =
      'button:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex="0"]';
    const focusableElements = Array.from(
      host.querySelectorAll<HTMLElement>(focusableSelector)
    );

    if (focusableElements.length === 0) return;

    const currentIndex = focusableElements.indexOf(document.activeElement as HTMLElement);
    if (currentIndex === -1) return;

    let nextIndex = currentIndex;
    if (event.key === 'ArrowRight') {
      nextIndex = (currentIndex + 1) % focusableElements.length;
    } else if (event.key === 'ArrowLeft') {
      nextIndex = (currentIndex - 1 + focusableElements.length) % focusableElements.length;
    } else if (event.key === 'Home') {
      nextIndex = 0;
    } else if (event.key === 'End') {
      nextIndex = focusableElements.length - 1;
    }

    event.preventDefault();
    focusableElements[nextIndex]?.focus();
  }
}
