// packages/angular/src/components/select/select.component.ts
import { Component, Input, Output, EventEmitter, forwardRef, ChangeDetectionStrategy, HostListener, ElementRef, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

export interface DsSelectItem {
  label: string;
  value: string;
  disabled?: boolean;
}

export type SelectSize = 'sm' | 'md' | 'lg';

let nextSelectId = 0;

@Component({
  selector: 'ds-select',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="ds-select-root">
      <label *ngIf="label" [id]="labelId" [attr.for]="triggerId" class="ds-select-label">{{ label }}</label>

      <button
        type="button"
        [id]="triggerId"
        [disabled]="disabled"
        [ngClass]="[
          'ds-select-trigger',
          'ds-select-trigger--' + size,
          isOpen ? 'ds-select-trigger--open' : '',
          isInvalid || errorMessage ? 'ds-select-trigger--invalid' : ''
        ]"
        (click)="toggleOpen()"
        aria-haspopup="listbox"
        [attr.aria-expanded]="isOpen"
        [attr.aria-invalid]="isInvalid || errorMessage ? 'true' : null"
        [attr.aria-describedby]="describedByIds"
        [attr.aria-labelledby]="label ? labelId : ariaLabelledBy || null"
        [attr.aria-label]="label ? null : ariaLabel || null"
      >
        <span class="ds-select-value">{{ selectedLabel || placeholder }}</span>
        <span class="ds-select-indicator" aria-hidden="true">▼</span>
      </button>

      <p *ngIf="helperText" [id]="helperId" class="ds-select-helper-text">{{ helperText }}</p>
      <p *ngIf="errorMessage" [id]="errorId" role="alert" class="ds-select-error-message">{{ errorMessage }}</p>

      <ul *ngIf="isOpen" class="ds-select-content" role="listbox">
        <li
          *ngFor="let item of items"
          role="option"
          [attr.aria-selected]="item.value === value"
          [attr.aria-disabled]="item.disabled"
          [ngClass]="[
            'ds-select-item',
            item.value === value ? 'ds-select-item--selected' : '',
            item.disabled ? 'ds-select-item--disabled' : ''
          ]"
          (click)="selectItem(item)"
        >
          <span>{{ item.label }}</span>
          <span *ngIf="item.value === value" class="ds-select-item-indicator">✓</span>
        </li>
      </ul>
    </div>
  `,
  styleUrls: ['./select.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => DsSelectComponent),
      multi: true,
    },
  ],
})
export class DsSelectComponent implements ControlValueAccessor, OnInit {
  @Input() id?: string;
  @Input() items: DsSelectItem[] = [];
  @Input() label?: string;
  @Input() ariaLabel?: string;
  @Input() ariaLabelledBy?: string;
  @Input() ariaDescribedBy?: string;
  @Input() placeholder: string = 'Select an option...';
  @Input() size: SelectSize = 'md';
  @Input() disabled: boolean = false;
  @Input() isInvalid: boolean = false;
  @Input() errorMessage?: string;
  @Input() helperText?: string;

  @Output() valueChange = new EventEmitter<string>();

  value: string = '';
  isOpen: boolean = false;
  private autoId = `ds-select-${++nextSelectId}`;

  get triggerId(): string {
    return this.id || this.autoId;
  }

  get labelId(): string {
    return `${this.triggerId}-label`;
  }

  get helperId(): string {
    return `${this.triggerId}-helper`;
  }

  get errorId(): string {
    return `${this.triggerId}-error`;
  }

  get describedByIds(): string | null {
    const ids: string[] = [];
    if (this.errorMessage) ids.push(this.errorId);
    if (this.helperText) ids.push(this.helperId);
    if (this.ariaDescribedBy) ids.push(this.ariaDescribedBy);
    return ids.length > 0 ? ids.join(' ') : null;
  }

  constructor(private elementRef: ElementRef) {}

  ngOnInit(): void {
    if (!this.label?.trim() && !this.ariaLabel?.trim() && !this.ariaLabelledBy?.trim()) {
      throw new Error('ds-select requires label, ariaLabel, or ariaLabelledBy.');
    }
  }

  get selectedLabel(): string | undefined {
    const item = this.items.find((i) => i.value === this.value);
    return item ? item.label : undefined;
  }

  toggleOpen(): void {
    if (!this.disabled) {
      this.isOpen = !this.isOpen;
    }
  }

  selectItem(item: DsSelectItem): void {
    if (item.disabled) return;
    this.value = item.value;
    this.isOpen = false;
    this.onChange(item.value);
    this.valueChange.emit(item.value);
    this.onTouched();
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (!this.elementRef.nativeElement.contains(event.target)) {
      this.isOpen = false;
    }
  }

  @HostListener('keydown.escape')
  onEscape(): void {
    this.isOpen = false;
  }

  onChange: (value: string) => void = () => {};
  onTouched: () => void = () => {};

  writeValue(val: string): void {
    this.value = val || '';
  }

  registerOnChange(fn: (value: string) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}

// packages/react/src/components/Select/Select.tsx
import React, { useId, useMemo } from 'react';
import * as select from '@zag-js/select';
import { useMachine, normalizeProps, Portal } from '@zag-js/react';
import './Select.css';

export interface SelectItem {
  label: string;
  value: string;
  disabled?: boolean;
}

interface SelectBaseProps {
  items: SelectItem[];
  placeholder?: string;
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (details: { value: string[]; items: SelectItem[] }) => void;
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
  id?: string;
  name?: string;
  isInvalid?: boolean;
  errorMessage?: string;
  helperText?: string;
  'aria-labelledby'?: string;
  'aria-describedby'?: string;
}

export type SelectProps = SelectBaseProps & (
  | { label: string; 'aria-label'?: string }
  | { label?: string; 'aria-label': string }
  | { label?: string; 'aria-labelledby': string; 'aria-label'?: string }
);

export const Select: React.FC<SelectProps> = ({
  items,
  label,
  placeholder = 'Select an option...',
  value,
  defaultValue,
  onValueChange,
  disabled = false,
  size = 'md',
  id: customId,
  name,
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
  'aria-describedby': ariaDescribedBy,
  isInvalid = false,
  errorMessage,
  helperText,
}) => {
  const generatedId = useId();
  const id = customId || generatedId;
  const helperId = helperText ? `${id}-helper` : undefined;
  const errorId = errorMessage ? `${id}-error` : undefined;
  const invalid = isInvalid || Boolean(errorMessage);
  const describedByIds = [helperId, errorId, ariaDescribedBy].filter(Boolean).join(' ') || undefined;

  const collection = useMemo(
    () =>
      select.collection({
        items,
        itemToString: (item) => item.label,
        itemToValue: (item) => item.value,
        isItemDisabled: (item) => Boolean(item.disabled),
      }),
    [items]
  );

  const service = useMachine(select.machine, {
    id,
    name,
    collection,
    value,
    defaultValue,
    disabled,
    onValueChange(details) {
      onValueChange?.(details);
    },
  });

  const api = select.connect(service, normalizeProps);

  const currentValues = value !== undefined ? value : (api.value || []);
  const selectedItemLabels = items
    .filter((item) => currentValues.includes(item.value))
    .map((item) => item.label);

  const displayLabel =
    selectedItemLabels.length > 0
      ? selectedItemLabels.join(', ')
      : api.valueAsString || placeholder;
  const triggerProps = api.getTriggerProps();

  return (
    <div {...api.getRootProps()} className="ds-select-root">
      {label && (
        <label {...api.getLabelProps()} className="ds-select-label">
          {label}
        </label>
      )}

      {/* Hidden native select for form submission */}
      <select {...api.getHiddenSelectProps()}>
        {items.map((item) => (
          <option key={item.value} value={item.value} disabled={item.disabled}>
            {item.label}
          </option>
        ))}
      </select>

      <button
        type="button"
        role="combobox"
        {...triggerProps}
        aria-expanded={triggerProps['aria-expanded']}
        aria-controls={triggerProps['aria-controls']}
        aria-label={label ? undefined : ariaLabel}
        aria-labelledby={[label ? triggerProps['aria-labelledby'] : undefined, ariaLabelledBy].filter(Boolean).join(' ') || undefined}
        aria-invalid={invalid ? 'true' : undefined}
        aria-describedby={describedByIds}
        className={`ds-select-trigger ds-select-trigger--${size} ${invalid ? 'ds-select-trigger--invalid' : ''}`}
      >
        <span className="ds-select-value">
          {displayLabel}
        </span>
        <span className="ds-select-indicator" aria-hidden="true">
          ▼
        </span>
      </button>

      {helperText && (
        <p id={helperId} className="ds-select-helper-text">
          {helperText}
        </p>
      )}

      {errorMessage && (
        <p id={errorId} role="alert" className="ds-select-error-message">
          {errorMessage}
        </p>
      )}

      {api.open && (
        <Portal>
          <div {...api.getPositionerProps()} className="ds-select-positioner">
            <ul {...api.getContentProps()} className="ds-select-content">
              {items.map((item) => (
                <li
                  key={item.value}
                  {...api.getItemProps({ item })}
                  className="ds-select-item"
                >
                  <span {...api.getItemTextProps({ item })}>
                    {item.label}
                  </span>
                  <span {...api.getItemIndicatorProps({ item })} className="ds-select-item-indicator">
                    ✓
                  </span>
                </li>
              ))}
            </ul>
          </div>
        </Portal>
      )}
    </div>
  );
};
