// packages/angular/src/components/heatmap/heatmap.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  ElementRef,
  ViewChild,
  AfterViewInit,
  OnDestroy
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  createPlotRegion,
  createBandScale,
  createSequentialColorScale,
  createDivergingColorScale,
  formatVizValue,
  PlotMargins,
  getVizDensityTier,
  VizDensityTier
} from '../../utils/viz-core.js';

export type HeatmapVariant = 'matrix' | 'clustered' | 'calendar' | 'correlation';
export type HeatmapColorScaleType = 'sequential' | 'diverging';
export type HeatmapDensity = 'compact' | 'standard' | 'expanded';

@Component({
  selector: 'ds-heatmap',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      #containerRef
      class="ds-heatmap ds-heatmap--{{ variant }} ds-heatmap--density-{{ density }}"
      [ngClass]="{ 'ds-heatmap--loading': loading, 'ds-heatmap--empty': !loading && (!data || data.length === 0) }"
      [style.width]="'100%'"
      role="region"
      [attr.aria-label]="title || 'Heatmap matrix visualization'"
      [attr.aria-busy]="loading"
      tabindex="0"
      (keydown)="onKeyDown($event)"
      (pointerleave)="hoveredCell = null"
    >
      <ng-container *ngIf="loading">
        <div class="ds-heatmap__skeleton-header"></div>
        <div class="ds-heatmap__skeleton-plot" [style.height.px]="height"></div>
      </ng-container>

      <ng-container *ngIf="!loading && (!data || data.length === 0)">
        <h3 *ngIf="title" class="ds-heatmap__title">{{ title }}</h3>
        <div class="ds-heatmap__empty-msg" [style.height.px]="height">
          <p>{{ emptyMessage }}</p>
        </div>
      </ng-container>

      <ng-container *ngIf="!loading && data && data.length > 0">
        <div *ngIf="title || subtitle" class="ds-heatmap__header">
          <div>
            <h3 *ngIf="title" class="ds-heatmap__title">{{ title }}</h3>
            <p *ngIf="subtitle" class="ds-heatmap__subtitle">{{ subtitle }}</p>
          </div>
        </div>

        <svg
          width="100%"
          [attr.height]="height"
          [attr.viewBox]="'0 0 ' + plotWidth + ' ' + height"
          class="ds-heatmap__svg"
          style="overflow: visible; display: block; width: 100%; height: auto;"
          aria-hidden="true"
        >
          <defs>
            <pattern id="ds-heatmap-missing-hatch" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45 0 0)">
              <line x1="0" y1="0" x2="0" y2="6" stroke="var(--border-strong, #94a3b8)" stroke-width="1.2" opacity="0.4" />
            </pattern>

            <linearGradient id="ds-heatmap-legend-grad" x1="0" y1="1" x2="0" y2="0">
              <ng-container *ngIf="colorScaleType === 'diverging' || variant === 'correlation'">
                <stop offset="0%" [attr.stop-color]="colorRange[0] || '#ef4444'" />
                <stop offset="50%" [attr.stop-color]="colorRange[1] || '#f8fafc'" />
                <stop offset="100%" [attr.stop-color]="colorRange[2] || '#2563eb'" />
              </ng-container>
              <ng-container *ngIf="colorScaleType !== 'diverging' && variant !== 'correlation'">
                <stop offset="0%" [attr.stop-color]="colorRange[0] || '#eff6ff'" />
                <stop offset="100%" [attr.stop-color]="colorRange[1] || '#1d4ed8'" />
              </ng-container>
            </linearGradient>
          </defs>

          <g [attr.transform]="'translate(' + plot.margins.left + ', ' + plot.margins.top + ')'">
            <!-- Heatmap Grid Cells -->
            <g *ngFor="let row of rowLabels; let rIdx = index">
              <g *ngFor="let col of colLabels; let cIdx = index">
                <rect
                  class="ds-heatmap__cell"
                  [attr.x]="cellX(cIdx)"
                  [attr.y]="cellY(rIdx)"
                  [attr.width]="cellWidth"
                  [attr.height]="cellHeight"
                  [attr.rx]="cellRadius"
                  [attr.fill]="getCellFill(rIdx, cIdx)"
                  [attr.stroke]="isCellActive(rIdx, cIdx) ? 'var(--text-primary, #0f172a)' : 'rgba(0,0,0,0.06)'"
                  [attr.stroke-width]="isCellActive(rIdx, cIdx) ? 2 : 1"
                  (pointerenter)="onCellHover(rIdx, cIdx)"
                  (click)="onCellClick(rIdx, cIdx)"
                />
                <text
                  *ngIf="showCellValues && getCellValue(rIdx, cIdx) != null && cellWidth > 28 && cellHeight > 18"
                  [attr.x]="cellX(cIdx) + cellWidth / 2"
                  [attr.y]="cellY(rIdx) + cellHeight / 2"
                  dy="0.32em"
                  text-anchor="middle"
                  [attr.font-size]="fontSize"
                  font-weight="600"
                  [attr.fill]="getCellTextColor(rIdx, cIdx)"
                  pointer-events="none"
                >
                  {{ formatCellValue(getCellValue(rIdx, cIdx)) }}
                </text>
              </g>
            </g>

            <!-- X Axis (Column Labels on Bottom) -->
            <g class="ds-heatmap__axis">
              <g
                *ngFor="let col of colLabels; let cIdx = index"
                [attr.transform]="'translate(' + (cellX(cIdx) + cellWidth / 2) + ', ' + (plot.plotHeight + (isXRotated ? 12 : 18)) + ')'"
              >
                <text
                  [attr.transform]="isXRotated ? 'rotate(' + actualXAngle + ')' : null"
                  [attr.text-anchor]="isXRotated ? 'end' : 'middle'"
                  [attr.dx]="isXRotated ? -4 : 0"
                  [attr.dy]="isXRotated ? 4 : 0"
                  font-size="11"
                  font-weight="500"
                  fill="var(--text-secondary, #475569)"
                >
                  {{ col }}
                </text>
              </g>
            </g>

            <!-- Y Axis (Row Labels on Left) -->
            <g class="ds-heatmap__axis">
              <g *ngFor="let row of rowLabels; let rIdx = index" [attr.transform]="'translate(0, ' + (cellY(rIdx) + cellHeight / 2) + ')'">
                <text x="-12" dy="0.32em" text-anchor="end" font-size="11" font-weight="500" fill="var(--text-secondary, #475569)">{{ row }}</text>
              </g>
            </g>

            <!-- Vertical Legend Bar -->
            <g
              *ngIf="showLegend"
              [attr.transform]="'translate(' + (plot.plotWidth + 24) + ', 10)'"
              class="ds-heatmap__legend-group"
            >
              <text x="0" y="-6" class="ds-heatmap__legend-title">{{ unit || 'Intensity' }}</text>
              <rect
                x="0"
                y="0"
                width="12"
                [attr.height]="plot.plotHeight - 20"
                fill="url(#ds-heatmap-legend-grad)"
                stroke="var(--border-subtle, #cbd5e1)"
                rx="2"
              />
              <text x="18" y="8" dy="0.32em" class="ds-heatmap__legend-tick">
                {{ formatVal(minMaxVals[1]) }}
              </text>
              <text
                *ngIf="colorScaleType === 'diverging' || variant === 'correlation'"
                x="18"
                [attr.y]="(plot.plotHeight - 20) / 2"
                dy="0.32em"
                class="ds-heatmap__legend-tick"
              >
                {{ formatVal(neutralValue) }}
              </text>
              <text x="18" [attr.y]="plot.plotHeight - 24" dy="0.32em" class="ds-heatmap__legend-tick">
                {{ formatVal(minMaxVals[0]) }}
              </text>
            </g>
          </g>
        </svg>

        <!-- Tooltip -->
        <div
          *ngIf="hoveredCell"
          class="ds-heatmap__tooltip"
          [style.left.px]="tooltipLeft"
          [style.top.px]="tooltipTop"
          role="tooltip"
        >
          <strong>{{ hoveredCell.row }} × {{ hoveredCell.col }}</strong>
          <div>
            {{ valueLabel }}:
            <strong>{{ hoveredCell.value != null ? formatVal(hoveredCell.value) : missingCellLabel }}</strong>
          </div>
          <div *ngIf="variant === 'correlation' && hoveredCell.value != null" style="font-size: 11px; color: var(--text-secondary, #64748b); margin-top: 2px;">
            <em>{{ hoveredCell.value > 0.7 ? 'Strong Positive' : hoveredCell.value < -0.7 ? 'Strong Negative' : 'Weak / Neutral' }}</em>
          </div>
        </div>

        <!-- Accessibility Live Announcer -->
        <div class="ds-heatmap__sr-only" style="position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0, 0, 0, 0);" aria-live="polite">
          {{ activeCellText }}
        </div>

        <!-- Accessible Tabular Matrix Mirror -->
        <details
          *ngIf="showDataTable && data && data.length > 0"
          class="ds-chart-table-details"
        >
          <summary class="ds-chart-table-summary">
            View Accessible Data Matrix
          </summary>
          <div class="ds-chart-table-wrap">
            <table class="ds-chart-table">
              <caption style="position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0, 0, 0, 0);">
                {{ title ? title + ' Data Matrix' : 'Heatmap Data Matrix' }}
              </caption>
              <thead>
                <tr>
                  <th scope="col">{{ rowLabel || 'Row / Col' }}</th>
                  <th *ngFor="let c of colLabels" scope="col">{{ c }}</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let r of rowLabels; let rIdx = index">
                  <th scope="row">{{ r }}</th>
                  <td *ngFor="let c of colLabels; let cIdx = index">
                    {{ getCellValue(rIdx, cIdx) != null ? formatVizValue(getCellValue(rIdx, cIdx)!, unit, locale) : missingCellLabel }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </details>
      </ng-container>
    </div>
  `,
  styleUrls: ['./heatmap.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DsHeatmapComponent implements AfterViewInit, OnDestroy {
  formatVizValue = formatVizValue;

  @Input() data: Array<Record<string, any>> = [];
  @Input() rows: string[] = [];
  @Input() cols: string[] = [];
  @Input() rowKey: string = 'row';
  @Input() colKey: string = 'col';
  @Input() valueKey: string = 'value';
  @Input() variant: HeatmapVariant = 'matrix';
  @Input() colorScaleType: HeatmapColorScaleType = 'sequential';
  @Input() colorRange: string[] = ['#eff6ff', '#1d4ed8'];
  @Input() domain: [number, number] | null = null;
  @Input() neutralValue: number = 0;
  @Input() cellPadding: number = 2;
  @Input() cellRadius: number = 2;
  @Input() showCellValues: boolean = false;
  @Input() width: number = 640;
  @Input() height: number = 360;
  @Input() margins?: Partial<PlotMargins>;
  @Input() unit: string = '';
  @Input() rowLabel: string = 'Row Dimension';
  @Input() colLabel: string = 'Column Dimension';
  @Input() valueLabel: string = 'Intensity Value';
  @Input() locale: string = 'en-IN';
  @Input() title: string = '';
  @Input() subtitle: string = '';
  @Input() missingCellLabel: string = 'No Record / Down';
  @Input() showLegend: boolean = true;
  @Input() showDataTable: boolean = true;
  @Input() density: HeatmapDensity = 'standard';
  @Input() emptyMessage: string = 'No matrix observation records found.';
  @Input() loading: boolean = false;
  @Input() rotateXLabels: boolean | 'auto' = 'auto';
  @Input() xLabelAngle: number = -45;

  @Output() cellSelect = new EventEmitter<{ datum: Record<string, any>; coords: { rIdx: number; cIdx: number } }>();

  @ViewChild('containerRef') containerRef?: ElementRef<HTMLDivElement>;

  hoveredCell: any = null;
  activeCellCoord: { rIdx: number; cIdx: number } | null = null;
  selectedCellCoord: { rIdx: number; cIdx: number } | null = null;

  measuredWidth: number = 0;
  private resizeObserver?: ResizeObserver;

  constructor(private cdr: ChangeDetectorRef) {}

  ngAfterViewInit(): void {
    if (this.containerRef?.nativeElement && typeof ResizeObserver !== 'undefined') {
      this.resizeObserver = new ResizeObserver((entries) => {
        for (const entry of entries) {
          const w = Math.floor(entry.contentRect.width);
          if (w > 0) {
            this.measuredWidth = w;
            this.cdr.markForCheck();
          }
        }
      });
      this.resizeObserver.observe(this.containerRef.nativeElement);
    }
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
  }

  get plotWidth(): number {
    return Math.max(280, this.measuredWidth || this.width);
  }

  get densityTier(): VizDensityTier {
    return getVizDensityTier(this.plotWidth);
  }

  get resolvedMargins(): PlotMargins {
    const isMobile = this.densityTier === 'compact' || this.densityTier === 'mobile';
    const defaultRight = this.showLegend ? (isMobile ? 54 : 80) : 24;
    const isRotatedExpected = this.rotateXLabels === true || isMobile;
    const maxRowLabelLen = Math.max(0, ...this.rowLabels.map(l => String(l).length));
    const autoLeft = isMobile
      ? Math.max(54, Math.min(120, Math.round(maxRowLabelLen * 5.5 + 16)))
      : Math.max(88, Math.min(220, Math.round(maxRowLabelLen * 7.5 + 24)));
    return {
      top: this.margins?.top ?? 32,
      right: this.margins?.right ?? defaultRight,
      bottom: this.margins?.bottom ?? (isRotatedExpected ? 56 : 48),
      left: this.margins?.left ?? autoLeft
    };
  }

  get rowLabels(): string[] {
    if (this.rows && this.rows.length > 0) return this.rows;
    if (!this.data || this.data.length === 0) return [];
    return Array.from(new Set(this.data.map(d => String(d[this.rowKey])))).filter(Boolean);
  }

  get colLabels(): string[] {
    if (this.cols && this.cols.length > 0) return this.cols;
    if (!this.data || this.data.length === 0) return [];
    return Array.from(new Set(this.data.map(d => String(d[this.colKey])))).filter(Boolean);
  }

  get plot() {
    return createPlotRegion({
      containerWidth: this.plotWidth,
      containerHeight: this.height,
      margins: this.resolvedMargins
    });
  }

  get matrixLookup(): Map<string, any> {
    const map = new Map();
    this.data.forEach(d => {
      const r = String(d[this.rowKey]);
      const c = String(d[this.colKey]);
      map.set(`${r}:::${c}`, d);
    });
    return map;
  }

  get minMaxVals(): [number, number] {
    if (this.domain) return this.domain;
    if (this.variant === 'correlation') return [-1, 1];
    const vals = this.data.map(d => Number(d[this.valueKey])).filter(v => !isNaN(v));
    if (vals.length === 0) return [0, 100];
    return [Math.min(...vals), Math.max(...vals)];
  }

  get colorScaleFn(): (val: any) => string {
    const [minV, maxV] = this.minMaxVals;
    if (this.colorScaleType === 'diverging' || this.variant === 'correlation') {
      return createDivergingColorScale({
        domain: [minV, maxV],
        colors: this.colorRange.length >= 3 ? (this.colorRange as [string, string, string]) : ['#ef4444', '#f8fafc', '#2563eb'],
        neutral: this.neutralValue
      });
    }
    return createSequentialColorScale({
      domain: [minV, maxV],
      colors: this.colorRange.length >= 2 ? (this.colorRange as [string, string]) : ['#eff6ff', '#1d4ed8']
    });
  }

  get cellWidth(): number {
    const colsCount = Math.max(1, this.colLabels.length);
    return Math.max(2, (this.plot.plotWidth - (colsCount - 1) * this.cellPadding) / colsCount);
  }

  get cellHeight(): number {
    const rowsCount = Math.max(1, this.rowLabels.length);
    return Math.max(2, (this.plot.plotHeight - (rowsCount - 1) * this.cellPadding) / rowsCount);
  }

  get isXRotated(): boolean {
    return this.rotateXLabels === true || (this.rotateXLabels === 'auto' && this.cellWidth < 36);
  }

  get actualXAngle(): number {
    return this.xLabelAngle ?? (this.isXRotated ? -45 : 0);
  }

  get fontSize(): number {
    return Math.min(11, Math.max(9, this.cellHeight * 0.45));
  }

  cellX(cIdx: number): number {
    return cIdx * (this.cellWidth + this.cellPadding);
  }

  cellY(rIdx: number): number {
    return rIdx * (this.cellHeight + this.cellPadding);
  }

  getCellValue(rIdx: number, cIdx: number): number | null {
    const r = this.rowLabels[rIdx];
    const c = this.colLabels[cIdx];
    const datum = this.matrixLookup.get(`${r}:::${c}`);
    if (!datum || datum[this.valueKey] == null) return null;
    const v = Number(datum[this.valueKey]);
    return isNaN(v) ? null : v;
  }

  getCellFill(rIdx: number, cIdx: number): string {
    const v = this.getCellValue(rIdx, cIdx);
    if (v == null) return 'url(#ds-heatmap-missing-hatch)';
    return this.colorScaleFn(v);
  }

  getCellTextColor(rIdx: number, cIdx: number): string {
    const fill = this.getCellFill(rIdx, cIdx);
    if (!fill || fill === 'transparent' || fill.startsWith('url(')) {
      return 'var(--text-primary, #0f172a)';
    }
    let r = 255, g = 255, b = 255;
    if (fill.startsWith('#')) {
      const hex = fill.replace('#', '');
      if (hex.length === 3) {
        r = parseInt(hex[0] + hex[0], 16);
        g = parseInt(hex[1] + hex[1], 16);
        b = parseInt(hex[2] + hex[2], 16);
      } else if (hex.length >= 6) {
        r = parseInt(hex.slice(0, 2), 16);
        g = parseInt(hex.slice(2, 4), 16);
        b = parseInt(hex.slice(4, 6), 16);
      }
    } else if (fill.startsWith('rgb')) {
      const match = fill.match(/\d+/g);
      if (match && match.length >= 3) {
        r = parseInt(match[0], 10);
        g = parseInt(match[1], 10);
        b = parseInt(match[2], 10);
      }
    }
    const luminance = 0.299 * r + 0.587 * g + 0.114 * b;
    return luminance < 145 ? '#ffffff' : 'var(--text-primary, #0f172a)';
  }

  formatCellValue(val: number | null): string {
    if (val == null || isNaN(val)) return '';
    if (this.variant === 'correlation') {
      return val.toFixed(2);
    }
    if (Number.isInteger(val)) {
      return val.toString();
    }
    return val.toFixed(1);
  }

  formatVal(val: any): string {
    if (val == null) return this.missingCellLabel;
    return formatVizValue(val, this.unit, this.locale);
  }

  isCellActive(rIdx: number, cIdx: number): boolean {
    return (
      (this.activeCellCoord?.rIdx === rIdx && this.activeCellCoord?.cIdx === cIdx) ||
      (this.selectedCellCoord?.rIdx === rIdx && this.selectedCellCoord?.cIdx === cIdx)
    );
  }

  get tooltipLeft(): number {
    const raw = this.plot.margins.left + (this.hoveredCell?.cIdx ?? 0) * (this.cellWidth + this.cellPadding) + this.cellWidth / 2 + 10;
    return Math.max(10, Math.min(raw, this.width - 210));
  }

  get tooltipTop(): number {
    const raw = this.plot.margins.top + (this.hoveredCell?.rIdx ?? 0) * (this.cellHeight + this.cellPadding) - 15;
    return Math.max(10, Math.min(raw, this.height - 90));
  }

  get activeCellText(): string {
    if (!this.activeCellCoord) return '';
    const r = this.rowLabels[this.activeCellCoord.rIdx];
    const c = this.colLabels[this.activeCellCoord.cIdx];
    const v = this.getCellValue(this.activeCellCoord.rIdx, this.activeCellCoord.cIdx);
    return `Selected matrix cell ${r}, ${c}: ${v != null ? `${v} ${this.unit}` : this.missingCellLabel}.`;
  }

  onCellHover(rIdx: number, cIdx: number): void {
    const r = this.rowLabels[rIdx];
    const c = this.colLabels[cIdx];
    const val = this.getCellValue(rIdx, cIdx);
    this.hoveredCell = { rIdx, cIdx, row: r, col: c, value: val };
    this.activeCellCoord = { rIdx, cIdx };
  }

  onCellClick(rIdx: number, cIdx: number): void {
    const r = this.rowLabels[rIdx];
    const c = this.colLabels[cIdx];
    const datum = this.matrixLookup.get(`${r}:::${c}`) || { [this.rowKey]: r, [this.colKey]: c };
    this.selectedCellCoord = { rIdx, cIdx };
    this.cellSelect.emit({ datum, coords: { rIdx, cIdx } });
  }

  onKeyDown(e: KeyboardEvent): void {
    if (this.rowLabels.length === 0 || this.colLabels.length === 0) return;

    let r = this.activeCellCoord ? this.activeCellCoord.rIdx : 0;
    let c = this.activeCellCoord ? this.activeCellCoord.cIdx : 0;

    switch (e.key) {
      case 'ArrowRight':
        e.preventDefault();
        c = (c + 1) % this.colLabels.length;
        this.activeCellCoord = { rIdx: r, cIdx: c };
        this.onCellHover(r, c);
        break;
      case 'ArrowLeft':
        e.preventDefault();
        c = (c - 1 + this.colLabels.length) % this.colLabels.length;
        this.activeCellCoord = { rIdx: r, cIdx: c };
        this.onCellHover(r, c);
        break;
      case 'ArrowDown':
        e.preventDefault();
        r = (r + 1) % this.rowLabels.length;
        this.activeCellCoord = { rIdx: r, cIdx: c };
        this.onCellHover(r, c);
        break;
      case 'ArrowUp':
        e.preventDefault();
        r = (r - 1 + this.rowLabels.length) % this.rowLabels.length;
        this.activeCellCoord = { rIdx: r, cIdx: c };
        this.onCellHover(r, c);
        break;
      case 'Home':
        e.preventDefault();
        this.activeCellCoord = { rIdx: 0, cIdx: 0 };
        this.onCellHover(0, 0);
        break;
      case 'End':
        e.preventDefault();
        this.activeCellCoord = { rIdx: this.rowLabels.length - 1, cIdx: this.colLabels.length - 1 };
        this.onCellHover(this.rowLabels.length - 1, this.colLabels.length - 1);
        break;
      case 'Enter':
      case ' ':
        e.preventDefault();
        if (this.activeCellCoord) {
          this.onCellClick(this.activeCellCoord.rIdx, this.activeCellCoord.cIdx);
        }
        break;
      case 'Escape':
        e.preventDefault();
        this.activeCellCoord = null;
        this.hoveredCell = null;
        break;
    }
  }
}

// packages/react/src/components/Heatmap/Heatmap.tsx
/* eslint-disable jsx-a11y/no-noninteractive-element-interactions -- keyboard-operated visualization surface; interactive controls retain native semantics */
/* eslint-disable jsx-a11y/no-noninteractive-tabindex -- chart region is intentionally keyboard reachable */
import React, { useState, useRef, useId, useMemo } from 'react';
import {
  formatVizValue,
  createPlotRegion,
  createBandScale,
  createSequentialColorScale,
  createDivergingColorScale,
  useResponsiveVizBounds
} from '../../utils/viz-core.js';

export type HeatmapVariant = 'matrix' | 'clustered' | 'calendar' | 'correlation';
export type HeatmapColorScaleType = 'sequential' | 'diverging';
export type HeatmapDensity = 'compact' | 'standard' | 'expanded';

export interface HeatmapProps {
  data: Array<Record<string, any>>;
  rows?: string[];
  cols?: string[];
  rowKey?: string;
  colKey?: string;
  valueKey?: string;
  variant?: HeatmapVariant;
  colorScaleType?: HeatmapColorScaleType;
  colorRange?: string[];
  domain?: [number, number] | null;
  neutralValue?: number;
  cellPadding?: number;
  cellRadius?: number;
  showCellValues?: boolean;
  width?: number;
  height?: number;
  margins?: { top?: number; right?: number; bottom?: number; left?: number };
  unit?: string;
  rowLabel?: string;
  colLabel?: string;
  valueLabel?: string;
  locale?: string;
  title?: string;
  subtitle?: string;
  missingCellLabel?: string;
  showLegend?: boolean;
  showDataTable?: boolean;
  density?: HeatmapDensity;
  emptyMessage?: string;
  loading?: boolean;
  rotateXLabels?: boolean | 'auto';
  xLabelAngle?: number;
  onCellSelect?: (datum: Record<string, any>, coords: { rIdx: number; cIdx: number }) => void;
  className?: string;
  style?: React.CSSProperties;
}

export function getContrastTextColor(colorStr: string): string {
  if (!colorStr || colorStr === 'transparent' || colorStr.startsWith('url(')) {
    return 'var(--text-primary, #0f172a)';
  }
  let r = 255, g = 255, b = 255;
  if (colorStr.startsWith('#')) {
    const hex = colorStr.replace('#', '');
    if (hex.length === 3) {
      r = parseInt(hex[0] + hex[0], 16);
      g = parseInt(hex[1] + hex[1], 16);
      b = parseInt(hex[2] + hex[2], 16);
    } else if (hex.length >= 6) {
      r = parseInt(hex.slice(0, 2), 16);
      g = parseInt(hex.slice(2, 4), 16);
      b = parseInt(hex.slice(4, 6), 16);
    }
  } else if (colorStr.startsWith('rgb')) {
    const match = colorStr.match(/\d+/g);
    if (match && match.length >= 3) {
      r = parseInt(match[0], 10);
      g = parseInt(match[1], 10);
      b = parseInt(match[2], 10);
    }
  }
  const luminance = 0.299 * r + 0.587 * g + 0.114 * b;
  return luminance < 145 ? '#ffffff' : 'var(--text-primary, #0f172a)';
}

export function formatCellValue(val: number | null, variant: HeatmapVariant = 'matrix'): string {
  if (val == null || isNaN(val)) return '';
  if (variant === 'correlation') {
    return val.toFixed(2);
  }
  if (Number.isInteger(val)) {
    return val.toString();
  }
  return val.toFixed(1);
}

/**
 * Heatmap — Meridian Design System
 *
 * Visualizes patterns, intensity gradients, correlations, and anomalies across
 * two-dimensional categorical, ordinal, or discretized quantitative structures.
 */
export const Heatmap: React.FC<HeatmapProps> = ({
  data = [],
  rows = [],
  cols = [],
  rowKey = 'row',
  colKey = 'col',
  valueKey = 'value',
  variant = 'matrix',
  colorScaleType = 'sequential',
  colorRange = ['#eff6ff', '#1d4ed8'],
  domain = null,
  neutralValue = 0,
  cellPadding = 2,
  cellRadius = 2,
  showCellValues = false,
  width = 640,
  height = 360,
  margins,
  unit = '',
  rowLabel = 'Row Dimension',
  colLabel: _colLabel = 'Column Dimension',
  valueLabel = 'Intensity Value',
  locale = 'en-IN',
  title,
  subtitle,
  missingCellLabel = 'No Record / Down',
  showLegend = true,
  showDataTable = true,
  density = 'standard',
  emptyMessage = 'No matrix observation records found.',
  loading = false,
  rotateXLabels = 'auto',
  xLabelAngle = -45,
  onCellSelect,
  className = '',
  style = {}
}) => {
  const chartId = useId();
  const containerRef = useRef<HTMLDivElement>(null);
  const { width: measuredWidth, height: measuredHeight, densityTier } = useResponsiveVizBounds(containerRef, typeof width === 'number' ? width : 640, typeof height === 'number' ? height : 360);

  const plotWidth = Math.max(280, measuredWidth || (typeof width === 'number' ? width : 640));
  const plotHeight = Math.max(180, measuredHeight || (typeof height === 'number' ? height : 360));

  const [activeCellCoord, setActiveCellCoord] = useState<{ rIdx: number; cIdx: number } | null>(null);
  const [selectedCellCoord, setSelectedCellCoord] = useState<{ rIdx: number; cIdx: number } | null>(null);

  // Extract distinct row & column labels
  const rowLabels = useMemo(() => {
    if (rows && rows.length > 0) return rows;
    if (!data || data.length === 0) return [];
    return Array.from(new Set(data.map(d => String(d[rowKey])))).filter(Boolean);
  }, [rows, data, rowKey]);

  const colLabels = useMemo(() => {
    if (cols && cols.length > 0) return cols;
    if (!data || data.length === 0) return [];
    return Array.from(new Set(data.map(d => String(d[colKey])))).filter(Boolean);
  }, [cols, data, colKey]);

  const maxRowLabelLen = useMemo(() => {
    return Math.max(0, ...rowLabels.map(l => String(l).length));
  }, [rowLabels]);

  const resolvedMargins = useMemo(() => {
    const isMobile = densityTier === 'compact';
    const defaultRight = showLegend ? (isMobile ? 50 : 80) : 24;
    const isRotatedExpected = rotateXLabels === true || (rotateXLabels === 'auto' && (isMobile || colLabels.length > 6));
    const autoLeft = isMobile
      ? Math.max(54, Math.min(120, Math.round(maxRowLabelLen * 5.5 + 16)))
      : Math.max(88, Math.min(220, Math.round(maxRowLabelLen * 7.5 + 24)));
    return {
      top: margins?.top ?? 32,
      right: margins?.right ?? defaultRight,
      bottom: margins?.bottom ?? (isRotatedExpected ? 56 : 48),
      left: margins?.left ?? autoLeft
    };
  }, [margins, showLegend, rotateXLabels, maxRowLabelLen, densityTier, colLabels.length]);

  // Compute 2D Data Grid Matrix Lookup
  const { gridMatrix, minVal, maxVal } = useMemo(() => {
    const map = new Map<string, { datum: any; value: number | null }>();
    const vals: number[] = [];

    data.forEach(d => {
      const r = String(d[rowKey]);
      const c = String(d[colKey]);
      const v = d[valueKey] != null ? Number(d[valueKey]) : null;
      map.set(`${r}:::${c}`, { datum: d, value: v });
      if (v != null && !isNaN(v)) vals.push(v);
    });

    const matrix = rowLabels.map(r => {
      return colLabels.map(c => {
        const item = map.get(`${r}:::${c}`);
        return item || { datum: { [rowKey]: r, [colKey]: c }, value: null };
      });
    });

    let minV = 0, maxV = 100;
    if (vals.length > 0) {
      minV = Math.min(...vals);
      maxV = Math.max(...vals);
    }
    if (domain) {
      minV = domain[0];
      maxV = domain[1];
    } else if (variant === 'correlation') {
      minV = -1;
      maxV = 1;
    }

    return { gridMatrix: matrix, allValues: vals, minVal: minV, maxVal: maxV };
  }, [data, rowLabels, colLabels, rowKey, colKey, valueKey, domain, variant]);

  // Dimensions & Plot Region
  const plot = useMemo(() => {
    return createPlotRegion({
      containerWidth: plotWidth,
      containerHeight: plotHeight,
      margins: resolvedMargins
    });
  }, [plotWidth, plotHeight, resolvedMargins]);

  // Compute Scales
  const scales = useMemo(() => {
    if (rowLabels.length === 0 || colLabels.length === 0) {
      return { scaleX: null, scaleY: null, colorScale: null };
    }

    const scaleX = createBandScale({
      domain: colLabels,
      range: [0, plot.plotWidth],
      paddingInner: 0,
      paddingOuter: 0
    });

    const scaleY = createBandScale({
      domain: rowLabels,
      range: [0, plot.plotHeight],
      paddingInner: 0,
      paddingOuter: 0
    });

    let colorScale: any;
    if (colorScaleType === 'diverging' || variant === 'correlation') {
      colorScale = createDivergingColorScale({
        domain: [minVal, maxVal],
        colors: (colorRange.length >= 3 ? colorRange : ['#ef4444', '#f8fafc', '#2563eb']) as [string, string, string],
        neutral: neutralValue
      });
    } else {
      colorScale = createSequentialColorScale({
        domain: [minVal, maxVal],
        colors: (colorRange.length >= 2 ? colorRange : ['#eff6ff', '#1d4ed8']) as [string, string]
      });
    }

    return { scaleX, scaleY, colorScale };
  }, [rowLabels, colLabels, plot, colorScaleType, variant, minVal, maxVal, colorRange, neutralValue]);

  // 2D Keyboard Handler
  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (rowLabels.length === 0 || colLabels.length === 0) return;

    let r = activeCellCoord ? activeCellCoord.rIdx : 0;
    let c = activeCellCoord ? activeCellCoord.cIdx : 0;

    switch (e.key) {
      case 'ArrowRight':
        e.preventDefault();
        c = (c + 1) % colLabels.length;
        setActiveCellCoord({ rIdx: r, cIdx: c });
        break;
      case 'ArrowLeft':
        e.preventDefault();
        c = (c - 1 + colLabels.length) % colLabels.length;
        setActiveCellCoord({ rIdx: r, cIdx: c });
        break;
      case 'ArrowDown':
        e.preventDefault();
        r = (r + 1) % rowLabels.length;
        setActiveCellCoord({ rIdx: r, cIdx: c });
        break;
      case 'ArrowUp':
        e.preventDefault();
        r = (r - 1 + rowLabels.length) % rowLabels.length;
        setActiveCellCoord({ rIdx: r, cIdx: c });
        break;
      case 'Home':
        e.preventDefault();
        setActiveCellCoord({ rIdx: 0, cIdx: 0 });
        break;
      case 'End':
        e.preventDefault();
        setActiveCellCoord({ rIdx: rowLabels.length - 1, cIdx: colLabels.length - 1 });
        break;
      case 'Enter':
      case ' ':
        e.preventDefault();
        if (activeCellCoord) {
          setSelectedCellCoord(activeCellCoord);
          const cellItem = gridMatrix[activeCellCoord.rIdx][activeCellCoord.cIdx];
          if (onCellSelect) onCellSelect(cellItem.datum, activeCellCoord);
        }
        break;
      case 'Escape':
        e.preventDefault();
        setActiveCellCoord(null);
        break;
      default:
        break;
    }
  };

  const activeCell = (activeCellCoord && gridMatrix[activeCellCoord.rIdx])
    ? gridMatrix[activeCellCoord.rIdx][activeCellCoord.cIdx]
    : null;

  if (loading) {
    return (
      <div
        className={`mds-heatmap mds-heatmap--loading ${className}`}
        style={{ width, height, ...style }}
        role="region"
        aria-label={title || 'Heatmap Loading'}
        aria-busy="true"
      >
        <div className="mds-heatmap__skeleton-header">
          <div className="mds-heatmap__skeleton-title" />
          <div className="mds-heatmap__skeleton-sub" />
        </div>
        <div className="mds-heatmap__skeleton-plot" />
      </div>
    );
  }

  if (!data || data.length === 0 || rowLabels.length === 0 || colLabels.length === 0) {
    return (
      <div
        className={`mds-heatmap mds-heatmap--empty ${className}`}
        style={{ width, height, ...style }}
        role="region"
        aria-label={title || 'Heatmap Empty'}
      >
        {title && <h2 className="mds-heatmap__title">{title}</h2>}
        <div className="mds-heatmap__empty-msg">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
            <rect x="3" y="3" width="7" height="7" rx="1" />
            <rect x="14" y="3" width="7" height="7" rx="1" />
            <rect x="14" y="14" width="7" height="7" rx="1" />
            <rect x="3" y="14" width="7" height="7" rx="1" />
          </svg>
          <p>{emptyMessage}</p>
        </div>
      </div>
    );
  }

  const cellWidth = scales.scaleX ? scales.scaleX.bandwidth() : 0;
  const cellHeight = scales.scaleY ? scales.scaleY.bandwidth() : 0;
  const isXRotated = rotateXLabels === true || (rotateXLabels === 'auto' && cellWidth < 36);
  const actualXAngle = xLabelAngle ?? (isXRotated ? -45 : 0);

  return (
    <div
      ref={containerRef}
      className={`mds-heatmap mds-heatmap--${variant} mds-heatmap--density-${density} ${className}`}
      style={{ width: typeof width === 'number' ? `${width}px` : width, maxWidth: '100%', ...style }}
      role="region"
      aria-roledescription="heatmap"
      aria-label={title || '2D Heatmap Matrix Visualization'}
      tabIndex={0}
      onKeyDown={handleKeyDown}
    >
      {(title || subtitle) && (
        <div className="mds-heatmap__header">
          <div>
            {title && <h2 className="mds-heatmap__title">{title}</h2>}
            {subtitle && <p className="mds-heatmap__subtitle">{subtitle}</p>}
          </div>
        </div>
      )}

      <svg
        width="100%"
        height={plotHeight}
        viewBox={`0 0 ${plotWidth} ${plotHeight}`}
        className="mds-heatmap__svg mds-chart-svg"
        style={{ overflow: 'visible', display: 'block' }}
        aria-hidden="true"
        onClick={() => setActiveCellCoord(null)}
      >
        <defs>
          <pattern id={`${chartId}-missing-hatch`} width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45 0 0)">
            <line x1="0" y1="0" x2="0" y2="6" stroke="var(--border-strong, #94a3b8)" strokeWidth="1.2" opacity="0.4" />
          </pattern>

          <linearGradient id={`${chartId}-legend-grad`} x1="0" y1="1" x2="0" y2="0">
            {colorScaleType === 'diverging' || variant === 'correlation' ? (
              <>
                <stop offset="0%" stopColor={colorRange[0] || '#ef4444'} />
                <stop offset="50%" stopColor={colorRange[1] || '#f8fafc'} />
                <stop offset="100%" stopColor={colorRange[2] || '#2563eb'} />
              </>
            ) : (
              <>
                <stop offset="0%" stopColor={colorRange[0] || '#eff6ff'} />
                <stop offset="100%" stopColor={colorRange[1] || '#1d4ed8'} />
              </>
            )}
          </linearGradient>
        </defs>

        <g transform={`translate(${plot.margins.left}, ${plot.margins.top})`}>
          {gridMatrix.map((rowCells, rIdx) => {
            const rLabel = rowLabels[rIdx];
            const yPos = scales.scaleY ? (scales.scaleY(rLabel) ?? 0) : 0;

            return (
              <g key={`row-${rLabel}`} className="mds-heatmap__row" role="row">
                {rowCells.map((cell, cIdx) => {
                  const cLabel = colLabels[cIdx];
                  const xPos = scales.scaleX ? (scales.scaleX(cLabel) ?? 0) : 0;
                  const isNull = cell.value == null || isNaN(cell.value);
                  const fill = isNull ? `url(#${chartId}-missing-hatch)` : (scales.colorScale ? scales.colorScale(cell.value) : 'transparent');
                  const isActive = activeCellCoord && activeCellCoord.rIdx === rIdx && activeCellCoord.cIdx === cIdx;
                  const isSelected = selectedCellCoord && selectedCellCoord.rIdx === rIdx && selectedCellCoord.cIdx === cIdx;
                  const textColor = getContrastTextColor(fill);

                  return (
                    <g
                      key={`cell-${rLabel}-${cLabel}`}
                      transform={`translate(${xPos + cellPadding / 2}, ${yPos + cellPadding / 2})`}
                      className="mds-heatmap__cell-group"
                      onPointerEnter={(e) => {
                        e.stopPropagation();
                        setActiveCellCoord({ rIdx, cIdx });
                      }}
                      onClick={(e) => {
                        e.stopPropagation();
                        setSelectedCellCoord({ rIdx, cIdx });
                        if (onCellSelect) onCellSelect(cell.datum, { rIdx, cIdx });
                      }}
                      style={{ cursor: 'pointer' }}
                    >
                      <rect
                        width={Math.max(2, cellWidth - cellPadding)}
                        height={Math.max(2, cellHeight - cellPadding)}
                        rx={cellRadius}
                        fill={fill}
                        stroke={isActive || isSelected ? 'var(--text-primary, #0f172a)' : 'rgba(0,0,0,0.06)'}
                        strokeWidth={isActive || isSelected ? 2 : 1}
                        className="mds-heatmap__cell"
                      />
                      {showCellValues && !isNull && cell.value != null && cellWidth > 28 && cellHeight > 18 && (
                        <text
                          x={(cellWidth - cellPadding) / 2}
                          y={(cellHeight - cellPadding) / 2}
                          dy="0.32em"
                          textAnchor="middle"
                          fill={textColor}
                          className="mds-heatmap__cell-text"
                          style={{ fontSize: Math.min(11, Math.max(9, cellHeight * 0.45)), pointerEvents: 'none' }}
                        >
                          {formatCellValue(cell.value, variant)}
                        </text>
                      )}
                    </g>
                  );
                })}
              </g>
            );
          })}

          {rowLabels.map((rLabel) => {
            const yPos = scales.scaleY ? ((scales.scaleY(rLabel) ?? 0) + cellHeight / 2) : 0;
            return (
              <text
                key={`ylabel-${rLabel}`}
                x="-12"
                y={yPos}
                dy="0.32em"
                textAnchor="end"
                fontSize="11"
                fontWeight="500"
                fill="var(--text-secondary, #475569)"
                className="mds-heatmap__row-label"
              >
                {rLabel}
              </text>
            );
          })}

          {colLabels.map((cLabel) => {
            const xPos = scales.scaleX ? ((scales.scaleX(cLabel) ?? 0) + cellWidth / 2) : 0;
            const yPos = plot.plotHeight + (isXRotated ? 12 : 18);
            return (
              <g
                key={`xlabel-${cLabel}`}
                transform={`translate(${xPos}, ${yPos})`}
              >
                <text
                  transform={isXRotated ? `rotate(${actualXAngle})` : undefined}
                  textAnchor={isXRotated ? 'end' : 'middle'}
                  dx={isXRotated ? '-4' : '0'}
                  dy={isXRotated ? '4' : '0'}
                  fontSize="11"
                  fontWeight="500"
                  fill="var(--text-secondary, #475569)"
                  className="mds-heatmap__col-label"
                >
                  {cLabel}
                </text>
              </g>
            );
          })}

          {showLegend && (
            <g transform={`translate(${plot.plotWidth + 24}, 10)`} className="mds-heatmap__legend-group">
              <text x="0" y="-6" className="mds-heatmap__legend-title">{unit || 'Intensity'}</text>
              <rect
                x="0"
                y="0"
                width="12"
                height={plot.plotHeight - 20}
                fill={`url(#${chartId}-legend-grad)`}
                stroke="var(--border-subtle, #cbd5e1)"
                rx="2"
              />
              <text x="18" y="8" dy="0.32em" className="mds-heatmap__legend-tick">
                {formatVizValue(maxVal, unit, locale)}
              </text>
              {colorScaleType === 'diverging' && (
                <text x="18" y={(plot.plotHeight - 20) / 2} dy="0.32em" className="mds-heatmap__legend-tick">
                  {formatVizValue(neutralValue, unit, locale)}
                </text>
              )}
              <text x="18" y={plot.plotHeight - 24} dy="0.32em" className="mds-heatmap__legend-tick">
                {formatVizValue(minVal, unit, locale)}
              </text>
            </g>
          )}
        </g>
      </svg>

      {activeCell && activeCellCoord && (
        <div
          className="mds-heatmap__tooltip"
          style={{
            left: Math.max(10, Math.min(plot.toCanvasX((scales.scaleX ? (scales.scaleX(colLabels[activeCellCoord.cIdx]) ?? 0) : 0)) + cellWidth / 2 + 10, width - 210)),
            top: Math.max(10, Math.min(plot.toCanvasY((scales.scaleY ? (scales.scaleY(rowLabels[activeCellCoord.rIdx]) ?? 0) : 0)) - 15, height - 90))
          }}
          role="tooltip"
        >
          <div className="mds-heatmap__tooltip-header">
            <strong>{rowLabels[activeCellCoord.rIdx]} × {colLabels[activeCellCoord.cIdx]}</strong>
          </div>
          <div className="mds-heatmap__tooltip-body">
            <div className="mds-heatmap__tooltip-row">
              <span>{valueLabel}:</span>
              <strong>
                {activeCell.value != null ? formatVizValue(activeCell.value, unit, locale) : missingCellLabel}
              </strong>
            </div>
            {variant === 'correlation' && activeCell.value != null && (
              <div className="mds-heatmap__tooltip-row mds-heatmap__tooltip-row--sub">
                <span>Correlation:</span>
                <em>{activeCell.value > 0.7 ? 'Strong Positive' : activeCell.value < -0.7 ? 'Strong Negative' : 'Weak / Neutral'}</em>
              </div>
            )}
          </div>
        </div>
      )}

      <div className="mds-heatmap__sr-only" aria-live="polite">
        {activeCell && activeCellCoord
          ? `Selected matrix cell ${rowLabels[activeCellCoord.rIdx]}, ${colLabels[activeCellCoord.cIdx]}: ${activeCell.value != null ? `${activeCell.value} ${unit}` : missingCellLabel}.`
          : ''}
      </div>

      {/* Accessible Tabular Matrix Mirror */}
      {showDataTable && data && data.length > 0 && (
        <details
          className="ds-chart-table-details"
          style={{
            marginTop: 'var(--space-3)',
            borderTop: 'var(--border-hairline-subtle)',
            paddingTop: 'var(--space-2)',
            fontSize: 'var(--text-xs)',
            color: 'var(--text-secondary)'
          }}
        >
          <summary
            className="ds-chart-table-summary"
            style={{
              cursor: 'pointer',
              padding: 'var(--space-1) var(--space-2)',
              fontWeight: 500,
              userSelect: 'none'
            }}
          >
            View Accessible Data Matrix
          </summary>
          <div role="region" aria-label="Heatmap data matrix" tabIndex={0} style={{ overflowX: 'auto', marginTop: 8 }}>
            <table
              className="ds-chart-table"
              style={{
                width: '100%',
                borderCollapse: 'collapse',
                textAlign: 'left',
                fontSize: 'var(--text-xs)'
              }}
            >
              <caption style={{ position: 'absolute', width: 1, height: 1, padding: 0, margin: -1, overflow: 'hidden', clip: 'rect(0, 0, 0, 0)', border: 0 }}>
                {title ? `${title} Data Matrix` : 'Heatmap Data Matrix'}
              </caption>
              <thead>
                <tr style={{ borderBottom: 'var(--border-width-emphasis) solid var(--border-default)' }}>
                  <th scope="col" style={{ padding: 'calc(var(--space-1) + var(--space-half)) var(--space-2)', fontWeight: 600, color: 'var(--text-primary)' }}>
                    {rowLabel || 'Row / Col'}
                  </th>
                  {colLabels.map((c) => (
                    <th key={c} scope="col" style={{ padding: 'calc(var(--space-1) + var(--space-half)) var(--space-2)', fontWeight: 600, color: 'var(--text-primary)' }}>
                      {c}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {rowLabels.map((r, rIdx) => (
                  <tr key={r} style={{ borderBottom: 'var(--border-hairline-subtle)' }}>
                    <th scope="row" style={{ padding: 'calc(var(--space-1) + var(--space-half)) var(--space-2)', fontWeight: 500, color: 'var(--text-primary)' }}>
                      {r}
                    </th>
                    {colLabels.map((c, cIdx) => {
                      const cell = gridMatrix[rIdx]?.[cIdx];
                      const val = cell?.value;
                      return (
                        <td key={c} style={{ padding: 'calc(var(--space-1) + var(--space-half)) var(--space-2)', fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)' }}>
                          {val != null ? formatVizValue(val, unit, locale) : missingCellLabel}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </details>
      )}
    </div>
  );
};
