// packages/angular/src/components/layout/box.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DsSpacingScale = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 8 | 10 | 12;

@Component({
  selector: 'ds-box',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [ngClass]="rootClasses">
      <ng-content></ng-content>
    </div>
  `,
  styleUrls: ['./layout.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsBoxComponent {
  @Input() p?: DsSpacingScale;
  @Input() isCard: boolean = false;

  get rootClasses(): string {
    return [
      'ds-box',
      this.p !== undefined ? `ds-p-${this.p}` : '',
      this.isCard ? 'ds-surface-card' : '',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/components/Layout/Box.tsx
import React, { forwardRef } from 'react';
import './Layout.css';

export type SpacingScale = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 8 | 10 | 12;

export interface BoxProps extends React.HTMLAttributes<HTMLElement> {
  as?: React.ElementType;
  p?: SpacingScale;
  isCard?: boolean;
}

export const Box = forwardRef<HTMLElement, BoxProps>(
  ({ children, as = 'div', p, isCard = false, className = '', ...props }, ref) => {
    const Component = as;

    const classNames = [
      'ds-box',
      p !== undefined ? `ds-p-${p}` : '',
      isCard ? 'ds-surface-card' : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <Component ref={ref} className={classNames} {...props}>
        {children}
      </Component>
    );
  }
);

Box.displayName = 'Box';
