// packages/angular/src/components/layout/divider.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DsSpacingScale } from './box.component.js';

export type DsDividerOrientation = 'horizontal' | 'vertical';
export type DsDividerVariant = 'subtle' | 'strong' | 'dashed';

@Component({
  selector: 'ds-divider',
  standalone: true,
  imports: [CommonModule],
  template: `
    <ng-container *ngIf="hasLabel; else defaultDivider">
      <div
        role="separator"
        [attr.aria-orientation]="orientation"
        [ngClass]="rootClasses"
      >
        <span class="ds-divider__label">{{ label }}</span>
      </div>
    </ng-container>

    <ng-template #defaultDivider>
      <hr
        *ngIf="orientation === 'horizontal'"
        role="separator"
        [attr.aria-orientation]="orientation"
        [ngClass]="rootClasses"
      />
      <div
        *ngIf="orientation === 'vertical'"
        role="separator"
        [attr.aria-orientation]="orientation"
        [ngClass]="rootClasses"
      ></div>
    </ng-template>
  `,
  styleUrls: ['./layout.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDividerComponent {
  @Input() orientation: DsDividerOrientation = 'horizontal';
  @Input() variant: DsDividerVariant = 'subtle';
  @Input() spacing?: DsSpacingScale;
  @Input() label?: string;
  @Input() labelPosition: 'start' | 'center' | 'end' = 'center';

  get hasLabel(): boolean {
    return Boolean(this.label && this.orientation === 'horizontal');
  }

  get rootClasses(): string {
    return [
      'ds-divider',
      `ds-divider--${this.orientation}`,
      `ds-divider--${this.variant}`,
      this.spacing !== undefined ? `ds-divider--spacing-${this.spacing}` : '',
      this.hasLabel
        ? `ds-divider--with-label ds-divider--label-${this.labelPosition}`
        : '',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/components/Layout/Divider.tsx
import React, { forwardRef } from 'react';
import { SpacingScale } from './Box.js';
import './Layout.css';

export type DividerOrientation = 'horizontal' | 'vertical';
export type DividerVariant = 'subtle' | 'strong' | 'dashed';

export interface DividerProps extends React.HTMLAttributes<HTMLElement> {
  as?: React.ElementType;
  orientation?: DividerOrientation;
  variant?: DividerVariant;
  spacing?: SpacingScale;
  label?: React.ReactNode;
  labelPosition?: 'start' | 'center' | 'end';
}

export const Divider = forwardRef<HTMLElement, DividerProps>(
  (
    {
      as,
      orientation = 'horizontal',
      variant = 'subtle',
      spacing,
      label,
      labelPosition = 'center',
      className = '',
      children,
      ...props
    },
    ref
  ) => {
    const hasContent = Boolean(label || children);
    const hasLabel = hasContent && orientation === 'horizontal';

    // If it has a label/children or is vertical, use 'div' or custom 'as'; otherwise default to 'hr'
    const Component = as || (hasLabel || orientation === 'vertical' ? 'div' : 'hr');

    const classNames = [
      'ds-divider',
      `ds-divider--${orientation}`,
      `ds-divider--${variant}`,
      spacing !== undefined ? `ds-divider--spacing-${spacing}` : '',
      hasLabel ? `ds-divider--with-label ds-divider--label-${labelPosition}` : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    if (Component === 'hr') {
      return (
        <hr
          ref={ref as React.Ref<HTMLHRElement>}
          aria-orientation={orientation}
          className={classNames}
          {...(props as React.HTMLAttributes<HTMLHRElement>)}
        />
      );
    }

    return (
      <Component
        ref={ref}
        role="separator"
        aria-orientation={orientation}
        className={classNames}
        {...props}
      >
        {hasLabel && <span className="ds-divider__label">{label || children}</span>}
      </Component>
    );
  }
);

Divider.displayName = 'Divider';
