// packages/angular/src/components/layout/image.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DsSurfaceRadius } from './surface.component.js';
import { DsAspectRatioPreset } from './aspect-ratio.component.js';

export type DsImageFit = 'cover' | 'contain' | 'fill' | 'scale-down' | 'none';

const presetRatioMap: Record<DsAspectRatioPreset, string> = {
  '16/9': '16 / 9',
  '4/3': '4 / 3',
  '1/1': '1 / 1',
  '21/9': '21 / 9',
  '3/2': '3 / 2',
};

@Component({
  selector: 'ds-image',
  standalone: true,
  imports: [CommonModule],
  template: `
    <img
      [src]="currentSrc"
      [alt]="alt"
      [loading]="loading"
      [decoding]="decoding"
      [ngClass]="rootClasses"
      [ngStyle]="customStyles"
      (error)="handleError($event)"
      (load)="onLoad.emit($event)"
    />
  `,
  styleUrls: ['./layout.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsImageComponent {
  @Input() src: string = '';
  @Input() alt: string = '';
  @Input() fit: DsImageFit = 'cover';
  @Input() position: string = 'center';
  @Input() radius: DsSurfaceRadius = 'none';
  @Input() aspectRatio?: number | DsAspectRatioPreset;
  @Input() fallbackSrc?: string;
  @Input() loading: 'lazy' | 'eager' = 'lazy';
  @Input() decoding: 'async' | 'sync' | 'auto' = 'async';

  @Output() onError = new EventEmitter<Event>();
  @Output() onLoad = new EventEmitter<Event>();

  hasError: boolean = false;
  currentSrc: string = '';

  ngOnInit() {
    this.currentSrc = this.src;
  }

  ngOnChanges() {
    if (!this.hasError) {
      this.currentSrc = this.src;
    }
  }

  handleError(event: Event) {
    if (!this.hasError && this.fallbackSrc) {
      this.hasError = true;
      this.currentSrc = this.fallbackSrc;
    }
    this.onError.emit(event);
  }

  get rootClasses(): string {
    return [
      'ds-image',
      `ds-image--fit-${this.fit}`,
      `ds-image--radius-${this.radius}`,
    ]
      .filter(Boolean)
      .join(' ');
  }

  get customStyles(): Record<string, string> {
    const styles: Record<string, string> = {
      objectPosition: this.position,
    };

    if (this.aspectRatio !== undefined) {
      styles['aspectRatio'] =
        typeof this.aspectRatio === 'string' && this.aspectRatio in presetRatioMap
          ? presetRatioMap[this.aspectRatio as DsAspectRatioPreset]
          : String(this.aspectRatio);
    }

    return styles;
  }
}

// packages/react/src/components/Layout/Image.tsx
import React, { forwardRef, useState } from 'react';
import { SurfaceRadius } from './Surface.js';
import { AspectRatioPreset } from './AspectRatio.js';
import './Layout.css';

export type ImageFit = 'cover' | 'contain' | 'fill' | 'scale-down' | 'none';

export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
  fit?: ImageFit;
  position?: string;
  radius?: SurfaceRadius;
  aspectRatio?: number | AspectRatioPreset;
  fallbackSrc?: string;
}

const presetRatioMap: Record<AspectRatioPreset, string> = {
  '16/9': '16 / 9',
  '4/3': '4 / 3',
  '1/1': '1 / 1',
  '21/9': '21 / 9',
  '3/2': '3 / 2',
};

export const Image = forwardRef<HTMLImageElement, ImageProps>(
  (
    {
      src,
      alt,
      fit = 'cover',
      position = 'center',
      radius = 'none',
      aspectRatio,
      fallbackSrc,
      loading = 'lazy',
      decoding = 'async',
      className = '',
      style,
      onError,
      ...props
    },
    ref
  ) => {
    const [currentSrc, setCurrentSrc] = useState(src);
    const [hasError, setHasError] = useState(false);

    const handleError = (e: React.SyntheticEvent<HTMLImageElement, Event>) => {
      if (!hasError && fallbackSrc) {
        setHasError(true);
        setCurrentSrc(fallbackSrc);
      }
      onError?.(e);
    };

    const computedRatio =
      aspectRatio !== undefined
        ? typeof aspectRatio === 'string' && aspectRatio in presetRatioMap
          ? presetRatioMap[aspectRatio as AspectRatioPreset]
          : String(aspectRatio)
        : undefined;

    const classNames = [
      'ds-image',
      `ds-image--fit-${fit}`,
      `ds-image--radius-${radius}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const computedStyle: React.CSSProperties = {
      ...style,
      objectPosition: position,
      ...(computedRatio ? { aspectRatio: computedRatio } : {}),
    };

    return (
      <img
        ref={ref}
        src={currentSrc}
        alt={alt}
        loading={loading}
        decoding={decoding}
        className={classNames}
        style={computedStyle}
        onError={handleError}
        {...props}
      />
    );
  }
);

Image.displayName = 'Image';
