// packages/angular/src/components/layout/surface.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DsSpacingScale } from './box.component.js';

export type DsSurfaceTone = 'default' | 'card' | 'sunken' | 'overlay' | 'inverse';
export type DsSurfaceElevation = 0 | 1 | 2 | 3 | 4 | 5;
export type DsSurfaceRadius = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
export type DsSurfaceBorder = 'none' | 'subtle' | 'strong';

@Component({
  selector: 'ds-surface',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [ngClass]="rootClasses">
      <ng-content></ng-content>
    </div>
  `,
  styleUrls: ['./layout.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsSurfaceComponent {
  @Input() tone: DsSurfaceTone = 'card';
  @Input() elevation: DsSurfaceElevation = 0;
  @Input() radius: DsSurfaceRadius = 'md';
  @Input() border: DsSurfaceBorder = 'subtle';
  @Input() p?: DsSpacingScale;

  get rootClasses(): string {
    return [
      'ds-surface',
      `ds-surface--tone-${this.tone}`,
      `ds-surface--elevation-${this.elevation}`,
      `ds-surface--radius-${this.radius}`,
      `ds-surface--border-${this.border}`,
      this.p !== undefined ? `ds-p-${this.p}` : '',
    ]
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/components/Layout/Surface.tsx
import React, { forwardRef } from 'react';
import { SpacingScale } from './Box.js';
import './Layout.css';

export type SurfaceTone = 'default' | 'card' | 'sunken' | 'overlay' | 'inverse';
export type SurfaceElevation = 0 | 1 | 2 | 3 | 4 | 5;
export type SurfaceRadius = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
export type SurfaceBorder = 'none' | 'subtle' | 'strong';

export interface SurfaceProps extends React.HTMLAttributes<HTMLElement> {
  as?: React.ElementType;
  tone?: SurfaceTone;
  elevation?: SurfaceElevation;
  radius?: SurfaceRadius;
  border?: SurfaceBorder;
  p?: SpacingScale;
}

export const Surface = forwardRef<HTMLElement, SurfaceProps>(
  (
    {
      as = 'div',
      tone = 'card',
      elevation = 0,
      radius = 'md',
      border = 'subtle',
      p,
      className = '',
      children,
      ...props
    },
    ref
  ) => {
    const Component = as;

    const classNames = [
      'ds-surface',
      `ds-surface--tone-${tone}`,
      `ds-surface--elevation-${elevation}`,
      `ds-surface--radius-${radius}`,
      `ds-surface--border-${border}`,
      p !== undefined ? `ds-p-${p}` : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <Component ref={ref} className={classNames} {...props}>
        {children}
      </Component>
    );
  }
);

Surface.displayName = 'Surface';
