// packages/react/src/components/Badge/StaleDataPill.tsx
import React, { forwardRef, useState, useEffect } from 'react';
import './Badge.css';

export interface StaleDataPillProps extends React.HTMLAttributes<HTMLSpanElement> {
  /** Timestamp of last calculation/sync from engine */
  lastSyncTime?: Date | number;
  /** Explicit minutes since last sync (overrides auto-timer) */
  ageMinutes?: number;
  /** Minutes before status turns to warning amber (default: 5) */
  staleThresholdMinutes?: number;
  /** Minutes before status turns to error red (default: 15) */
  criticalThresholdMinutes?: number;
  /** Callback fired when user triggers calculation refresh */
  onRefresh?: () => void;
  /** Whether calculation/sync is actively executing */
  isRefreshing?: boolean;
}

/**
 * StaleDataPill (§01–§14)
 * Ambient telemetry badge for manufacturing ERP control rooms.
 * Warns planners when displayed MRP or batch calculations are stale,
 * preventing allocation decisions on invalid phantom stock.
 */
export const StaleDataPill = forwardRef<HTMLSpanElement, StaleDataPillProps>(
  (
    {
      lastSyncTime,
      ageMinutes,
      staleThresholdMinutes = 5,
      criticalThresholdMinutes = 15,
      onRefresh,
      isRefreshing = false,
      className = '',
      ...props
    },
    ref
  ) => {
    const [computedAge, setComputedAge] = useState<number>(() => {
      if (ageMinutes !== undefined) return ageMinutes;
      if (!lastSyncTime) return 0;
      const ms = Date.now() - new Date(lastSyncTime).getTime();
      return Math.max(0, Math.floor(ms / 60000));
    });

    useEffect(() => {
      if (ageMinutes !== undefined || !lastSyncTime) return;

      const update = () => {
        const ms = Date.now() - new Date(lastSyncTime).getTime();
        setComputedAge(Math.max(0, Math.floor(ms / 60000)));
      };

      const initialUpdate = setTimeout(update, 0);
      const timer = setInterval(update, 30000); // Check every 30s
      return () => {
        clearTimeout(initialUpdate);
        clearInterval(timer);
      };
    }, [lastSyncTime, ageMinutes]);

    const displayedAge = ageMinutes ?? computedAge;
    const isCritical = displayedAge >= criticalThresholdMinutes;
    const isStale = !isCritical && displayedAge >= staleThresholdMinutes;
    const _isFresh = !isCritical && !isStale;

    const modifierClass = isCritical
      ? 'ds-stale-pill--critical'
      : isStale
      ? 'ds-stale-pill--stale'
      : 'ds-stale-pill--fresh';

    const statusText = isRefreshing
      ? 'Recalculating...'
      : isCritical
      ? `Stale calculation (${displayedAge}m)`
      : isStale
      ? `Data ${displayedAge}m stale`
      : displayedAge === 0
      ? 'Synced just now'
      : `Synced ${displayedAge}m ago`;

    return (
      <span
        ref={ref}
        className={`ds-stale-pill ${modifierClass} ${className}`}
        role="status"
        aria-live="polite"
        {...props}
      >
        <span aria-hidden="true">
          {isRefreshing ? '⏳' : isCritical ? '⚠️' : isStale ? '⏱️' : '✓'}
        </span>
        <span>{statusText}</span>
        {onRefresh && !isRefreshing && (
          <button
            type="button"
            className="ds-stale-pill__refresh"
            onClick={onRefresh}
            aria-label="Refresh MRP calculation"
            title="Refresh calculation"
          >
            🔄
          </button>
        )}
      </span>
    );
  }
);

StaleDataPill.displayName = 'StaleDataPill';

// packages/angular/src/components/badge/stale-data-pill.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  OnDestroy,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ds-stale-data-pill',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span
      class="ds-stale-pill"
      [class.ds-stale-pill--critical]="isCritical"
      [class.ds-stale-pill--stale]="isStale"
      [class.ds-stale-pill--fresh]="isFresh"
      [class]="customClass"
      role="status"
      aria-live="polite"
    >
      <span aria-hidden="true">
        {{ isRefreshing ? '⏳' : isCritical ? '⚠️' : isStale ? '⏱️' : '✓' }}
      </span>
      <span>{{ statusText }}</span>
      <button
        *ngIf="showRefreshButton && !isRefreshing"
        type="button"
        class="ds-stale-pill__refresh"
        (click)="triggerRefresh()"
        aria-label="Refresh MRP calculation"
        title="Refresh calculation"
      >
        🔄
      </button>
    </span>
  `,
  styleUrls: ['./badge.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsStaleDataPillComponent implements OnInit, OnDestroy {
  @Input() lastSyncTime?: Date | number;
  @Input() ageMinutes?: number;
  @Input() staleThresholdMinutes = 5;
  @Input() criticalThresholdMinutes = 15;
  @Input() isRefreshing = false;
  @Input() showRefreshButton = true;
  @Input() customClass = '';

  @Output() refresh = new EventEmitter<void>();

  computedAge = 0;
  private timer?: ReturnType<typeof setInterval>;

  ngOnInit(): void {
    this.updateAge();
    this.timer = setInterval(() => this.updateAge(), 30000);
  }

  ngOnDestroy(): void {
    if (this.timer) {
      clearInterval(this.timer);
    }
  }

  updateAge(): void {
    if (this.ageMinutes !== undefined) {
      this.computedAge = this.ageMinutes;
      return;
    }
    if (!this.lastSyncTime) {
      this.computedAge = 0;
      return;
    }
    const ms = Date.now() - new Date(this.lastSyncTime).getTime();
    this.computedAge = Math.max(0, Math.floor(ms / 60000));
  }

  get isCritical(): boolean {
    return this.computedAge >= this.criticalThresholdMinutes;
  }

  get isStale(): boolean {
    return !this.isCritical && this.computedAge >= this.staleThresholdMinutes;
  }

  get isFresh(): boolean {
    return !this.isCritical && !this.isStale;
  }

  get statusText(): string {
    if (this.isRefreshing) return 'Recalculating...';
    if (this.isCritical) return `Stale calculation (${this.computedAge}m)`;
    if (this.isStale) return `Data ${this.computedAge}m stale`;
    if (this.computedAge === 0) return 'Synced just now';
    return `Synced ${this.computedAge}m ago`;
  }

  triggerRefresh(): void {
    this.refresh.emit();
  }
}
