// packages/angular/src/components/skeleton/skeleton.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';

export type SkeletonVariant = 'text' | 'circular' | 'rectangular' | 'rounded';
export type SkeletonAnimation = 'pulse' | 'wave' | 'none';

@Component({
  selector: 'ds-skeleton',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      *ngIf="count > 1; else singleSkeleton"
      class="ds-skeleton-group"
      role="status"
      aria-busy="true"
      aria-live="polite"
    >
      <span
        *ngFor="let item of items; let isLast = last"
        class="ds-skeleton"
        [class.ds-skeleton--text]="variant === 'text'"
        [class.ds-skeleton--circular]="variant === 'circular'"
        [class.ds-skeleton--rectangular]="variant === 'rectangular'"
        [class.ds-skeleton--rounded]="variant === 'rounded'"
        [class.ds-skeleton--pulse]="animation === 'pulse'"
        [class.ds-skeleton--wave]="animation === 'wave'"
        [class]="customClass"
        [style.width]="isLast && variant === 'text' && !width ? '70%' : computedWidth"
        [style.height]="computedHeight"
      ></span>
      <span class="sr-only">Loading content...</span>
    </div>

    <ng-template #singleSkeleton>
      <span
        class="ds-skeleton"
        [class.ds-skeleton--text]="variant === 'text'"
        [class.ds-skeleton--circular]="variant === 'circular'"
        [class.ds-skeleton--rectangular]="variant === 'rectangular'"
        [class.ds-skeleton--rounded]="variant === 'rounded'"
        [class.ds-skeleton--pulse]="animation === 'pulse'"
        [class.ds-skeleton--wave]="animation === 'wave'"
        [class]="customClass"
        [style.width]="computedWidth"
        [style.height]="computedHeight"
        role="status"
        aria-busy="true"
        aria-live="polite"
      >
        <span class="sr-only">Loading content...</span>
      </span>
    </ng-template>
  `,
  styleUrls: ['./skeleton.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsSkeletonComponent {
  @Input() variant: SkeletonVariant = 'text';
  @Input() animation: SkeletonAnimation = 'wave';
  @Input() width?: string | number;
  @Input() height?: string | number;
  @Input() count = 1;
  @Input() customClass = '';

  get items(): number[] {
    return Array.from({ length: this.count });
  }

  get computedWidth(): string | null {
    if (this.width === undefined) return null;
    return typeof this.width === 'number' ? `${this.width}px` : this.width;
  }

  get computedHeight(): string | null {
    if (this.height === undefined) return null;
    return typeof this.height === 'number' ? `${this.height}px` : this.height;
  }
}

// packages/react/src/components/Skeleton/Skeleton.tsx
import React, { forwardRef } from 'react';
import './Skeleton.css';

export type SkeletonVariant = 'text' | 'circular' | 'rectangular' | 'rounded';
export type SkeletonAnimation = 'pulse' | 'wave' | 'none';

export interface SkeletonProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: SkeletonVariant;
  animation?: SkeletonAnimation;
  width?: string | number;
  height?: string | number;
  count?: number;
}

export const Skeleton = forwardRef<HTMLSpanElement, SkeletonProps>(
  (
    {
      variant = 'text',
      animation = 'wave',
      width,
      height,
      count = 1,
      className = '',
      style,
      ...props
    },
    ref
  ) => {
    const classNames = [
      'ds-skeleton',
      `ds-skeleton--${variant}`,
      animation !== 'none' ? `ds-skeleton--${animation}` : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const computedStyle: React.CSSProperties = {
      ...style,
      width: width !== undefined ? (typeof width === 'number' ? `${width}px` : width) : undefined,
      height: height !== undefined ? (typeof height === 'number' ? `${height}px` : height) : undefined,
    };

    if (count > 1) {
      return (
        <div className="ds-skeleton-group" role="status" aria-busy="true" aria-live="polite">
          {Array.from({ length: count }).map((_, index) => (
            <span
              key={index}
              className={classNames}
              style={{
                ...computedStyle,
                width: index === count - 1 && variant === 'text' && !width ? '70%' : computedStyle.width,
              }}
              {...props}
            />
          ))}
          <span className="sr-only" style={{ position: 'absolute', width: 1, height: 1, overflow: 'hidden', clip: 'rect(0,0,0,0)' }}>
            Loading content...
          </span>
        </div>
      );
    }

    return (
      <span
        ref={ref}
        className={classNames}
        style={computedStyle}
        role="status"
        aria-busy="true"
        aria-live="polite"
        {...props}
      >
        <span className="sr-only" style={{ position: 'absolute', width: 1, height: 1, overflow: 'hidden', clip: 'rect(0,0,0,0)' }}>
          Loading content...
        </span>
      </span>
    );
  }
);

Skeleton.displayName = 'Skeleton';
