// packages/angular/src/components/layout-templates/collection-workspace-layout.component.ts
import { forwardRef, Optional, SkipSelf } from '@angular/core';
import { DsHeadingLevelProviderComponent } from '../typography/heading.component.js';
import { DsHeadingComponent } from '../typography/heading.component.js';
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DsCollectionWorkspaceLayoutState =
  | 'idle'
  | 'loading'
  | 'empty'
  | 'no-matches'
  | 'error';

@Component({
  selector: 'ds-collection-workspace-layout',
  standalone: true,
  imports: [CommonModule, DsHeadingComponent],
  template: `
    <div class="ds-collection-workspace" [ngClass]="customClass">
      <header class="ds-collection-workspace__scope-header" aria-label="Collection scope">
        <ng-content select="[scopeHeader]"></ng-content>
      </header>

      <div class="ds-collection-workspace__toolbar" role="toolbar" aria-label="Collection toolbar">
        <ng-content select="[toolbar]"></ng-content>
      </div>

      <div
        *ngIf="selectedCount > 0"
        class="ds-collection-workspace__selection-bar"
        role="region"
        aria-label="Batch actions"
      >
        <ng-content select="[selectionBar]"></ng-content>
      </div>

      <main class="ds-collection-workspace__content" aria-label="Collection data">
        <!-- Loading State -->
        <div *ngIf="layoutState === 'loading'">
          <ng-content select="[loadingState]"></ng-content>
          <div *ngIf="!hasCustomLoading" style="padding: 32px;">
            <div style="height: 40px; background: #f1f5f9; border-radius: 4px; margin-bottom: 12px;"></div>
            <div style="height: 40px; background: #f8fafc; border-radius: 4px; margin-bottom: 8px;"></div>
            <div style="height: 40px; background: #f8fafc; border-radius: 4px; margin-bottom: 8px;"></div>
            <div style="height: 40px; background: #f8fafc; border-radius: 4px;"></div>
          </div>
        </div>

        <!-- Empty State -->
        <div *ngIf="layoutState === 'empty'">
          <ng-content select="[emptyState]"></ng-content>
          <div *ngIf="!hasCustomEmpty" style="padding: 64px 24px; text-align: center;">
            <ds-heading size="base">No items in this collection</ds-heading>
            <p style="font-size: 13px; color: #64748b;">Create a new item to get started.</p>
          </div>
        </div>

        <!-- No Matches State -->
        <div *ngIf="layoutState === 'no-matches'">
          <ng-content select="[noMatchesState]"></ng-content>
          <div *ngIf="!hasCustomNoMatches" style="padding: 64px 24px; text-align: center;">
            <ds-heading size="base">No matching records found</ds-heading>
            <p style="font-size: 13px; color: #64748b;">Try clearing filters or changing search keywords.</p>
          </div>
        </div>

        <!-- Error State -->
        <div *ngIf="layoutState === 'error'">
          <ng-content select="[errorState]"></ng-content>
          <div *ngIf="!hasCustomError" style="padding: 48px 24px; text-align: center; color: #dc2626;">
            <ds-heading size="base">Failed to load collection</ds-heading>
            <p style="font-size: 13px; color: #64748b;">The connection to the plant data server timed out.</p>
          </div>
        </div>

        <!-- Default Content -->
        <div *ngIf="layoutState === 'idle'">
          <ng-content></ng-content>
        </div>
      </main>

      <!-- Filter Drawer -->
      <aside
        *ngIf="isDrawerFilterOpen"
        style="position: fixed; top: 0; right: 0; bottom: 0; width: 360px; background: #ffffff; border-left: 1px solid #e2e8f0; box-shadow: -4px 0 16px rgba(0,0,0,0.1); z-index: 50; padding: 24px; overflow-y: auto;"
        aria-label="Filter panel"
      >
        <ng-content select="[filterDrawer]"></ng-content>
      </aside>

      <footer
        class="ds-collection-workspace__footer"
        [class.ds-collection-workspace__footer--sticky]="isStickyFooter"
        aria-label="Collection pagination and status"
      >
        <ng-content select="[footer]"></ng-content>
      </footer>
    </div>
  `,
  styleUrls: ['./layout-templates.component.css'],
  providers: [{ provide: DsHeadingLevelProviderComponent, useExisting: forwardRef(() => DsCollectionWorkspaceLayoutComponent) }],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsCollectionWorkspaceLayoutComponent extends DsHeadingLevelProviderComponent {
  constructor(@Optional() @SkipSelf() parent: DsHeadingLevelProviderComponent | null) { super(parent); }
  @Input() selectedCount = 0;
  @Input() isStickyFooter = true;
  @Input() layoutState: DsCollectionWorkspaceLayoutState = 'idle';
  @Input() isDrawerFilterOpen = false;
  @Input() hasCustomLoading = false;
  @Input() hasCustomEmpty = false;
  @Input() hasCustomNoMatches = false;
  @Input() hasCustomError = false;
  @Input() customClass = '';
}

// packages/react/src/components/LayoutTemplates/CollectionWorkspaceLayout.tsx
import { Heading, HeadingLevelProvider } from '../Typography/Heading.js';
import React, { forwardRef } from 'react';
import './LayoutTemplates.css';

export type CollectionWorkspaceLayoutState =
  | 'idle'
  | 'loading'
  | 'empty'
  | 'no-matches'
  | 'error';

export interface CollectionWorkspaceLayoutProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Number of items currently selected (triggers conditional non-displacing bulk action bar) */
  selectedCount?: number;
  /** Whether the pagination footer sticks to viewport bottom */
  isStickyFooter?: boolean;
  /** Structural state of the collection */
  layoutState?: CollectionWorkspaceLayoutState;
  /** Region 1: Scope header (page title, breadcrumbs, summary KPIs) */
  scopeHeader?: React.ReactNode;
  /** Region 2: Dedicated 3-tiered action/filter toolbar */
  toolbar?: React.ReactNode;
  /** Conditional bulk action bar rendered when selectedCount > 0 */
  selectionBar?: React.ReactNode;
  /** Slide-over filter drawer / panel */
  filterDrawer?: React.ReactNode;
  /** Whether the filter drawer is expanded */
  isDrawerFilterOpen?: boolean;
  /** Region 4: Bottom status & pagination footer */
  footer?: React.ReactNode;
  /** Custom empty state */
  emptyState?: React.ReactNode;
  /** Custom no-matches search state */
  noMatchesState?: React.ReactNode;
  /** Custom error state */
  errorState?: React.ReactNode;
}

/**
 * CollectionWorkspaceLayout (§01–§14)
 * Standardized full-screen workspace framing a single large collection.
 * Integrates 3-tiered control scoping (collection, refinement, batch action),
 * identity-preserved selection, and sticky status pagination.
 */
export const CollectionWorkspaceLayout = forwardRef<HTMLDivElement, CollectionWorkspaceLayoutProps>(
  (
    {
      children,
      scopeHeader,
      toolbar,
      selectionBar,
      filterDrawer,
      footer,
      emptyState,
      noMatchesState,
      errorState,
      selectedCount = 0,
      isStickyFooter = true,
      layoutState = 'idle',
      isDrawerFilterOpen = false,
      className = '',
      ...props
    },
    ref
  ) => {
    return (
      <HeadingLevelProvider>
      <div
        ref={ref}
        className={`ds-collection-workspace ${className}`}
        {...props}
      >
        {scopeHeader && (
          <header className="ds-collection-workspace__scope-header" aria-label="Collection scope">
            {scopeHeader}
          </header>
        )}

        {toolbar && (
          <section aria-label="Collection controls">
          <div className="ds-collection-workspace__toolbar" role="toolbar" aria-label="Collection toolbar">
            {toolbar}
          </div>
          </section>
        )}

        {selectedCount > 0 && selectionBar && (
          <div
            className="ds-collection-workspace__selection-bar"
            role="region"
            aria-label="Batch actions"
          >
            {selectionBar}
          </div>
        )}

        <main className="ds-collection-workspace__content" aria-label="Collection data">
          {layoutState === 'loading' && (
            <div style={{ padding: 'var(--space-8)' }}>
              <div style={{ height: 'var(--control-h-lg)', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-sm)', marginBottom: 'var(--space-3)' }} />
              <div style={{ height: 'var(--control-h-lg)', background: 'var(--background-page)', borderRadius: 'var(--radius-sm)', marginBottom: 'var(--space-2)' }} />
              <div style={{ height: 'var(--control-h-lg)', background: 'var(--background-page)', borderRadius: 'var(--radius-sm)', marginBottom: 'var(--space-2)' }} />
              <div style={{ height: 'var(--control-h-lg)', background: 'var(--background-page)', borderRadius: 'var(--radius-sm)' }} />
            </div>
          )}

          {layoutState === 'empty' && (
            emptyState || (
              <div style={{ padding: 'var(--space-16) var(--space-6)', textAlign: 'center' }}>
                <Heading size="base" style={{ fontSize: 'var(--text-lg)', fontWeight: 600, color: 'var(--text-primary)' }}>No items in this collection</Heading>
                <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)' }}>Create a new item to get started.</p>
              </div>
            )
          )}

          {layoutState === 'no-matches' && (
            noMatchesState || (
              <div style={{ padding: 'var(--space-16) var(--space-6)', textAlign: 'center' }}>
                <Heading size="base" style={{ fontSize: 'var(--text-lg)', fontWeight: 600, color: 'var(--text-primary)' }}>No matching records found</Heading>
                <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)' }}>Try clearing filters or changing search keywords.</p>
              </div>
            )
          )}

          {layoutState === 'error' && (
            errorState || (
              <div style={{ padding: 'var(--space-12) var(--space-6)', textAlign: 'center', color: 'var(--status-critical-text)' }}>
                <Heading size="base" style={{ fontSize: 'var(--text-lg)', fontWeight: 600 }}>Failed to load collection</Heading>
                <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)' }}>The connection to the plant data server timed out.</p>
              </div>
            )
          )}

          {layoutState === 'idle' && children}
        </main>

        {filterDrawer && isDrawerFilterOpen && (
          <aside
            style={{
              position: 'fixed',
              top: 0,
              right: 0,
              bottom: 0,
              width: 'var(--drawer-width-sm)',
              background: 'var(--surface-card)',
              borderLeft: 'var(--border-hairline-subtle)',
              boxShadow: 'var(--drawer-shadow)',
              zIndex: 50,
              padding: 'var(--space-6)',
              overflowY: 'auto',
            }}
            aria-label="Filter panel"
          >
            {filterDrawer}
          </aside>
        )}

        {footer && (
          <footer
            className={`ds-collection-workspace__footer ${
              isStickyFooter ? 'ds-collection-workspace__footer--sticky' : ''
            }`}
            aria-label="Collection pagination and status"
          >
            {footer}
          </footer>
        )}
      </div>
      </HeadingLevelProvider>
    );
  }
);

CollectionWorkspaceLayout.displayName = 'CollectionWorkspaceLayout';
