// packages/angular/src/components/layout-templates/dashboard-layout.component.ts
import { forwardRef, Optional, SkipSelf } from '@angular/core';
import { DsHeadingLevelProviderComponent } from '../typography/heading.component.js';
import { DsHeadingComponent } from '../typography/heading.component.js';
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DsDashboardGap = 'sm' | 'md' | 'lg';

@Component({
  selector: 'ds-dashboard-widget',
  standalone: true,
  imports: [CommonModule, DsHeadingComponent],
  template: `
    <div
      class="ds-dashboard-widget"
      [ngClass]="['ds-col-span-' + colSpan, customClass]"
    >
      <div *ngIf="title || hasActions" class="ds-dashboard-widget__header">
        <ds-heading *ngIf="title" size="base" customClass="ds-dashboard-widget__title">{{ title }}</ds-heading>
        <ng-content select="[title]"></ng-content>
        <div>
          <ng-content select="[actions]"></ng-content>
        </div>
      </div>

      <div class="ds-dashboard-widget__body">
        <div *ngIf="isLoading" style="display: flex; flex-direction: column; gap: 10px;">
          <div style="height: 20px; width: 40%; background: #e2e8f0; border-radius: 4px;"></div>
          <div style="height: 80px; background: #e2e8f0; border-radius: 4px;"></div>
        </div>

        <div
          *ngIf="!isLoading && isError"
          style="padding: 16px; color: #dc2626; font-size: 13px; background: #fef2f2; border-radius: 6px;"
        >
          ⚠️ {{ errorMessage }}
        </div>

        <ng-container *ngIf="!isLoading && !isError">
          <ng-content></ng-content>
        </ng-container>
      </div>
    </div>
  `,
  styleUrls: ['./layout-templates.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDashboardWidgetComponent {
  @Input() colSpan = 4;
  @Input() title?: string;
  @Input() hasActions = false;
  @Input() isLoading = false;
  @Input() isError = false;
  @Input() errorMessage = 'Failed to load telemetry';
  @Input() customClass = '';
}

@Component({
  selector: 'ds-dashboard-layout',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="ds-dashboard" [ngClass]="customClass">
      <header class="ds-dashboard__header" aria-label="Dashboard controls">
        <ng-content select="[header]"></ng-content>
      </header>

      <section class="ds-dashboard__kpis" aria-label="Key performance indicators">
        <ng-content select="[kpiRow]"></ng-content>
      </section>

      <main
        class="ds-dashboard__grid"
        [class.ds-dashboard__grid--compact]="compactMode"
        aria-label="Dashboard widgets"
      >
        <ng-content></ng-content>
      </main>
    </div>
  `,
  styleUrls: ['./layout-templates.component.css'],
  providers: [{ provide: DsHeadingLevelProviderComponent, useExisting: forwardRef(() => DsDashboardLayoutComponent) }],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDashboardLayoutComponent extends DsHeadingLevelProviderComponent {
  constructor(@Optional() @SkipSelf() parent: DsHeadingLevelProviderComponent | null) { super(parent); }
  @Input() gap: DsDashboardGap = 'md';
  @Input() compactMode = false;
  @Input() customClass = '';
}

// packages/react/src/components/LayoutTemplates/DashboardLayout.tsx
import { Heading, HeadingLevelProvider } from '../Typography/Heading.js';
import React, { forwardRef } from 'react';
import './LayoutTemplates.css';

export type DashboardGap = 'sm' | 'md' | 'lg';

export interface DashboardLayoutProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Grid gap rhythm between cards (default 'md') */
  gap?: DashboardGap;
  /** High-density mode for operational telemetry */
  compactMode?: boolean;
  /** Global dashboard header (shared filter controls scoping all widgets) */
  header?: React.ReactNode;
  /** Dedicated top row for high-level KPI summary cards */
  kpiRow?: React.ReactNode;
}

export interface DashboardWidgetProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'title'> {
  /** Column span within 12-column grid system (1 to 12) */
  colSpan?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  /** Widget title */
  title?: React.ReactNode;
  /** Header action controls local to this widget */
  actions?: React.ReactNode;
  /** Isolated loading state for this widget */
  isLoading?: boolean;
  /** Isolated error message for this widget */
  isError?: boolean;
  /** Error fallback message */
  errorMessage?: string;
}

/**
 * DashboardWidget
 * Card surface holding an independently meaningful module with local action scope.
 */
export const DashboardWidget = forwardRef<HTMLDivElement, DashboardWidgetProps>(
  (
    {
      children,
      title,
      actions,
      colSpan = 4,
      isLoading = false,
      isError = false,
      errorMessage = 'Failed to load telemetry',
      className = '',
      ...props
    },
    ref
  ) => {
    return (
      <div
        ref={ref}
        className={`ds-dashboard-widget ds-col-span-${colSpan} ${className}`}
        {...props}
      >
        {(title || actions) && (
          <div className="ds-dashboard-widget__header">
            {typeof title === 'string' ? (
              <Heading className="ds-dashboard-widget__title" size="base">{title}</Heading>
            ) : (
              title
            )}
            {actions && <div>{actions}</div>}
          </div>
        )}

        <div className="ds-dashboard-widget__body">
          {isLoading ? (
            <div role="status" aria-busy="true" aria-label="Loading dashboard module" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
              <div style={{ height: 'var(--space-5)', width: '40%', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-sm)' }} />
              <div style={{ height: 'calc(var(--space-10) * 2)', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-sm)' }} />
            </div>
          ) : isError ? (
            <div role="alert" style={{ padding: 'var(--space-4)', color: 'var(--text-critical)', fontSize: 'var(--text-sm)', background: 'var(--status-critical-soft, var(--surface-sunken))', borderRadius: 'var(--radius-md)' }}>
              {errorMessage}
            </div>
          ) : (
            children
          )}
        </div>
      </div>
    );
  }
);

DashboardWidget.displayName = 'DashboardWidget';

/**
 * DashboardLayout (§01–§14)
 * Simultaneous overview of several independently meaningful modules.
 * Scopes global controls via header, enforces strict document reflow order,
 * and maintains per-module query failure isolation.
 */
export const DashboardLayout = forwardRef<HTMLDivElement, DashboardLayoutProps>(
  (
    {
      children,
      header,
      kpiRow,
      gap: _gap = 'md',
      compactMode = false,
      className = '',
      ...props
    },
    ref
  ) => {
    return (
      <HeadingLevelProvider>
      <div
        ref={ref}
        className={`ds-dashboard ${className}`}
        {...props}
      >
        {header && (
          <header className="ds-dashboard__header" aria-label="Dashboard controls">
            {header}
          </header>
        )}

        {kpiRow && (
          <section className="ds-dashboard__kpis" aria-label="Key performance indicators">
            {kpiRow}
          </section>
        )}

        <main
          className={`ds-dashboard__grid ${
            compactMode ? 'ds-dashboard__grid--compact' : ''
          }`}
          aria-label="Dashboard widgets"
        >
          {children}
        </main>
      </div>
      </HeadingLevelProvider>
    );
  }
);

DashboardLayout.displayName = 'DashboardLayout';
