// packages/angular/src/components/layout-templates/master-detail-layout.component.ts
import { forwardRef, Optional, SkipSelf } from '@angular/core';
import { DsHeadingLevelProviderComponent } from '../typography/heading.component.js';
import { DsHeadingComponent } from '../typography/heading.component.js';
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DsMasterDetailLayoutState =
  | 'initial-empty'
  | 'item-selected'
  | 'detail-loading'
  | 'detail-error';

export type DsMasterDetailMobileView = 'master' | 'detail';

@Component({
  selector: 'ds-master-detail-layout',
  standalone: true,
  imports: [CommonModule, DsHeadingComponent],
  template: `
    <div
      class="ds-master-detail"
      [style.gridTemplateColumns]="masterWidth + ' minmax(0, 1fr)'"
      [ngClass]="customClass"
    >
      <section
        class="ds-master-detail__master"
        [class.ds-master-detail__master--hidden]="mobileView !== 'master'"
        aria-label="Master list"
      >
        <ng-content select="[master]"></ng-content>
      </section>

      <section
        class="ds-master-detail__detail"
        [class.ds-master-detail__detail--hidden]="mobileView !== 'detail'"
        aria-label="Detail inspector"
      >
        <!-- Loading State -->
        <div *ngIf="getEffectiveState() === 'detail-loading'">
          <ng-content select="[loadingState]"></ng-content>
          <div *ngIf="!hasCustomLoading" style="padding: 32px;">
            <div style="height: 32px; width: 60%; background: #e2e8f0; border-radius: 4px; margin-bottom: 16px;"></div>
            <div style="height: 120px; background: #e2e8f0; border-radius: 4px; margin-bottom: 16px;"></div>
            <div style="height: 200px; background: #e2e8f0; border-radius: 4px;"></div>
          </div>
        </div>

        <!-- Error State -->
        <div *ngIf="getEffectiveState() === 'detail-error'">
          <ng-content select="[errorState]"></ng-content>
          <div *ngIf="!hasCustomError" style="padding: 32px; text-align: center;">
            <ds-heading size="lg" color="danger">Failed to load detail</ds-heading>
            <p style="color: #64748b; font-size: 14px;">Unable to retrieve member record from the plant server.</p>
          </div>
        </div>

        <!-- Empty State -->
        <div *ngIf="getEffectiveState() === 'initial-empty'">
          <ng-content select="[emptyState]"></ng-content>
          <div *ngIf="!hasCustomEmpty" class="ds-master-detail__empty">
            <div
              style="width: 48px; height: 48px; border-radius: 50%; background: #e2e8f0; margin: 0 auto 16px; display: flex; align-items: center; justify-content: center; color: #64748b; font-size: 20px;"
            >
              📋
            </div>
            <ds-heading size="base">
              {{ emptyTitle }}
            </ds-heading>
            <p style="font-size: 13px; color: #64748b; margin: 0; line-height: 1.5;">
              {{ emptyDescription }}
            </p>
          </div>
        </div>

        <!-- Selected Detail View -->
        <div *ngIf="getEffectiveState() === 'item-selected'">
          <ng-content select="[detail]"></ng-content>
        </div>
      </section>
    </div>
  `,
  styleUrls: ['./layout-templates.component.css'],
  providers: [{ provide: DsHeadingLevelProviderComponent, useExisting: forwardRef(() => DsMasterDetailLayoutComponent) }],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsMasterDetailLayoutComponent extends DsHeadingLevelProviderComponent {
  constructor(@Optional() @SkipSelf() parent: DsHeadingLevelProviderComponent | null) { super(parent); }
  @Input() masterWidth = '380px';
  @Input() selectedId: string | number | null = null;
  @Input() layoutState?: DsMasterDetailLayoutState;
  @Input() mobileView: DsMasterDetailMobileView = 'master';
  @Input() emptyTitle = 'No item selected';
  @Input() emptyDescription = 'Select an item from the master list to inspect and edit details.';
  @Input() hasCustomLoading = false;
  @Input() hasCustomError = false;
  @Input() hasCustomEmpty = false;
  @Input() customClass = '';

  @Output() mobileViewChange = new EventEmitter<DsMasterDetailMobileView>();
  @Output() clearSelection = new EventEmitter<void>();

  getEffectiveState(): DsMasterDetailLayoutState {
    if (this.layoutState) return this.layoutState;
    return this.selectedId ? 'item-selected' : 'initial-empty';
  }
}

// packages/react/src/components/LayoutTemplates/MasterDetailLayout.tsx
import { Heading, HeadingLevelProvider } from '../Typography/Heading.js';
import React, { forwardRef } from 'react';
import './LayoutTemplates.css';

export type MasterDetailLayoutState =
  | 'initial-empty'
  | 'item-selected'
  | 'detail-loading'
  | 'detail-error';

export type MasterDetailMobileView = 'master' | 'detail';

export interface MasterDetailLayoutProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Width allocated to the master list track */
  masterWidth?: string;
  /** Current selected member identifier */
  selectedId?: string | number | null;
  /** Structural state of the layout */
  layoutState?: MasterDetailLayoutState;
  /** Mobile view toggle in responsive sequential form */
  mobileView?: MasterDetailMobileView;
  /** Callback fired when mobile view switches */
  onMobileViewChange?: (view: MasterDetailMobileView) => void;
  /** Callback fired to clear selection */
  onClearSelection?: () => void;
  /** Master collection / queue region */
  master?: React.ReactNode;
  /** Member detail inspection/editing region */
  detail?: React.ReactNode;
  /** Custom empty state when nothing is selected */
  emptyState?: React.ReactNode;
  /** Custom loading skeleton state */
  loadingState?: React.ReactNode;
  /** Custom error state */
  errorState?: React.ReactNode;
  /** Default empty state title */
  emptyTitle?: string;
  /** Default empty state description */
  emptyDescription?: string;
}

/**
 * MasterDetailLayout (§01–§14)
 * A collection held beside the one member currently being worked.
 * Strictly maintains one-directional selection dependency, independent position/scroll ownership,
 * and 4 structural layout states (empty, selected, loading, error).
 */
export const MasterDetailLayout = forwardRef<HTMLDivElement, MasterDetailLayoutProps>(
  (
    {
      master,
      detail,
      emptyState,
      loadingState,
      errorState,
      masterWidth = 'var(--layout-master-detail-track-w)',
      selectedId = null,
      layoutState: customLayoutState,
      mobileView = selectedId ? 'detail' : 'master',
      onMobileViewChange: _onMobileViewChange,
      onClearSelection: _onClearSelection,
      emptyTitle = 'No item selected',
      emptyDescription = 'Select an item from the master list to inspect and edit details.',
      className = '',
      ...props
    },
    ref
  ) => {
    // Determine effective layout state
    const layoutState: MasterDetailLayoutState =
      customLayoutState || (selectedId ? 'item-selected' : 'initial-empty');

    const gridTemplateColumns = `${masterWidth} minmax(0, 1fr)`;

    return (
      <HeadingLevelProvider>
      <div
        ref={ref}
        className={`ds-master-detail ${className}`}
        style={{ gridTemplateColumns }}
        {...props}
      >
        <section
          className={`ds-master-detail__master ${
            mobileView !== 'master' ? 'ds-master-detail__master--hidden' : ''
          }`}
          aria-label="Master list"
        >
          {master}
        </section>

        <section
          className={`ds-master-detail__detail ${
            mobileView !== 'detail' ? 'ds-master-detail__detail--hidden' : ''
          }`}
          aria-label="Detail inspector"
        >
          {layoutState === 'detail-loading' && (
            loadingState || (
              <div style={{ padding: 'var(--space-8)' }}>
                <div style={{ height: 'var(--space-8)', width: '60%', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-sm)', marginBottom: 'var(--space-4)' }} />
                <div style={{ height: 'var(--layout-master-detail-skeleton-short-h)', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-sm)', marginBottom: 'var(--space-4)' }} />
                <div style={{ height: 'var(--layout-master-detail-skeleton-tall-h)', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-sm)' }} />
              </div>
            )
          )}

          {layoutState === 'detail-error' && (
            errorState || (
              <div style={{ padding: 'var(--space-8)', textAlign: 'center' }}>
                <Heading size="lg" style={{ color: 'var(--status-critical-text)', fontSize: 'var(--text-xl)', fontWeight: 'var(--weight-semibold)' }}>Failed to load detail</Heading>
                <p style={{ color: 'var(--text-secondary)', fontSize: 'var(--text-base)' }}>Unable to retrieve member record from the plant server.</p>
              </div>
            )
          )}

          {layoutState === 'initial-empty' && (
            emptyState || (
              <div className="ds-master-detail__empty">
                <div
                  style={{
                    width: 'var(--space-12)',
                    height: 'var(--space-12)',
                    borderRadius: '50%',
                    background: 'var(--surface-sunken)',
                    margin: '0 auto var(--space-4)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: 'var(--text-secondary)',
                    fontSize: 'var(--text-xl)',
                  }}
                >
                  📋
                </div>
                <Heading size="base" style={{ fontSize: 'var(--text-lg)', fontWeight: 'var(--weight-semibold)', color: 'var(--text-primary)', margin: '0 0 calc(var(--space-1) + var(--space-half))' }}>
                  {emptyTitle}
                </Heading>
                <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)', margin: 0, lineHeight: 'var(--leading-normal)' }}>
                  {emptyDescription}
                </p>
              </div>
            )
          )}

          {layoutState === 'item-selected' && detail}
        </section>
      </div>
      </HeadingLevelProvider>
    );
  }
);

MasterDetailLayout.displayName = 'MasterDetailLayout';
