// packages/react/src/components/Tabs/SegmentedControl.tsx
import React, { useRef, useCallback } from 'react';
import './SegmentedControl.css';

export interface SegmentedControlOption<T extends string = string> {
  value: T;
  label: React.ReactNode;
  icon?: React.ReactNode;
  badge?: React.ReactNode;
  disabled?: boolean;
}

export interface SegmentedControlProps<T extends string = string> {
  /** Array of selectable segments */
  options: SegmentedControlOption<T>[];
  /** Currently selected value */
  value: T;
  /** Callback fired when selection changes */
  onChange: (value: T) => void;
  /** Size variant: 'sm' (compact 32px for dense ERP) or 'md' (standard 36px) */
  size?: 'sm' | 'md';
  /** Accessible label for the segmented control group */
  'aria-label': string;
  /** Optional custom CSS class name */
  className?: string;
  /** Whether the entire control group is disabled */
  disabled?: boolean;
  /** Whether to expand to full width of container */
  fullWidth?: boolean;
}

export const SegmentedControl = <T extends string = string>({
  options,
  value,
  onChange,
  size = 'sm',
  'aria-label': ariaLabel,
  className = '',
  disabled = false,
  fullWidth = false,
}: SegmentedControlProps<T>): React.ReactElement => {
  const containerRef = useRef<HTMLDivElement>(null);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLButtonElement>, currentIndex: number) => {
      const enabledOptions = options.map((opt, i) => ({ ...opt, index: i })).filter((opt) => !opt.disabled && !disabled);
      if (enabledOptions.length === 0) return;

      const currentEnabledIndex = enabledOptions.findIndex((opt) => opt.index === currentIndex);
      let targetIndex = -1;

      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        targetIndex = (currentEnabledIndex + 1) % enabledOptions.length;
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        targetIndex = (currentEnabledIndex - 1 + enabledOptions.length) % enabledOptions.length;
      } else if (e.key === 'Home') {
        e.preventDefault();
        targetIndex = 0;
      } else if (e.key === 'End') {
        e.preventDefault();
        targetIndex = enabledOptions.length - 1;
      }

      if (targetIndex !== -1) {
        const nextOption = enabledOptions[targetIndex];
        onChange(nextOption.value);
        const buttons = containerRef.current?.querySelectorAll<HTMLButtonElement>('[role="radio"]');
        buttons?.[nextOption.index]?.focus();
      }
    },
    [options, disabled, onChange]
  );

  return (
    <div
      ref={containerRef}
      role="radiogroup"
      aria-label={ariaLabel}
      aria-disabled={disabled}
      className={`ds-segmented-control ds-segmented-control--${size} ${fullWidth ? 'ds-segmented-control--full-width' : ''} ${
        disabled ? 'ds-segmented-control--disabled' : ''
      } ${className}`}
    >
      {options.map((option, index) => {
        const isSelected = option.value === value;
        const isOptionDisabled = disabled || option.disabled;

        return (
          <button
            key={option.value}
            type="button"
            role="radio"
            aria-checked={isSelected}
            disabled={isOptionDisabled}
            tabIndex={isSelected ? 0 : -1}
            className={`ds-segmented-control__segment ${
              isSelected ? 'ds-segmented-control__segment--selected' : ''
            } ${isOptionDisabled ? 'ds-segmented-control__segment--disabled' : ''}`}
            onClick={() => {
              if (!isOptionDisabled && !isSelected) {
                onChange(option.value);
              }
            }}
            onKeyDown={(e) => handleKeyDown(e, index)}
          >
            {option.icon && (
              <span className="ds-segmented-control__icon" aria-hidden="true">
                {option.icon}
              </span>
            )}
            <span className="ds-segmented-control__label">{option.label}</span>
            {option.badge && (
              <span className="ds-segmented-control__badge" aria-hidden="true">
                {option.badge}
              </span>
            )}
          </button>
        );
      })}
    </div>
  );
};

// packages/angular/src/components/tabs/segmented-control.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface AngularSegmentOption<T extends string = string> {
  value: T;
  label: string;
  icon?: string;
  badge?: string | number;
  disabled?: boolean;
}

@Component({
  selector: 'ds-segmented-control',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="ds-segmented-control ds-segmented-control--{{ size }}"
      [class.ds-segmented-control--full-width]="fullWidth"
      [class.ds-segmented-control--disabled]="disabled"
      [class]="customClass"
      role="radiogroup"
      [attr.aria-label]="ariaLabel"
      [attr.aria-disabled]="disabled"
    >
      <button
        *ngFor="let opt of options; let i = index"
        type="button"
        role="radio"
        [attr.aria-checked]="value === opt.value"
        [disabled]="disabled || opt.disabled"
        [tabIndex]="value === opt.value ? 0 : -1"
        class="ds-segmented-control__segment"
        [class.ds-segmented-control__segment--selected]="value === opt.value"
        [class.ds-segmented-control__segment--disabled]="disabled || opt.disabled"
        (click)="selectOption(opt)"
        (keydown)="onKeydown($event, i)"
      >
        <span *ngIf="opt.icon" class="ds-segmented-control__icon" aria-hidden="true">{{ opt.icon }}</span>
        <span class="ds-segmented-control__label">{{ opt.label }}</span>
        <span *ngIf="opt.badge !== undefined" class="ds-segmented-control__badge" aria-hidden="true">{{ opt.badge }}</span>
      </button>
    </div>
  `,
  styleUrls: ['./segmented-control.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsSegmentedControlComponent<T extends string = string> {
  @Input() options: AngularSegmentOption<T>[] = [];
  @Input() value!: T;
  @Input() size: 'sm' | 'md' = 'sm';
  @Input() ariaLabel: string = 'View Switcher';
  @Input() disabled: boolean = false;
  @Input() fullWidth: boolean = false;
  @Input() customClass: string = '';

  @Output() valueChange = new EventEmitter<T>();

  selectOption(opt: AngularSegmentOption<T>): void {
    if (this.disabled || opt.disabled || this.value === opt.value) return;
    this.valueChange.emit(opt.value);
  }

  onKeydown(e: KeyboardEvent, currentIndex: number): void {
    const enabled = this.options.map((o, idx) => ({ ...o, idx })).filter((o) => !o.disabled && !this.disabled);
    if (enabled.length === 0) return;

    const currentEnabledIdx = enabled.findIndex((o) => o.idx === currentIndex);
    let targetIdx = -1;

    if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
      e.preventDefault();
      targetIdx = (currentEnabledIdx + 1) % enabled.length;
    } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
      e.preventDefault();
      targetIdx = (currentEnabledIdx - 1 + enabled.length) % enabled.length;
    } else if (e.key === 'Home') {
      e.preventDefault();
      targetIdx = 0;
    } else if (e.key === 'End') {
      e.preventDefault();
      targetIdx = enabled.length - 1;
    }

    if (targetIdx !== -1) {
      const next = enabled[targetIdx];
      this.valueChange.emit(next.value);
    }
  }
}
