// packages/angular/src/components/tabs/tabs.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';

export type TabsVariant = 'line' | 'pill';
export type TabsSize = 'sm' | 'md' | 'lg';

export interface TabItem {
  id: string;
  label: string;
  disabled?: boolean;
}

let nextTabsId = 0;

@Component({
  selector: 'ds-tabs',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="ds-tabs"
      [class.ds-tabs--variant-line]="variant === 'line'"
      [class.ds-tabs--variant-pill]="variant === 'pill'"
      [class.ds-tabs--size-sm]="size === 'sm'"
      [class.ds-tabs--size-md]="size === 'md'"
      [class.ds-tabs--size-lg]="size === 'lg'"
      [class]="customClass"
    >
      <div role="tablist" class="ds-tab-list" [attr.aria-label]="ariaLabel" (keydown)="onKeyDown($event)">
        <button
          *ngFor="let tab of tabs"
          type="button"
          role="tab"
          [id]="baseId + '-tab-' + tab.id"
          [attr.aria-selected]="activeTab === tab.id"
          [attr.aria-controls]="baseId + '-panel-' + tab.id"
          [attr.aria-disabled]="tab.disabled"
          [disabled]="tab.disabled"
          [tabIndex]="activeTab === tab.id ? 0 : -1"
          (click)="selectTab(tab.id)"
          class="ds-tab-trigger"
        >
          {{ tab.label }}
        </button>
      </div>

      <div
        role="tabpanel"
        [id]="baseId + '-panel-' + activeTab"
        [attr.aria-labelledby]="baseId + '-tab-' + activeTab"
        tabindex="0"
        class="ds-tab-panel"
      >
        <ng-content></ng-content>
      </div>
    </div>
  `,
  styleUrls: ['./tabs.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsTabsComponent {
  @Input() tabs: TabItem[] = [];
  @Input() activeTab = '';
  @Input() variant: TabsVariant = 'line';
  @Input() size: TabsSize = 'md';
  @Input() ariaLabel = 'Tab options';
  @Input() customClass = '';

  @Output() activeTabChange = new EventEmitter<string>();

  baseId = `ds-tabs-${++nextTabsId}`;

  selectTab(id: string): void {
    const tab = this.tabs.find((t) => t.id === id);
    if (tab && !tab.disabled && this.activeTab !== id) {
      this.activeTab = id;
      this.activeTabChange.emit(id);
    }
  }

  onKeyDown(event: KeyboardEvent): void {
    const enabledTabs = this.tabs.filter((t) => !t.disabled);
    if (enabledTabs.length === 0) return;
    const currentIndex = enabledTabs.findIndex((t) => t.id === this.activeTab);
    let nextIndex = currentIndex;

    if (event.key === 'ArrowRight') {
      event.preventDefault();
      nextIndex = (currentIndex + 1) % enabledTabs.length;
    } else if (event.key === 'ArrowLeft') {
      event.preventDefault();
      nextIndex = (currentIndex - 1 + enabledTabs.length) % enabledTabs.length;
    } else if (event.key === 'Home') {
      event.preventDefault();
      nextIndex = 0;
    } else if (event.key === 'End') {
      event.preventDefault();
      nextIndex = enabledTabs.length - 1;
    }

    if (nextIndex !== currentIndex && nextIndex >= 0) {
      this.selectTab(enabledTabs[nextIndex].id);
    }
  }
}

// packages/react/src/components/Tabs/Tabs.tsx
import React,{
createContext,
forwardRef,
useContext,
useId,
useRef,
useState
} from 'react';
import './Tabs.css';

export type TabsVariant = 'line' | 'pill';
export type TabsSize = 'sm' | 'md' | 'lg';

interface TabsContextValue {
  value: string;
  onChange: (value: string) => void;
  baseId: string;
  variant: TabsVariant;
  size: TabsSize;
}

const TabsContext = createContext<TabsContextValue | null>(null);

const useTabsContext = () => {
  const context = useContext(TabsContext);
  if (!context) {
    throw new Error('Tabs compound components must be used within a <Tabs>');
  }
  return context;
};

export interface TabsProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  variant?: TabsVariant;
  size?: TabsSize;
}

export const Tabs = forwardRef<HTMLDivElement, TabsProps>(
  (
    {
      value: controlledValue,
      defaultValue = '',
      onValueChange,
      variant = 'line',
      size = 'md',
      children,
      className = '',
      ...props
    },
    ref
  ) => {
    const isControlled = controlledValue !== undefined;
    const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);
    const currentValue = isControlled ? controlledValue : uncontrolledValue;
    const baseId = useId();

    const handleValueChange = (val: string) => {
      if (!isControlled) {
        setUncontrolledValue(val);
      }
      onValueChange?.(val);
    };

    const classNames = [
      'ds-tabs',
      `ds-tabs--variant-${variant}`,
      `ds-tabs--size-${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <TabsContext.Provider
        value={{
          value: currentValue,
          onChange: handleValueChange,
          baseId,
          variant,
          size,
        }}
      >
        <div ref={ref} className={classNames} {...props}>
          {children}
        </div>
      </TabsContext.Provider>
    );
  }
);
Tabs.displayName = 'Tabs';

export interface TabListProps extends React.HTMLAttributes<HTMLDivElement> {
  'aria-label'?: string;
}

export const TabList = forwardRef<HTMLDivElement, TabListProps>(
  ({ 'aria-label': ariaLabel = 'Tab options', children, className = '', ...props }, ref) => {
    const listRef = useRef<HTMLDivElement>(null);

    const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      const container = listRef.current;
      if (!container) return;

      const tabs = Array.from(
        container.querySelectorAll<HTMLButtonElement>('[role="tab"]:not([disabled])')
      );
      const currentIndex = tabs.findIndex((tab) => tab === document.activeElement);
      if (currentIndex === -1) return;

      let nextIndex = currentIndex;

      if (e.key === 'ArrowRight') {
        e.preventDefault();
        nextIndex = (currentIndex + 1) % tabs.length;
      } else if (e.key === 'ArrowLeft') {
        e.preventDefault();
        nextIndex = (currentIndex - 1 + tabs.length) % tabs.length;
      } else if (e.key === 'Home') {
        e.preventDefault();
        nextIndex = 0;
      } else if (e.key === 'End') {
        e.preventDefault();
        nextIndex = tabs.length - 1;
      }

      if (nextIndex !== currentIndex) {
        tabs[nextIndex]?.focus();
        tabs[nextIndex]?.click();
      }
    };

    return (
      <div
        ref={(node) => {
          (listRef as any).current = node;
          if (typeof ref === 'function') ref(node);
          else if (ref) (ref as any).current = node;
        }}
        role="tablist"
        tabIndex={0}
        aria-label={ariaLabel}
        onKeyDown={handleKeyDown}
        className={`ds-tab-list ${className}`}
        {...props}
      >
        {children}
      </div>
    );
  }
);
TabList.displayName = 'TabList';

export interface TabTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  value: string;
}

export const TabTrigger = forwardRef<HTMLButtonElement, TabTriggerProps>(
  ({ value, children, disabled = false, className = '', ...props }, ref) => {
    const { value: selectedValue, onChange, baseId } = useTabsContext();
    const isSelected = selectedValue === value;
    const tabId = `${baseId}-tab-${value}`;
    const panelId = `${baseId}-panel-${value}`;

    return (
      <button
        ref={ref}
        type="button"
        role="tab"
        id={tabId}
        aria-selected={isSelected}
        aria-controls={panelId}
        aria-disabled={disabled}
        disabled={disabled}
        tabIndex={isSelected ? 0 : -1}
        onClick={() => !disabled && onChange(value)}
        className={`ds-tab-trigger ${className}`}
        {...props}
      >
        {children}
      </button>
    );
  }
);
TabTrigger.displayName = 'TabTrigger';

export interface TabPanelProps extends React.HTMLAttributes<HTMLDivElement> {
  value: string;
}

export const TabPanel = forwardRef<HTMLDivElement, TabPanelProps>(
  ({ value, children, className = '', ...props }, ref) => {
    const { value: selectedValue, baseId } = useTabsContext();
    const isSelected = selectedValue === value;
    const tabId = `${baseId}-tab-${value}`;
    const panelId = `${baseId}-panel-${value}`;

    if (!isSelected) return null;

    return (
      <div
        ref={ref}
        role="tabpanel"
        id={panelId}
        aria-labelledby={tabId}
        className={`ds-tab-panel ${className}`}
        {...props}
      >
        {children}
      </div>
    );
  }
);
TabPanel.displayName = 'TabPanel';
