// packages/angular/src/components/badge/badge.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DsBadgeVariant = 'neutral' | 'brand' | 'success' | 'warning' | 'danger' | 'info';
export type DsBadgeStyle = 'subtle' | 'solid' | 'outline';
export type DsBadgeSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'ds-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span [ngClass]="rootClasses">
      <span *ngIf="hasDot" class="ds-badge__dot" aria-hidden="true"></span>
      <span class="ds-badge__icon-left" aria-hidden="true">
        <ng-content select="[slot=left-icon]"></ng-content>
      </span>
      <span class="ds-badge__content">
        <ng-content></ng-content>
      </span>
      <span class="ds-badge__icon-right" aria-hidden="true">
        <ng-content select="[slot=right-icon]"></ng-content>
      </span>
      <button
        *ngIf="isDismissible"
        type="button"
        class="ds-badge__dismiss"
        aria-label="Remove tag"
        (click)="onDismissClick($event)"
      >
        ✕
      </button>
    </span>
  `,
  styleUrls: ['./badge.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsBadgeComponent {
  @Input() variant: DsBadgeVariant = 'neutral';
  @Input() styleVariant: DsBadgeStyle = 'subtle';
  @Input() size: DsBadgeSize = 'md';
  @Input() hasDot: boolean = false;
  @Input() isDismissible: boolean = false;

  @Output() dismissed = new EventEmitter<MouseEvent>();

  get rootClasses(): string {
    return [
      'ds-badge',
      `ds-badge--${this.variant}`,
      `ds-badge--${this.styleVariant}`,
      `ds-badge--${this.size}`,
    ]
      .filter(Boolean)
      .join(' ');
  }

  onDismissClick(event: MouseEvent): void {
    event.stopPropagation();
    this.dismissed.emit(event);
  }
}

// packages/react/src/components/Badge/Badge.tsx
import React, { forwardRef } from 'react';
import './Badge.css';

export type BadgeVariant = 'neutral' | 'brand' | 'success' | 'warning' | 'danger' | 'info';
export type BadgeStyle = 'subtle' | 'solid' | 'outline';
export type BadgeSize = 'sm' | 'md' | 'lg';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant;
  styleVariant?: BadgeStyle;
  size?: BadgeSize;
  hasDot?: boolean;
  isDismissible?: boolean;
  onDismiss?: (e: React.MouseEvent<HTMLButtonElement>) => void;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  (
    {
      children,
      variant = 'neutral',
      styleVariant = 'subtle',
      size = 'md',
      hasDot = false,
      isDismissible = false,
      onDismiss,
      leftIcon,
      rightIcon,
      className = '',
      ...props
    },
    ref
  ) => {
    const classNames = [
      'ds-badge',
      `ds-badge--${variant}`,
      `ds-badge--${styleVariant}`,
      `ds-badge--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <span ref={ref} className={classNames} {...props}>
        {hasDot && <span className="ds-badge__dot" aria-hidden="true" />}
        {leftIcon && <span className="ds-badge__icon-left" aria-hidden="true">{leftIcon}</span>}
        <span className="ds-badge__content">{children}</span>
        {rightIcon && <span className="ds-badge__icon-right" aria-hidden="true">{rightIcon}</span>}
        {isDismissible && (
          <button
            type="button"
            className="ds-badge__dismiss"
            aria-label="Remove tag"
            onClick={(e) => {
              e.stopPropagation();
              onDismiss?.(e);
            }}
          >
            ✕
          </button>
        )}
      </span>
    );
  }
);

Badge.displayName = 'Badge';

export const Tag = Badge;
export const Pill = Badge;
