// packages/angular/src/components/badge/dual-uom-badge.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ds-dual-uom-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span
      class="ds-dual-uom-badge"
      [class]="customClass"
      [attr.title]="accessibleTitle"
      [attr.aria-label]="accessibleTitle"
    >
      <span class="ds-dual-uom-badge__primary">
        {{ formattedPrimary }} {{ primaryUom }}
      </span>
      <ng-container *ngIf="secondaryQty !== undefined && secondaryUom">
        <span class="ds-dual-uom-badge__separator" aria-hidden="true">|</span>
        <span class="ds-dual-uom-badge__secondary">
          ~{{ formattedSecondary }} {{ secondaryUom }}
        </span>
      </ng-container>
    </span>
  `,
  styleUrls: ['./badge.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDualUomBadgeComponent {
  @Input({ required: true }) primaryQty!: number | string;
  @Input({ required: true }) primaryUom!: string;
  @Input() secondaryQty?: number | string;
  @Input() secondaryUom?: string;
  @Input() conversionRatio?: string;
  @Input() customClass = '';

  get formattedPrimary(): string {
    return typeof this.primaryQty === 'number'
      ? this.primaryQty.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 2 })
      : String(this.primaryQty);
  }

  get formattedSecondary(): string {
    return typeof this.secondaryQty === 'number'
      ? this.secondaryQty.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 1 })
      : String(this.secondaryQty ?? '');
  }

  get accessibleTitle(): string {
    if (this.secondaryQty !== undefined && this.secondaryUom) {
      return `${this.formattedPrimary} ${this.primaryUom} (equivalent to ${this.formattedSecondary} ${this.secondaryUom}${
        this.conversionRatio ? ` · Rate: ${this.conversionRatio}` : ''
      })`;
    }
    return `${this.formattedPrimary} ${this.primaryUom}`;
  }
}

// packages/react/src/components/Badge/DualUomBadge.tsx
import React, { forwardRef } from 'react';
import './Badge.css';

export interface DualUomBadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  /** Primary inventory quantity */
  primaryQty: number | string;
  /** Primary inventory unit of measure (e.g. 'KG', 'L') */
  primaryUom: string;
  /** Operational / production converted quantity */
  secondaryQty?: number | string;
  /** Operational production unit of measure (e.g. 'Pk', 'Btl') */
  secondaryUom?: string;
  /** Conversion ratio label for tooltip/title (e.g. '1 KG = 20 Pk') */
  conversionRatio?: string;
}

/**
 * DualUomBadge (§01–§14)
 * Displays primary inventory storage unit and operational production unit side-by-side.
 * Uses machine monospace typography and tabular numbers to prevent jitter in high-density tables.
 */
export const DualUomBadge = forwardRef<HTMLSpanElement, DualUomBadgeProps>(
  (
    {
      primaryQty,
      primaryUom,
      secondaryQty,
      secondaryUom,
      conversionRatio,
      className = '',
      title,
      ...props
    },
    ref
  ) => {
    const formattedPrimary =
      typeof primaryQty === 'number'
        ? primaryQty.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 2 })
        : primaryQty;

    const formattedSecondary =
      typeof secondaryQty === 'number'
        ? secondaryQty.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 1 })
        : secondaryQty;

    const accessibleTitle =
      title ||
      (secondaryQty && secondaryUom
        ? `${formattedPrimary} ${primaryUom} (equivalent to ${formattedSecondary} ${secondaryUom}${
            conversionRatio ? ` · Rate: ${conversionRatio}` : ''
          })`
        : `${formattedPrimary} ${primaryUom}`);

    return (
      <span
        ref={ref}
        className={`ds-dual-uom-badge ${className}`}
        title={accessibleTitle}
        aria-label={accessibleTitle}
        {...props}
      >
        <span className="ds-dual-uom-badge__primary">
          {formattedPrimary} {primaryUom}
        </span>
        {secondaryQty !== undefined && secondaryUom && (
          <>
            <span className="ds-dual-uom-badge__separator" aria-hidden="true">
              |
            </span>
            <span className="ds-dual-uom-badge__secondary">
              ~{formattedSecondary} {secondaryUom}
            </span>
          </>
        )}
      </span>
    );
  }
);

DualUomBadge.displayName = 'DualUomBadge';
