// packages/react/src/components/Layout/AspectRatio.tsx
import React, { forwardRef } from 'react';
import './Layout.css';

export type AspectRatioPreset = '16/9' | '4/3' | '1/1' | '21/9' | '3/2';

export interface AspectRatioProps extends React.HTMLAttributes<HTMLElement> {
  as?: React.ElementType;
  ratio?: number | AspectRatioPreset;
}

const presetRatioMap: Record<AspectRatioPreset, string> = {
  '16/9': '16 / 9',
  '4/3': '4 / 3',
  '1/1': '1 / 1',
  '21/9': '21 / 9',
  '3/2': '3 / 2',
};

export const AspectRatio = forwardRef<HTMLElement, AspectRatioProps>(
  (
    {
      as = 'div',
      ratio = '16/9',
      children,
      className = '',
      style,
      ...props
    },
    ref
  ) => {
    const Component = as;

    const computedRatio =
      typeof ratio === 'string' && ratio in presetRatioMap
        ? presetRatioMap[ratio as AspectRatioPreset]
        : String(ratio);

    const computedStyle: React.CSSProperties = {
      ...style,
      aspectRatio: computedRatio,
    };

    return (
      <Component
        ref={ref}
        className={`ds-aspect-ratio ${className}`}
        style={computedStyle}
        {...props}
      >
        {children}
      </Component>
    );
  }
);

AspectRatio.displayName = 'AspectRatio';

// packages/angular/src/components/layout/aspect-ratio.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DsAspectRatioPreset = '16/9' | '4/3' | '1/1' | '21/9' | '3/2';

const presetRatioMap: Record<DsAspectRatioPreset, string> = {
  '16/9': '16 / 9',
  '4/3': '4 / 3',
  '1/1': '1 / 1',
  '21/9': '21 / 9',
  '3/2': '3 / 2',
};

@Component({
  selector: 'ds-aspect-ratio',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="ds-aspect-ratio"
      [ngStyle]="customStyles"
    >
      <ng-content></ng-content>
    </div>
  `,
  styleUrls: ['./layout.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsAspectRatioComponent {
  @Input() ratio: number | DsAspectRatioPreset = '16/9';

  get customStyles(): Record<string, string> {
    const computedRatio =
      typeof this.ratio === 'string' && this.ratio in presetRatioMap
        ? presetRatioMap[this.ratio as DsAspectRatioPreset]
        : String(this.ratio);

    return {
      aspectRatio: computedRatio,
    };
  }
}
