// packages/react/src/components/Layout/Grid.tsx
import React, { forwardRef } from 'react';
import { SpacingScale } from './Box.js';
import './Layout.css';

export type GridColumns = 1 | 2 | 3 | 4 | 6 | 12;

export interface GridProps extends React.HTMLAttributes<HTMLElement> {
  as?: React.ElementType;
  columns?: GridColumns;
  gap?: SpacingScale;
  p?: SpacingScale;
}

export const Grid = forwardRef<HTMLElement, GridProps>(
  ({ children, as = 'div', columns = 3, gap = 4, p, className = '', ...props }, ref) => {
    const Component = as;

    const classNames = [
      'ds-grid',
      `ds-grid--cols-${columns}`,
      `ds-gap-${gap}`,
      p !== undefined ? `ds-p-${p}` : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <Component ref={ref} className={classNames} {...props}>
        {children}
      </Component>
    );
  }
);

Grid.displayName = 'Grid';

// packages/angular/src/components/layout/grid.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DsSpacingScale } from './box.component.js';

export type DsGridColumns = 1 | 2 | 3 | 4 | 6 | 12;

@Component({
  selector: 'ds-grid',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [ngClass]="rootClasses">
      <ng-content></ng-content>
    </div>
  `,
  styleUrls: ['./layout.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsGridComponent {
  @Input() columns: DsGridColumns = 3;
  @Input() gap: DsSpacingScale = 4;
  @Input() p?: DsSpacingScale;

  get rootClasses(): string {
    return [
      'ds-grid',
      `ds-grid--cols-${this.columns}`,
      `ds-gap-${this.gap}`,
      this.p !== undefined ? `ds-p-${this.p}` : '',
    ]
      .filter(Boolean)
      .join(' ');
  }
}
