// packages/react/src/components/Layout/Spacer.tsx
import React, { forwardRef } from 'react';
import { SpacingScale } from './Box.js';
import './Layout.css';

export type SpacerAxis = 'horizontal' | 'vertical' | 'both';

export interface SpacerProps extends React.HTMLAttributes<HTMLElement> {
  as?: React.ElementType;
  size?: SpacingScale;
  axis?: SpacerAxis;
  flex?: number | string;
}

export const Spacer = forwardRef<HTMLElement, SpacerProps>(
  (
    {
      as = 'div',
      size,
      axis = 'both',
      flex,
      className = '',
      style,
      ...props
    },
    ref
  ) => {
    const Component = as;

    const isFlexExpand = size === undefined && flex === undefined;

    const classNames = [
      'ds-spacer',
      isFlexExpand ? 'ds-spacer--flex' : '',
      size !== undefined ? `ds-spacer--${axis}-${size}` : '',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const computedStyle: React.CSSProperties = {
      ...style,
      ...(flex !== undefined ? { flex } : {}),
    };

    return (
      <Component
        ref={ref}
        aria-hidden="true"
        className={classNames}
        style={computedStyle}
        {...props}
      />
    );
  }
);

Spacer.displayName = 'Spacer';

// packages/angular/src/components/layout/spacer.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DsSpacingScale } from './box.component.js';

export type DsSpacerAxis = 'horizontal' | 'vertical' | 'both';

@Component({
  selector: 'ds-spacer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      aria-hidden="true"
      [ngClass]="rootClasses"
      [ngStyle]="customStyles"
    ></div>
  `,
  styleUrls: ['./layout.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsSpacerComponent {
  @Input() size?: DsSpacingScale;
  @Input() axis: DsSpacerAxis = 'both';
  @Input() flex?: number | string;

  get isFlexExpand(): boolean {
    return this.size === undefined && this.flex === undefined;
  }

  get rootClasses(): string {
    return [
      'ds-spacer',
      this.isFlexExpand ? 'ds-spacer--flex' : '',
      this.size !== undefined ? `ds-spacer--${this.axis}-${this.size}` : '',
    ]
      .filter(Boolean)
      .join(' ');
  }

  get customStyles(): Record<string, string | number> {
    const styles: Record<string, string | number> = {};
    if (this.flex !== undefined) {
      styles['flex'] = this.flex;
    }
    return styles;
  }
}
