// packages/react/src/components/ScopePicker/ScopePicker.tsx
import React, { forwardRef, useState } from 'react';
import { Select, SelectItem } from '../Select/index.js';
import { Button } from '../Button/index.js';
import { Badge } from '../Badge/index.js';
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbPage, BreadcrumbSeparator } from '../Breadcrumb/index.js';
import { HStack } from '../Layout/index.js';
import { Text } from '../Typography/index.js';
import './ScopePicker.css';

export interface ScopeSelection {
  plant?: string;
  area?: string;
  unit?: string;
}

export interface ScopePickerProps {
  value?: ScopeSelection;
  defaultValue?: ScopeSelection;
  onChange?: (scope: ScopeSelection) => void;
  onClear?: () => void;
  className?: string;
}

const plantOptions: SelectItem[] = [
  { label: 'Plant 01 - Pune HQ', value: 'plant-01' },
  { label: 'Plant 04 - Chakan Press Shop', value: 'plant-04' },
  { label: 'Plant 07 - Sanand Assembly', value: 'plant-07' },
];

const areaOptions: Record<string, SelectItem[]> = {
  'plant-04': [
    { label: 'Turbine Hall Bay 1', value: 'bay-1' },
    { label: 'Heavy Stamping Line 4', value: 'stamping-4' },
    { label: 'Auxiliary Boiler House', value: 'boiler-house' },
  ],
  'plant-01': [
    { label: 'CNC Machining Bay', value: 'cnc-bay' },
    { label: 'Inspection Cleanroom', value: 'cleanroom' },
  ],
  'plant-07': [
    { label: 'Final Robotic Chassis Line', value: 'robotics' },
    { label: 'Battery Pack Testing Cell', value: 'battery-cell' },
  ],
};

const unitOptions: Record<string, SelectItem[]> = {
  // Plant 04 - Chakan Press Shop
  'bay-1': [
    { label: 'Turbine Generator TG-401', value: 'tg-401' },
    { label: 'Steam Manifold Valve V-12', value: 'v-12' },
  ],
  'stamping-4': [
    { label: 'Hydraulic Press 2000T', value: 'press-2000' },
    { label: 'Blank Feeder F-08', value: 'feeder-08' },
  ],
  'boiler-house': [
    { label: 'High-Pressure Steam Boiler B-01', value: 'boiler-01' },
    { label: 'Feedwater Pump Set P-03', value: 'pump-03' },
  ],

  // Plant 01 - Pune HQ
  'cnc-bay': [
    { label: '5-Axis CNC Milling Center MC-01', value: 'cnc-01' },
    { label: 'Precision CNC Lathe L-04', value: 'lathe-04' },
    { label: 'Horizontal Boring Mill HB-02', value: 'boring-02' },
  ],
  'cleanroom': [
    { label: 'Coordinate Measuring Machine CMM-01', value: 'cmm-01' },
    { label: 'Optical Profile Projector OPP-02', value: 'opp-02' },
    { label: 'Surface Roughness Tester SRT-01', value: 'srt-01' },
  ],

  // Plant 07 - Sanand Assembly
  'robotics': [
    { label: 'Spot Welding Robot Arm R-101', value: 'robot-101' },
    { label: 'Automated Guided Vehicle AGV-04', value: 'agv-04' },
    { label: 'Chassis Transfer Conveyor TC-02', value: 'conveyor-02' },
  ],
  'battery-cell': [
    { label: 'High-Voltage Discharge Cycler DC-01', value: 'cycler-01' },
    { label: 'Thermal Chamber TC-80', value: 'thermal-80' },
    { label: 'Pack Insulation Tester IT-02', value: 'tester-02' },
  ],
};

export const ScopePicker = forwardRef<HTMLDivElement, ScopePickerProps>(
  (
    {
      value: controlledValue,
      defaultValue = { plant: 'plant-04', area: 'bay-1', unit: 'tg-401' },
      onChange,
      onClear,
      className = '',
    },
    ref
  ) => {
    const isControlled = controlledValue !== undefined;
    const [internalScope, setInternalScope] = useState<ScopeSelection>(defaultValue);
    const currentScope = isControlled ? controlledValue : internalScope;

    const handlePlantChange = (val: string[]) => {
      const plant = val?.[0];
      const newScope = { plant, area: undefined, unit: undefined };
      if (!isControlled) setInternalScope(newScope);
      onChange?.(newScope);
    };

    const handleAreaChange = (val: string[]) => {
      const area = val?.[0];
      const newScope = { ...currentScope, area, unit: undefined };
      if (!isControlled) setInternalScope(newScope);
      onChange?.(newScope);
    };

    const handleUnitChange = (val: string[]) => {
      const unit = val?.[0];
      const newScope = { ...currentScope, unit };
      if (!isControlled) setInternalScope(newScope);
      onChange?.(newScope);
    };

    const handleClear = () => {
      const emptyScope = { plant: undefined, area: undefined, unit: undefined };
      if (!isControlled) setInternalScope(emptyScope);
      onChange?.(emptyScope);
      onClear?.();
    };

    const currentPlantLabel = plantOptions.find((p) => p.value === currentScope.plant)?.label;
    const availableAreas = currentScope.plant ? areaOptions[currentScope.plant] || [] : [];
    const currentAreaLabel = availableAreas.find((a) => a.value === currentScope.area)?.label;
    const availableUnits = currentScope.area ? unitOptions[currentScope.area] || [] : [];
    const currentUnitLabel = availableUnits.find((u) => u.value === currentScope.unit)?.label;

    return (
      <div ref={ref} className={`ds-scope-picker ${className}`}>
        <div className="ds-scope-picker-controls">
          <Select
            label="Enterprise Plant Site"
            items={plantOptions}
            placeholder="Select Plant..."
            value={currentScope.plant ? [currentScope.plant] : []}
            onValueChange={(d) => handlePlantChange(d.value)}
          />

          <Select
            key={`area-${currentScope.plant || 'none'}`}
            label="Manufacturing Area / Hall"
            items={availableAreas}
            placeholder={currentScope.plant ? 'Select Area...' : 'Select Plant first'}
            disabled={!currentScope.plant || availableAreas.length === 0}
            value={currentScope.area ? [currentScope.area] : []}
            onValueChange={(d) => handleAreaChange(d.value)}
          />

          <Select
            key={`unit-${currentScope.plant || 'none'}-${currentScope.area || 'none'}`}
            label="Machine / Asset Unit"
            items={availableUnits}
            placeholder={currentScope.area ? 'Select Unit...' : 'Select Area first'}
            disabled={!currentScope.area || availableUnits.length === 0}
            value={currentScope.unit ? [currentScope.unit] : []}
            onValueChange={(d) => handleUnitChange(d.value)}
          />
        </div>

        {(currentPlantLabel || currentAreaLabel || currentUnitLabel) && (
          <div className="ds-scope-picker-summary">
            <HStack gap={2} align="center">
              <Text size="xs" color="secondary" weight="medium">
                Active Scope:
              </Text>
              <Breadcrumb>
                <BreadcrumbList>
                  {currentPlantLabel && (
                    <BreadcrumbItem>
                      <BreadcrumbPage>{currentPlantLabel}</BreadcrumbPage>
                    </BreadcrumbItem>
                  )}
                  {currentAreaLabel && (
                    <>
                      <BreadcrumbSeparator />
                      <BreadcrumbItem>
                        <BreadcrumbPage>{currentAreaLabel}</BreadcrumbPage>
                      </BreadcrumbItem>
                    </>
                  )}
                  {currentUnitLabel && (
                    <>
                      <BreadcrumbSeparator />
                      <BreadcrumbItem>
                        <Badge variant="brand">{currentUnitLabel}</Badge>
                      </BreadcrumbItem>
                    </>
                  )}
                </BreadcrumbList>
              </Breadcrumb>
            </HStack>

            <Button variant="ghost" size="sm" onClick={handleClear}>
              Clear Filter
            </Button>
          </div>
        )}
      </div>
    );
  }
);

ScopePicker.displayName = 'ScopePicker';

// packages/angular/src/components/scope-picker/scope-picker.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';

export interface ScopeData {
  plant?: string;
  area?: string;
  unit?: string;
}

@Component({
  selector: 'ds-scope-picker',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="ds-scope-picker" [class]="customClass">
      <div class="ds-scope-picker-controls">
        <div>
          <label style="display: block; font-size: 14px; font-weight: 500; margin-bottom: 4px;">Enterprise Plant</label>
          <select
            style="width: 100%; padding: 8px; border-radius: 6px; border: 1px solid #D1D5DB;"
            [value]="scope.plant || ''"
            (change)="onPlantSelect($event)"
          >
            <option value="">Select Plant...</option>
            <option value="plant-01">Plant 01 - Pune HQ</option>
            <option value="plant-04">Plant 04 - Chakan Press Shop</option>
            <option value="plant-07">Plant 07 - Sanand Assembly</option>
          </select>
        </div>

        <div>
          <label style="display: block; font-size: 14px; font-weight: 500; margin-bottom: 4px;">Area / Hall</label>
          <select
            style="width: 100%; padding: 8px; border-radius: 6px; border: 1px solid #D1D5DB;"
            [disabled]="!scope.plant"
            [value]="scope.area || ''"
            (change)="onAreaSelect($event)"
          >
            <option value="">Select Area...</option>
            <option *ngIf="scope.plant === 'plant-04'" value="bay-1">Turbine Hall Bay 1</option>
            <option *ngIf="scope.plant === 'plant-04'" value="stamping-4">Heavy Stamping Line 4</option>
            <option *ngIf="scope.plant === 'plant-04'" value="boiler-house">Auxiliary Boiler House</option>
            <option *ngIf="scope.plant === 'plant-01'" value="cnc-bay">CNC Machining Bay</option>
            <option *ngIf="scope.plant === 'plant-01'" value="cleanroom">Inspection Cleanroom</option>
            <option *ngIf="scope.plant === 'plant-07'" value="robotics">Robotic Chassis Line</option>
            <option *ngIf="scope.plant === 'plant-07'" value="battery-cell">Battery Pack Testing Cell</option>
          </select>
        </div>

        <div>
          <label style="display: block; font-size: 14px; font-weight: 500; margin-bottom: 4px;">Machine Unit</label>
          <select
            style="width: 100%; padding: 8px; border-radius: 6px; border: 1px solid #D1D5DB;"
            [disabled]="!scope.area"
            [value]="scope.unit || ''"
            (change)="onUnitSelect($event)"
          >
            <option value="">Select Unit...</option>
            <option *ngIf="scope.area === 'bay-1'" value="tg-401">Turbine Generator TG-401</option>
            <option *ngIf="scope.area === 'bay-1'" value="v-12">Steam Manifold Valve V-12</option>
            <option *ngIf="scope.area === 'stamping-4'" value="press-2000">Hydraulic Press 2000T</option>
            <option *ngIf="scope.area === 'stamping-4'" value="feeder-08">Blank Feeder F-08</option>
            <option *ngIf="scope.area === 'boiler-house'" value="boiler-01">High-Pressure Boiler B-01</option>
            <option *ngIf="scope.area === 'cnc-bay'" value="cnc-01">5-Axis CNC Milling Center MC-01</option>
            <option *ngIf="scope.area === 'cnc-bay'" value="lathe-04">Precision CNC Lathe L-04</option>
            <option *ngIf="scope.area === 'cleanroom'" value="cmm-01">Coordinate Measuring Machine CMM-01</option>
            <option *ngIf="scope.area === 'cleanroom'" value="opp-02">Optical Profile Projector OPP-02</option>
            <option *ngIf="scope.area === 'robotics'" value="robot-101">Spot Welding Robot Arm R-101</option>
            <option *ngIf="scope.area === 'battery-cell'" value="cycler-01">High-Voltage Discharge Cycler DC-01</option>
          </select>
        </div>
      </div>

      <div *ngIf="scope.plant || scope.area || scope.unit" class="ds-scope-picker-summary">
        <span style="font-size: 13px; color: #4B5563;">
          Scope: <strong>{{ scope.plant }}</strong> &gt; <strong>{{ scope.area }}</strong> &gt; <strong>{{ scope.unit }}</strong>
        </span>
        <button
          type="button"
          style="background: transparent; border: none; color: #2563EB; font-size: 13px; cursor: pointer;"
          (click)="clearScope()"
        >
          Clear
        </button>
      </div>
    </div>
  `,
  styleUrls: ['./scope-picker.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsScopePickerComponent {
  @Input() scope: ScopeData = { plant: 'plant-04', area: 'bay-1', unit: 'tg-401' };
  @Input() customClass = '';

  @Output() scopeChange = new EventEmitter<ScopeData>();

  onPlantSelect(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.scope = { plant: target.value || undefined, area: undefined, unit: undefined };
    this.scopeChange.emit(this.scope);
  }

  onAreaSelect(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.scope = { ...this.scope, area: target.value || undefined, unit: undefined };
    this.scopeChange.emit(this.scope);
  }

  onUnitSelect(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.scope = { ...this.scope, unit: target.value || undefined };
    this.scopeChange.emit(this.scope);
  }

  clearScope(): void {
    this.scope = {};
    this.scopeChange.emit(this.scope);
  }
}
