// components/data/ParallelCoordinates.jsx
import React, { useState, useMemo, useRef, useEffect, useCallback } from 'react';

/**
 * ParallelCoordinates - Meridian Design System
 *
 * Purpose: Compare multivariate profiles across many dimensions and identify clusters, trade-offs and anomalous records.
 * Supported Variants:
 *  - 'standard': Raw dimensional values on individual linear axes.
 *  - 'normalized': 0% - 100% normalized scales across all axes for uniform slope comparison.
 *  - 'spline': Smooth cubic bezier curves connecting axes.
 *  - 'brushed': Interactive 1D range brushing to filter multidimensional records.
 */

const CLUSTER_COLORS = [
  '#0284c7', // Sky blue (Cluster A / Class 1)
  '#16a34a', // Emerald green (Cluster B / Class 2)
  '#d97706', // Amber warning (Cluster C / Outliers)
  '#7c3aed', // Purple (Cluster D)
  '#dc2626', // Ruby critical
  '#0d9488'  // Teal
];

export function ParallelCoordinates({
  data = [],
  dimensions = [],
  variant = 'standard', // 'standard' | 'normalized' | 'spline' | 'brushed'
  width = 860,
  height = 420,
  title = 'Multivariate Process & Quality Telemetry',
  subtitle = 'Suryodaya Autocomp Ltd · Chakan Plant (PL-04)',
  colorKey = 'cluster', // Key used to color-code polylines
  idKey = 'id',
  labelKey = 'label',
  smooth = false,
  normalized = false,
  showBrushControls = true,
  showControls = true,
  showSearch = true,
  className = '',
  onRecordClick = null
}) {
  const [activeDimensions, setActiveDimensions] = useState(dimensions);
  const [isNormalized, setIsNormalized] = useState(normalized || variant === 'normalized');
  const [isSmooth, setIsSmooth] = useState(smooth || variant === 'spline');
  const [activeBrushes, setActiveBrushes] = useState({});
  const [selectedRecordId, setSelectedRecordId] = useState(null);
  const [hoveredRecord, setHoveredRecord] = useState(null);
  const [tooltipPos, setTooltipPos] = useState({ x: 0, y: 0 });
  const [searchQuery, setSearchQuery] = useState('');
  const [isTableModalOpen, setIsTableModalOpen] = useState(false);
  const [isFilterPanelOpen, setIsFilterPanelOpen] = useState(false);

  // Sync dimensions when prop changes
  useEffect(() => {
    setActiveDimensions(dimensions);
  }, [dimensions]);

  // Keyboard shortcut for Accessible Modal (Alt + F11)
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.altKey && (e.key === 'F11' || e.keyCode === 122)) {
        e.preventDefault();
        setIsTableModalOpen(prev => !prev);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  // Filter Data by Search Query & Active 1D Brushes
  const filteredData = useMemo(() => {
    const q = searchQuery.toLowerCase().trim();
    return data.filter(d => {
      // 1. Text Search Filter
      if (q) {
        const idVal = String(d[idKey] || '').toLowerCase();
        const lblVal = String(d[labelKey] || '').toLowerCase();
        const clusterVal = String(d[colorKey] || '').toLowerCase();
        if (!idVal.includes(q) && !lblVal.includes(q) && !clusterVal.includes(q)) {
          return false;
        }
      }

      // 2. Multidimensional Range Brush Filter
      const brushKeys = Object.keys(activeBrushes);
      for (let i = 0; i < brushKeys.length; i++) {
        const k = brushKeys[i];
        const brush = activeBrushes[k];
        if (brush && (brush.min != null || brush.max != null)) {
          const val = Number(d[k]);
          if (isNaN(val)) return false;
          if (brush.min != null && val < brush.min) return false;
          if (brush.max != null && val > brush.max) return false;
        }
      }

      return true;
    });
  }, [data, searchQuery, activeBrushes, idKey, labelKey, colorKey]);

  // Layout Dimensions & Margins
  const margin = useMemo(() => ({
    top: 36,
    right: 48,
    bottom: 40,
    left: 48
  }), []);

  const innerWidth = Math.max(100, width - margin.left - margin.right);
  const innerHeight = Math.max(100, height - margin.top - margin.bottom);

  // Compute Domain Bounds for each Dimension
  const dimensionDomains = useMemo(() => {
    const domains = {};
    activeDimensions.forEach(dim => {
      const key = typeof dim === 'string' ? dim : dim.key;
      let min = dim.min != null ? Number(dim.min) : Infinity;
      let max = dim.max != null ? Number(dim.max) : -Infinity;

      data.forEach(d => {
        const v = d[key] != null ? Number(d[key]) : null;
        if (v != null && !isNaN(v)) {
          if (v < min) min = v;
          if (v > max) max = v;
        }
      });

      if (min === Infinity || max === -Infinity) {
        min = 0;
        max = 100;
      }

      const span = max - min || 1;
      const pad = span * 0.05;
      const paddedMin = dim.min != null ? dim.min : min - pad;
      const paddedMax = dim.max != null ? dim.max : max + pad;

      domains[key] = {
        key,
        min: paddedMin,
        max: paddedMax,
        rawMin: min,
        rawMax: max,
        span: paddedMax - paddedMin,
        unit: dim.unit || '',
        label: dim.label || key,
        inverted: !!dim.inverted
      };
    });
    return domains;
  }, [activeDimensions, data]);

  // Calculate Parallel Axis X Coordinates
  const axisCount = activeDimensions.length;
  const axisSpacing = axisCount > 1 ? innerWidth / (axisCount - 1) : innerWidth / 2;

  const axisXCoords = useMemo(() => {
    return activeDimensions.map((_, i) => i * axisSpacing);
  }, [activeDimensions, axisSpacing]);

  // Scaler mapping raw value to Y coordinate
  const valToY = useCallback((val, dimKey) => {
    const domain = dimensionDomains[dimKey];
    if (!domain || val == null || isNaN(Number(val))) return innerHeight / 2;

    if (isNormalized) {
      // 0 to 1 normalized
      let norm = (Number(val) - domain.rawMin) / (domain.rawMax - domain.rawMin || 1);
      norm = Math.max(0, Math.min(1, norm));
      if (domain.inverted) norm = 1 - norm;
      return innerHeight - norm * innerHeight;
    }

    // Raw scaling
    let norm = (Number(val) - domain.min) / domain.span;
    norm = Math.max(0, Math.min(1, norm));
    if (domain.inverted) norm = 1 - norm;
    return innerHeight - norm * innerHeight;
  }, [dimensionDomains, innerHeight, isNormalized]);

  // Generate Polyline SVG path
  const buildPolylinePath = useCallback((record) => {
    const points = [];
    activeDimensions.forEach((dim, i) => {
      const key = typeof dim === 'string' ? dim : dim.key;
      const x = axisXCoords[i];
      const y = valToY(record[key], key);
      points.push([x, y]);
    });

    if (points.length === 0) return '';
    if (!isSmooth) {
      let p = `M ${points[0][0]} ${points[0][1]}`;
      for (let i = 1; i < points.length; i++) {
        p += ` L ${points[i][0]} ${points[i][1]}`;
      }
      return p;
    }

    // Cubic bezier spline
    let p = `M ${points[0][0]} ${points[0][1]}`;
    for (let i = 0; i < points.length - 1; i++) {
      const p0 = points[i];
      const p1 = points[i + 1];
      const dx = p1[0] - p0[0];
      const cx1 = p0[0] + dx * 0.4;
      const cy1 = p0[1];
      const cx2 = p1[0] - dx * 0.4;
      const cy2 = p1[1];
      p += ` C ${cx1} ${cy1}, ${cx2} ${cy2}, ${p1[0]} ${p1[1]}`;
    }
    return p;
  }, [activeDimensions, axisXCoords, valToY, isSmooth]);

  // Color Mapping by Cluster or Status
  const getRecordColor = useCallback((record) => {
    if (record.color) return record.color;
    const cVal = record[colorKey];
    if (typeof cVal === 'number') {
      return CLUSTER_COLORS[cVal % CLUSTER_COLORS.length];
    }
    if (typeof cVal === 'string') {
      let hash = 0;
      for (let i = 0; i < cVal.length; i++) hash = cVal.charCodeAt(i) + ((hash << 5) - hash);
      const idx = Math.abs(hash) % CLUSTER_COLORS.length;
      return CLUSTER_COLORS[idx];
    }
    return CLUSTER_COLORS[0];
  }, [colorKey]);

  // Axis Reordering Handlers (Move Left / Move Right)
  const moveAxis = (idx, direction) => {
    const targetIdx = idx + direction;
    if (targetIdx < 0 || targetIdx >= activeDimensions.length) return;
    const next = [...activeDimensions];
    const temp = next[idx];
    next[idx] = next[targetIdx];
    next[targetIdx] = temp;
    setActiveDimensions(next);
  };

  // Brush Filter Update
  const updateBrush = (key, field, val) => {
    setActiveBrushes(prev => {
      const current = prev[key] || { min: dimensionDomains[key].rawMin, max: dimensionDomains[key].rawMax };
      const num = val === '' ? null : Number(val);
      const nextBrush = { ...current, [field]: num };
      return { ...prev, [key]: nextBrush };
    });
  };

  const clearAllBrushes = () => {
    setActiveBrushes({});
    setSearchQuery('');
  };

  const activeBrushCount = Object.keys(activeBrushes).filter(k => activeBrushes[k].min != null || activeBrushes[k].max != null).length;

  return (
    <div
      className={`parallel-coordinates-container ${className}`}
      style={{
        position: 'relative',
        background: '#ffffff',
        border: '1px solid #e2e8f0',
        borderRadius: 8,
        padding: '16px 20px',
        fontFamily: 'system-ui, -apple-system, sans-serif'
      }}
    >
      {/* Header & Controls Toolbar */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        flexWrap: 'wrap',
        gap: 12
      }}>
        <div>
          <div style={{ fontWeight: 700, fontSize: 15, color: '#0f172a' }}>{title}</div>
          <div style={{ fontSize: 12, color: '#64748b', marginTop: 2 }}>
            {subtitle} · Showing <strong>{filteredData.length}</strong> of {data.length} records
          </div>
        </div>

        {showControls && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
            {/* Search Input */}
            {showSearch && (
              <div style={{ position: 'relative' }}>
                <input
                  type="text"
                  placeholder="Filter record/batch..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  style={{
                    padding: '4px 10px',
                    fontSize: 12,
                    border: '1px solid #cbd5e1',
                    borderRadius: 4,
                    outline: 'none',
                    width: 150
                  }}
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery('')}
                    style={{
                      position: 'absolute',
                      right: 6,
                      top: '50%',
                      transform: 'translateY(-50%)',
                      border: 'none',
                      background: 'none',
                      cursor: 'pointer',
                      color: '#94a3b8',
                      fontSize: 11
                    }}
                  >✕</button>
                )}
              </div>
            )}

            {/* Normalization Toggle */}
            <label style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: '#334155', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={isNormalized}
                onChange={(e) => setIsNormalized(e.target.checked)}
              />
              Normalize 0–100%
            </label>

            {/* Spline Smooth Toggle */}
            <label style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: '#334155', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={isSmooth}
                onChange={(e) => setIsSmooth(e.target.checked)}
              />
              Smooth Spline
            </label>

            {/* Accessible Brush Filters Modal Trigger */}
            <button
              onClick={() => setIsFilterPanelOpen(prev => !prev)}
              style={{
                padding: '4px 10px',
                fontSize: 11,
                fontWeight: 600,
                border: '1px solid #cbd5e1',
                borderRadius: 4,
                background: activeBrushCount > 0 ? '#eff6ff' : '#ffffff',
                color: activeBrushCount > 0 ? '#0284c7' : '#334155',
                cursor: 'pointer'
              }}
            >
              🎯 Brush Filters {activeBrushCount > 0 ? `(${activeBrushCount})` : ''}
            </button>

            {/* Accessible Table Modal Trigger */}
            <button
              onClick={() => setIsTableModalOpen(true)}
              title="Accessible Table Modal (Alt + F11)"
              style={{
                padding: '4px 10px',
                fontSize: 11,
                fontWeight: 600,
                border: '1px solid #cbd5e1',
                borderRadius: 4,
                background: '#f8fafc',
                color: '#0284c7',
                cursor: 'pointer'
              }}
            >
              📊 Table View
            </button>
          </div>
        )}
      </div>

      {/* Non-Drag Accessible Brush Controls Panel */}
      {isFilterPanelOpen && (
        <div style={{
          background: '#f8fafc',
          border: '1px solid #e2e8f0',
          borderRadius: 6,
          padding: '12px 16px',
          marginBottom: 16,
          fontSize: 12
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <span style={{ fontWeight: 600, color: '#0f172a' }}>Accessible 1D Axis Range Filters (Keyboard Alternative to Drag Brushes)</span>
            {activeBrushCount > 0 && (
              <button
                onClick={clearAllBrushes}
                style={{ border: 'none', background: 'none', color: '#dc2626', fontSize: 11, cursor: 'pointer', fontWeight: 600 }}
              >
                Reset All Filters
              </button>
            )}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 12 }}>
            {activeDimensions.map(dim => {
              const key = typeof dim === 'string' ? dim : dim.key;
              const d = dimensionDomains[key];
              const brush = activeBrushes[key] || {};

              return (
                <div key={key} style={{ background: '#ffffff', padding: '8px 10px', borderRadius: 4, border: '1px solid #cbd5e1' }}>
                  <div style={{ fontWeight: 600, fontSize: 11, color: '#334155', marginBottom: 4 }}>
                    {d.label} {d.unit ? `(${d.unit})` : ''}
                  </div>
                  <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                    <input
                      type="number"
                      placeholder={`Min (${d.rawMin.toFixed(0)})`}
                      value={brush.min ?? ''}
                      onChange={(e) => updateBrush(key, 'min', e.target.value)}
                      style={{ width: '48%', padding: '3px 6px', fontSize: 11, border: '1px solid #cbd5e1', borderRadius: 3 }}
                    />
                    <span style={{ color: '#94a3b8' }}>–</span>
                    <input
                      type="number"
                      placeholder={`Max (${d.rawMax.toFixed(0)})`}
                      value={brush.max ?? ''}
                      onChange={(e) => updateBrush(key, 'max', e.target.value)}
                      style={{ width: '48%', padding: '3px 6px', fontSize: 11, border: '1px solid #cbd5e1', borderRadius: 3 }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* SVG Parallel Coordinates Canvas */}
      <div style={{ position: 'relative', width: '100%', overflowX: 'auto' }}>
        <svg
          width={width}
          height={height}
          viewBox={`0 0 ${width} ${height}`}
          style={{ display: 'block', margin: '0 auto' }}
        >
          <g transform={`translate(${margin.left}, ${margin.top})`}>
            {/* 1. Inactive / Filtered-out Polylines (Muted Background) */}
            {data.map((record, idx) => {
              const isPassing = filteredData.includes(record);
              if (isPassing) return null; // rendered in foreground
              const p = buildPolylinePath(record);
              return (
                <path
                  key={record[idKey] || idx}
                  d={p}
                  fill="none"
                  stroke="#e2e8f0"
                  strokeWidth="1"
                  opacity="0.4"
                />
              );
            })}

            {/* 2. Active / Filtered Polylines */}
            {filteredData.map((record, idx) => {
              const itemId = record[idKey] || `rec-${idx}`;
              const isSelected = selectedRecordId === itemId;
              const isHovered = hoveredRecord?.id === itemId;
              const color = getRecordColor(record);
              const p = buildPolylinePath(record);

              return (
                <path
                  key={itemId}
                  d={p}
                  fill="none"
                  stroke={isSelected ? '#0284c7' : color}
                  strokeWidth={isSelected ? 3.5 : isHovered ? 3 : 1.5}
                  opacity={hoveredRecord && !isHovered && !isSelected ? 0.2 : isSelected || isHovered ? 1 : 0.7}
                  style={{ cursor: 'pointer', transition: 'stroke-width 0.15s ease, opacity 0.15s ease' }}
                  onMouseEnter={(e) => {
                    setHoveredRecord({ ...record, id: itemId });
                    setTooltipPos({ x: e.clientX, y: e.clientY });
                  }}
                  onMouseLeave={() => setHoveredRecord(null)}
                  onClick={(e) => {
                    setSelectedRecordId(itemId);
                    if (onRecordClick) onRecordClick(record, e);
                  }}
                />
              );
            })}

            {/* 3. Parallel Vertical Axes */}
            {activeDimensions.map((dim, i) => {
              const key = typeof dim === 'string' ? dim : dim.key;
              const d = dimensionDomains[key];
              const x = axisXCoords[i];

              // Generate 5 ticks per axis
              const ticks = [0, 0.25, 0.5, 0.75, 1].map(pct => {
                const y = innerHeight - pct * innerHeight;
                let valLabel = '';
                if (isNormalized) {
                  valLabel = `${(pct * 100).toFixed(0)}%`;
                } else {
                  const rawVal = d.rawMin + pct * (d.rawMax - d.rawMin);
                  valLabel = rawVal.toLocaleString('en-IN', { maximumFractionDigits: 1 });
                }
                return { y, label: valLabel };
              });

              return (
                <g key={key} transform={`translate(${x}, 0)`}>
                  {/* Axis Background Line */}
                  <line
                    y1="0"
                    y2={innerHeight}
                    stroke="#475569"
                    strokeWidth="1.5"
                  />

                  {/* Axis Reorder Buttons */}
                  <g transform="translate(0, -22)">
                    {i > 0 && (
                      <text
                        x="-10"
                        y="0"
                        fontSize="10"
                        fill="#0284c7"
                        textAnchor="end"
                        style={{ cursor: 'pointer', userSelect: 'none' }}
                        onClick={() => moveAxis(i, -1)}
                        title="Move Axis Left"
                      >◀</text>
                    )}
                    {i < activeDimensions.length - 1 && (
                      <text
                        x="10"
                        y="0"
                        fontSize="10"
                        fill="#0284c7"
                        textAnchor="start"
                        style={{ cursor: 'pointer', userSelect: 'none' }}
                        onClick={() => moveAxis(i, 1)}
                        title="Move Axis Right"
                      >▶</text>
                    )}
                  </g>

                  {/* Dimension Title Label */}
                  <text
                    x="0"
                    y="-8"
                    fontSize="11"
                    fontWeight="700"
                    fill="#0f172a"
                    textAnchor="middle"
                  >
                    {d.label}
                  </text>
                  {d.unit && (
                    <text
                      x="0"
                      y={innerHeight + 16}
                      fontSize="10"
                      fill="#64748b"
                      textAnchor="middle"
                    >
                      {d.unit}
                    </text>
                  )}

                  {/* Axis Ticks */}
                  {ticks.map((t, tIdx) => (
                    <g key={tIdx} transform={`translate(0, ${t.y})`}>
                      <line x1="-4" x2="4" stroke="#94a3b8" strokeWidth="1" />
                      <text
                        x="-7"
                        y="3"
                        fontSize="9"
                        fill="#64748b"
                        textAnchor="end"
                      >
                        {t.label}
                      </text>
                    </g>
                  ))}

                  {/* Active Hover Intersection Crosshair Indicator */}
                  {hoveredRecord && hoveredRecord[key] != null && (
                    <g transform={`translate(0, ${valToY(hoveredRecord[key], key)})`}>
                      <circle r="4.5" fill="#0284c7" stroke="#ffffff" strokeWidth="2" />
                      <rect x="8" y="-9" width="45" height="16" rx="3" fill="#0f172a" opacity="0.85" />
                      <text x="12" y="3" fontSize="9" fontWeight="600" fill="#ffffff">
                        {Number(hoveredRecord[key]).toLocaleString('en-IN', { maximumFractionDigits: 1 })}
                      </text>
                    </g>
                  )}
                </g>
              );
            })}
          </g>
        </svg>

        {/* Floating Tooltip */}
        {hoveredRecord && (
          <div style={{
            position: 'fixed',
            left: tooltipPos.x + 14,
            top: tooltipPos.y + 14,
            background: '#0f172a',
            color: '#ffffff',
            padding: '10px 14px',
            borderRadius: 6,
            fontSize: 12,
            boxShadow: '0 8px 20px rgba(0,0,0,0.25)',
            pointerEvents: 'none',
            zIndex: 100,
            maxWidth: 280
          }}>
            <div style={{ fontWeight: 700, fontSize: 13, marginBottom: 4 }}>
              {hoveredRecord[labelKey] || hoveredRecord[idKey]}
            </div>

            {hoveredRecord[colorKey] && (
              <div style={{ color: '#38bdf8', fontSize: 11, marginBottom: 6 }}>
                Classification: <strong>{hoveredRecord[colorKey]}</strong>
              </div>
            )}

            <div style={{ display: 'grid', gridTemplateColumns: 'auto auto', gap: '3px 12px', fontSize: 11 }}>
              {activeDimensions.map(dim => {
                const key = typeof dim === 'string' ? dim : dim.key;
                const d = dimensionDomains[key];
                return (
                  <React.Fragment key={key}>
                    <span style={{ color: '#cbd5e1' }}>{d.label}:</span>
                    <span style={{ fontWeight: 600, textAlign: 'right' }}>
                      {Number(hoveredRecord[key]).toLocaleString('en-IN', { maximumFractionDigits: 2 })} {d.unit}
                    </span>
                  </React.Fragment>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* Accessible Multivariate Table Modal (Alt + F11) */}
      {isTableModalOpen && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: 'rgba(15, 23, 42, 0.65)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 999
        }}>
          <div style={{
            background: '#ffffff',
            borderRadius: 8,
            width: '92%',
            maxWidth: 880,
            maxHeight: '80vh',
            display: 'flex',
            flexDirection: 'column',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.25)'
          }}>
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: '16px 20px',
              borderBottom: '1px solid #e2e8f0'
            }}>
              <h3 style={{ margin: 0, fontSize: 16, color: '#0f172a' }}>Accessible Multivariate Observations Table</h3>
              <button
                onClick={() => setIsTableModalOpen(false)}
                style={{ border: 'none', background: 'none', fontSize: 18, cursor: 'pointer', color: '#64748b' }}
              >✕</button>
            </div>

            <div style={{ padding: 20, overflowY: 'auto', flex: 1 }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
                <thead>
                  <tr style={{ background: '#f8fafc', borderBottom: '1px solid #cbd5e1', textAlign: 'left' }}>
                    <th style={{ padding: '8px 10px' }}>Record / Batch</th>
                    <th style={{ padding: '8px 10px' }}>Cluster / Grade</th>
                    {activeDimensions.map(dim => {
                      const key = typeof dim === 'string' ? dim : dim.key;
                      const d = dimensionDomains[key];
                      return (
                        <th key={key} style={{ padding: '8px 10px', textAlign: 'right' }}>
                          {d.label} {d.unit ? `(${d.unit})` : ''}
                        </th>
                      );
                    })}
                  </tr>
                </thead>
                <tbody>
                  {filteredData.map((r, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                      <td style={{ padding: '8px 10px', fontWeight: 600 }}>{r[labelKey] || r[idKey] || `Record ${i + 1}`}</td>
                      <td style={{ padding: '8px 10px', color: '#0284c7', fontWeight: 600 }}>{r[colorKey] || '—'}</td>
                      {activeDimensions.map(dim => {
                        const key = typeof dim === 'string' ? dim : dim.key;
                        const v = Number(r[key]);
                        return (
                          <td key={key} style={{ padding: '8px 10px', textAlign: 'right' }}>
                            {!isNaN(v) ? v.toLocaleString('en-IN', { maximumFractionDigits: 2 }) : '—'}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default ParallelCoordinates;

// packages/angular/src/components/parallel-coordinates/parallel-coordinates.component.ts
import { DsFocusTrapDirective } from '../../utils/focus-trap.directive.js';
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  OnInit,
  AfterViewInit,
  OnDestroy,
  ElementRef,
  ViewChild
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  calculateDimensionDomains,
  generateParallelPolylinePath,
  evaluateBrushFilters,
  STROKE_DASH_PATTERNS,
  VIZ_COLORS,
  formatVizValue,
  DimensionDomain,
  getVizDensityTier,
  VizDensityTier
} from '../../utils/viz-core.js';

export type ParallelCoordinatesVariant = 'standard' | 'normalized' | 'spline' | 'brushed';

export interface ParallelDimension {
  key: string;
  label: string;
  unit?: string;
  min?: number;
  max?: number;
  inverted?: boolean;
  isCategorical?: boolean;
  categories?: string[];
}

const CLUSTER_COLORS = [
  '#0284c7',
  '#16a34a',
  '#d97706',
  '#7c3aed',
  '#dc2626',
  '#0d9488'
];

@Component({
  selector: 'ds-parallel-coordinates',
  standalone: true,
  imports: [DsFocusTrapDirective, CommonModule, FormsModule],
  template: `
    <div
      #containerRef
      class="ds-parallel-coordinates ds-parallel-coordinates--{{ variant }}"
      [style.width]="'100%'"
      role="region"
      [attr.aria-label]="(title || 'Multivariate Parallel Coordinates') + '. ' + filteredData.length + ' records across ' + activeDimensions.length + ' dimensions. Use arrow keys to cycle, Alt+F11 for data table.'"
      tabindex="0"
      (keydown)="onKeyDown($event)"
    >
      <!-- Live Region for Screen Reader Announcements -->
      <div aria-live="polite" class="sr-only">
        {{ announcement }}
      </div>

      <!-- Header & Controls Toolbar -->
      <div class="ds-parallel-coordinates__header">
        <div>
          <div *ngIf="title" class="ds-parallel-coordinates__title">{{ title }}</div>
          <div *ngIf="subtitle" class="ds-parallel-coordinates__subtitle">
            {{ subtitle }} · Showing <strong>{{ filteredData.length }}</strong> of {{ data.length }} records
          </div>
        </div>

        <div *ngIf="showControls" class="ds-parallel-coordinates__toolbar">
          <!-- Search Input -->
          <div *ngIf="showSearch" class="ds-parallel-coordinates__search-wrapper">
            <input
              type="text"
              placeholder="Filter record/batch..."
              [(ngModel)]="searchQuery"
              class="ds-parallel-coordinates__search-input"
              aria-label="Filter records by ID, label, or cluster"
            />
            <button
              *ngIf="searchQuery"
              type="button"
              (click)="searchQuery = ''"
              class="ds-parallel-coordinates__search-clear"
              aria-label="Clear search"
            >&times;</button>
          </div>

          <!-- Normalization Toggle -->
          <label class="ds-parallel-coordinates__checkbox-label">
            <input
              type="checkbox"
              [(ngModel)]="isNormalized"
            />
            Normalize 0–100%
          </label>

          <!-- Spline Smooth Toggle -->
          <label class="ds-parallel-coordinates__checkbox-label">
            <input
              type="checkbox"
              [(ngModel)]="isSmooth"
            />
            Smooth Spline
          </label>

          <!-- Accessible Brush Filters Panel Trigger -->
          <button
            *ngIf="showBrushControls"
            type="button"
            class="ds-parallel-coordinates__btn"
            [class.ds-parallel-coordinates__btn--active]="isFilterPanelOpen"
            (click)="isFilterPanelOpen = !isFilterPanelOpen"
          >
            🎯 Brush Filters {{ activeBrushCount > 0 ? '(' + activeBrushCount + ')' : '' }}
          </button>

          <!-- Table Modal Toggle Button (Alt+F11) -->
          <button
            type="button"
            class="ds-parallel-coordinates__btn"
            [class.ds-parallel-coordinates__btn--active]="showTableModal"
            (click)="showTableModal = !showTableModal"
            title="Toggle Accessible Data Table View (Alt+F11)"
            aria-label="Toggle Accessible Data Table View"
          >
            Table (Alt+F11)
          </button>
        </div>
      </div>

      <!-- Non-Drag Accessible Brush Controls Panel -->
      <div *ngIf="isFilterPanelOpen" class="ds-parallel-coordinates__brush-panel">
        <div class="ds-parallel-coordinates__brush-header">
          <span class="ds-parallel-coordinates__brush-title">
            Accessible 1D Axis Range Filters (Keyboard Alternative to Drag Brushes)
          </span>
          <button
            *ngIf="activeBrushCount > 0"
            type="button"
            (click)="clearAllBrushes()"
            class="ds-parallel-coordinates__brush-reset"
          >
            Reset All Filters
          </button>
        </div>

        <div class="ds-parallel-coordinates__brush-grid">
          <div *ngFor="let dim of activeDimensions" class="ds-parallel-coordinates__brush-card">
            <div class="ds-parallel-coordinates__brush-label">
              {{ dim.label || dim.key }} {{ dim.unit ? '(' + dim.unit + ')' : '' }}
            </div>
            <div class="ds-parallel-coordinates__brush-inputs">
              <input
                type="number"
                [placeholder]="'Min (' + (dimDomains[dim.key]?.rawMin?.toFixed(0) || 0) + ')'"
                [ngModel]="activeBrushes[dim.key]?.min"
                (ngModelChange)="updateBrush(dim.key, 'min', $event)"
                class="ds-parallel-coordinates__brush-input"
              />
              <span class="ds-parallel-coordinates__brush-sep">&ndash;</span>
              <input
                type="number"
                [placeholder]="'Max (' + (dimDomains[dim.key]?.rawMax?.toFixed(0) || 100) + ')'"
                [ngModel]="activeBrushes[dim.key]?.max"
                (ngModelChange)="updateBrush(dim.key, 'max', $event)"
                class="ds-parallel-coordinates__brush-input"
              />
            </div>
          </div>
        </div>
      </div>

      <!-- Main SVG Plot Canvas -->
      <div class="ds-parallel-coordinates__svg-wrapper">
        <svg
          width="100%"
          [attr.height]="height"
          [attr.viewBox]="'0 0 ' + plotWidth + ' ' + height"
          class="ds-parallel-coordinates__svg"
          style="display: block; width: 100%; height: auto;"
        >
          <g [attr.transform]="'translate(' + margin.left + ', ' + margin.top + ')'">
            <!-- 1. Filtered-out Background Polylines -->
            <g class="ds-parallel-coordinates__inactive-lines">
              <ng-container *ngFor="let record of data; let idx = index">
                <path
                  *ngIf="!filteredData.includes(record)"
                  [attr.d]="getRecordPath(record)"
                  fill="none"
                  stroke="var(--border-subtle, #e2e8f0)"
                  stroke-width="1"
                  opacity="0.35"
                />
              </ng-container>
            </g>

            <!-- 2. Active Polylines -->
            <g class="ds-parallel-coordinates__active-lines">
              <path
                *ngFor="let record of filteredData; let idx = index"
                class="ds-parallel-coordinates__line"
                [attr.d]="getRecordPath(record)"
                fill="none"
                [attr.stroke]="getRecordColor(record, idx)"
                [attr.stroke-dasharray]="getRecordDash(record, idx)"
                [attr.stroke-width]="selectedRecordId === (record[idKey] || idx) ? 3.5 : (hoveredRecord === record ? 3 : 1.5)"
                [attr.stroke-opacity]="hoveredRecord && hoveredRecord !== record && selectedRecordId !== (record[idKey] || idx) ? 0.2 : (selectedRecordId === (record[idKey] || idx) || hoveredRecord === record ? 1 : 0.7)"
                (pointerenter)="onPointerEnter(record, $event)"
                (pointerleave)="hoveredRecord = null; tooltipPos = null"
                (click)="onRecordClickAction(record, $event)"
              />
            </g>

            <!-- 3. Parallel Vertical Axes -->
            <g *ngFor="let dim of activeDimensions; let i = index" class="ds-parallel-coordinates__axis" [attr.transform]="'translate(' + axisXCoords[i] + ', 0)'">
              <!-- Vertical Spine Line -->
              <line x1="0" y1="0" x2="0" [attr.y2]="innerHeight" />

              <!-- Axis Reorder Controls -->
              <g transform="translate(0, -22)">
                <text
                  *ngIf="i > 0"
                  x="-10"
                  y="0"
                  class="ds-parallel-coordinates__reorder-btn"
                  text-anchor="end"
                  (click)="moveAxis(i, -1)"
                >◀</text>
                <text
                  *ngIf="i < activeDimensions.length - 1"
                  x="10"
                  y="0"
                  class="ds-parallel-coordinates__reorder-btn"
                  text-anchor="start"
                  (click)="moveAxis(i, 1)"
                >▶</text>
              </g>

              <!-- Axis Title -->
              <text y="-8" text-anchor="middle" class="ds-parallel-coordinates__axis-title">
                {{ dim.label || dim.key }}
              </text>

              <!-- Unit Label -->
              <text *ngIf="dim.unit" [attr.y]="innerHeight + 16" text-anchor="middle" class="ds-parallel-coordinates__axis-unit">
                {{ dim.unit }}
              </text>

              <!-- Axis Ticks -->
              <g *ngFor="let pct of [0, 0.25, 0.5, 0.75, 1]" [attr.transform]="'translate(0, ' + (innerHeight - pct * innerHeight) + ')'">
                <line x1="-4" x2="4" stroke="var(--border-strong, #94a3b8)" stroke-width="1" />
                <text x="-7" y="3" text-anchor="end" class="ds-parallel-coordinates__tick-label">
                  {{ getTickLabel(dim.key, pct) }}
                </text>
              </g>

              <!-- Multi-Axis Intersection Chips on Hover -->
              <g *ngIf="hoveredRecord && hoveredRecord[dim.key] != null" [attr.transform]="'translate(0, ' + valToY(hoveredRecord[dim.key], dim.key) + ')'">
                <circle r="4.5" fill="var(--action-solid, #0284c7)" stroke="#ffffff" stroke-width="2" />
                <rect x="8" y="-9" width="48" height="17" rx="3" fill="var(--surface-floating, #0f172a)" opacity="0.9" />
                <text x="12" y="3" font-size="9" font-weight="600" fill="#ffffff">
                  {{ formatVal(hoveredRecord[dim.key], '') }}
                </text>
              </g>
            </g>
          </g>
        </svg>

        <!-- Floating 2D Quad-Flip Non-Occluding Tooltip -->
        <div
          *ngIf="hoveredRecord && tooltipPos"
          class="ds-parallel-coordinates__tooltip"
          [style.left.px]="tooltipPos.clientX > width / 2 ? Math.max(12, tooltipPos.clientX - 260) : Math.min(tooltipPos.clientX + 16, width - 260)"
          [style.top.px]="tooltipPos.clientY > height / 2 ? Math.max(12, tooltipPos.clientY - 160) : Math.min(tooltipPos.clientY + 14, height - 160)"
        >
          <div class="ds-parallel-coordinates__tooltip-title">
            {{ hoveredRecord[labelKey] || hoveredRecord[idKey] || 'Record' }}
          </div>
          <div *ngIf="hoveredRecord[colorKey]" class="ds-parallel-coordinates__tooltip-cluster">
            Classification: <strong>{{ hoveredRecord[colorKey] }}</strong>
          </div>
          <div class="ds-parallel-coordinates__tooltip-grid">
            <ng-container *ngFor="let dim of activeDimensions">
              <span class="ds-parallel-coordinates__tooltip-dim">{{ dim.label || dim.key }}:</span>
              <span class="ds-parallel-coordinates__tooltip-val">
                {{ formatVal(hoveredRecord[dim.key], dim.unit) }}
              </span>
            </ng-container>
          </div>
        </div>
      </div>

      <!-- Accessible Data Table Modal (Alt+F11) -->
      <div dsFocusTrap tabindex="-1" *ngIf="showTableModal" class="ds-parallel-coordinates__modal-backdrop" role="dialog" aria-modal="true" aria-label="Accessible Multivariate Telemetry Matrix">
        <div class="ds-parallel-coordinates__modal-dialog">
          <div class="ds-parallel-coordinates__modal-header">
            <div>
              <div class="ds-parallel-coordinates__modal-title">Accessible Multivariate Telemetry Matrix</div>
              <div class="ds-parallel-coordinates__modal-subtitle">
                Showing {{ filteredData.length }} records across {{ activeDimensions.length }} parallel dimensions
              </div>
            </div>
            <button
              type="button"
              (click)="showTableModal = false"
              class="ds-parallel-coordinates__modal-close"
              aria-label="Close table modal"
            >&times;</button>
          </div>

          <div class="ds-parallel-coordinates__modal-body">
            <table class="ds-parallel-coordinates__table">
              <thead>
                <tr>
                  <th>Record ID</th>
                  <th>Cluster</th>
                  <th *ngFor="let dim of activeDimensions" style="text-align: right">
                    {{ dim.label || dim.key }}
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let rec of filteredData; let idx = index">
                  <td style="font-weight: 600">{{ rec[labelKey] || rec[idKey] || ('Record ' + (idx + 1)) }}</td>
                  <td>
                    <span class="ds-parallel-coordinates__cluster-badge">{{ rec[colorKey] || 'Nominal' }}</span>
                  </td>
                  <td *ngFor="let dim of activeDimensions" style="text-align: right; font-variant-numeric: tabular-nums">
                    {{ formatVal(rec[dim.key], dim.unit) }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="ds-parallel-coordinates__modal-footer">
            <button
              type="button"
              (click)="showTableModal = false"
              class="ds-parallel-coordinates__modal-btn"
            >
              Close (Esc)
            </button>
          </div>
        </div>
      </div>

    </div>
  `,
  styleUrls: ['./parallel-coordinates.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DsParallelCoordinatesComponent implements OnInit, AfterViewInit, OnDestroy {
  Math = Math;

  @Input() data: Record<string, any>[] = [];
  @Input() dimensions: ParallelDimension[] = [];
  @Input() variant: ParallelCoordinatesVariant = 'standard';
  @Input() width: number = 860;
  @Input() height: number = 420;
  @Input() title: string = 'Multivariate Process & Quality Telemetry';
  @Input() subtitle: string = '';
  @Input() colorKey: string = 'cluster';
  @Input() idKey: string = 'id';
  @Input() labelKey: string = 'label';
  @Input() smooth: boolean = false;
  @Input() normalized: boolean = false;
  @Input() showBrushControls: boolean = true;
  @Input() showControls: boolean = true;
  @Input() showSearch: boolean = true;

  @Output() recordClick = new EventEmitter<{ record: Record<string, any> }>();

  @ViewChild('containerRef') containerRef!: ElementRef<HTMLDivElement>;

  activeDimensions: ParallelDimension[] = [];
  isNormalized = false;
  isSmooth = false;
  hoveredRecord: any = null;
  selectedRecordId: string | null = null;
  focusedIndex = -1;
  searchQuery = '';
  isFilterPanelOpen = false;
  showTableModal = false;
  announcement = '';
  tooltipPos: { clientX: number; clientY: number } | null = null;
  activeBrushes: Record<string, { min?: number | null; max?: number | null }> = {};

  margin = { top: 36, right: 48, bottom: 40, left: 48 };

  measuredWidth: number = 0;
  private resizeObserver?: ResizeObserver;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit() {
    this.activeDimensions = [...this.dimensions];
    this.isNormalized = this.normalized || this.variant === 'normalized';
    this.isSmooth = this.smooth || this.variant === 'spline';
  }

  ngAfterViewInit(): void {
    if (this.containerRef?.nativeElement && typeof ResizeObserver !== 'undefined') {
      this.resizeObserver = new ResizeObserver((entries) => {
        for (const entry of entries) {
          const w = Math.floor(entry.contentRect.width);
          if (w > 0) {
            this.measuredWidth = w;
            this.cdr.markForCheck();
          }
        }
      });
      this.resizeObserver.observe(this.containerRef.nativeElement);
    }
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
  }

  get plotWidth(): number {
    return Math.max(300, this.measuredWidth || this.width);
  }

  get densityTier(): VizDensityTier {
    return getVizDensityTier(this.plotWidth);
  }

  get innerWidth(): number {
    return Math.max(100, this.plotWidth - this.margin.left - this.margin.right);
  }

  get innerHeight(): number {
    return Math.max(100, this.height - this.margin.top - this.margin.bottom);
  }

  get filteredData(): Record<string, any>[] {
    const q = this.searchQuery.toLowerCase().trim();
    return this.data.filter(d => {
      if (q) {
        const idVal = String(d[this.idKey] || '').toLowerCase();
        const lblVal = String(d[this.labelKey] || '').toLowerCase();
        const clusterVal = String(d[this.colorKey] || '').toLowerCase();
        if (!idVal.includes(q) && !lblVal.includes(q) && !clusterVal.includes(q)) {
          return false;
        }
      }

      const brushKeys = Object.keys(this.activeBrushes);
      for (let i = 0; i < brushKeys.length; i++) {
        const k = brushKeys[i];
        const brush = this.activeBrushes[k];
        if (brush && (brush.min != null || brush.max != null)) {
          const val = Number(d[k]);
          if (isNaN(val)) return false;
          if (brush.min != null && val < brush.min) return false;
          if (brush.max != null && val > brush.max) return false;
        }
      }

      return true;
    });
  }

  get dimDomains(): Record<string, DimensionDomain> {
    return calculateDimensionDomains(this.data, this.activeDimensions);
  }

  get axisSpacing(): number {
    const count = this.activeDimensions.length;
    return count > 1 ? this.innerWidth / (count - 1) : this.innerWidth / 2;
  }

  get axisXCoords(): number[] {
    return this.activeDimensions.map((_, i) => i * this.axisSpacing);
  }

  get yScales(): Record<string, (v: any) => number> {
    const scales: Record<string, (v: any) => number> = {};
    const domains = this.dimDomains;

    this.activeDimensions.forEach(dim => {
      const dom = domains[dim.key];
      scales[dim.key] = (val: any) => {
        if (!dom || val == null || isNaN(Number(val))) return this.innerHeight / 2;

        if (this.isNormalized) {
          const rMin = dom.rawMin ?? dom.min ?? 0;
          const rMax = dom.rawMax ?? dom.max ?? 100;
          let norm = (Number(val) - rMin) / (rMax - rMin || 1);
          norm = Math.max(0, Math.min(1, norm));
          if (dom.inverted) norm = 1 - norm;
          return this.innerHeight - norm * this.innerHeight;
        }

        const span = dom.span || 1;
        const dMin = dom.min ?? 0;
        let norm = (Number(val) - dMin) / span;
        norm = Math.max(0, Math.min(1, norm));
        if (dom.inverted) norm = 1 - norm;
        return this.innerHeight - norm * this.innerHeight;
      };
    });
    return scales;
  }

  valToY(val: any, key: string): number {
    const scale = this.yScales[key];
    return scale ? scale(val) : this.innerHeight / 2;
  }

  getRecordPath(record: any): string {
    return generateParallelPolylinePath(
      record,
      this.activeDimensions,
      this.axisXCoords,
      this.yScales,
      { smooth: this.isSmooth }
    );
  }

  getRecordColor(record: any, idx: number): string {
    if (record.color) return record.color;
    const cVal = record[this.colorKey];
    if (typeof cVal === 'number') return CLUSTER_COLORS[cVal % CLUSTER_COLORS.length];
    if (typeof cVal === 'string') {
      let hash = 0;
      for (let i = 0; i < cVal.length; i++) hash = cVal.charCodeAt(i) + ((hash << 5) - hash);
      return CLUSTER_COLORS[Math.abs(hash) % CLUSTER_COLORS.length];
    }
    return CLUSTER_COLORS[idx % CLUSTER_COLORS.length];
  }

  getRecordDash(record: any, idx: number): string {
    const cVal = record[this.colorKey];
    if (typeof cVal === 'number') return STROKE_DASH_PATTERNS[cVal % STROKE_DASH_PATTERNS.length];
    if (typeof cVal === 'string') {
      let hash = 0;
      for (let i = 0; i < cVal.length; i++) hash = cVal.charCodeAt(i) + ((hash << 5) - hash);
      return STROKE_DASH_PATTERNS[Math.abs(hash) % STROKE_DASH_PATTERNS.length];
    }
    return 'none';
  }

  getTickLabel(key: string, pct: number): string {
    if (this.isNormalized) return `${(pct * 100).toFixed(0)}%`;
    const dom = this.dimDomains[key];
    if (!dom) return '';
    const rMin = dom.rawMin ?? dom.min ?? 0;
    const rMax = dom.rawMax ?? dom.max ?? 100;
    const rawVal = rMin + pct * (rMax - rMin);
    return rawVal.toLocaleString('en-IN', { maximumFractionDigits: 1 });
  }

  moveAxis(idx: number, direction: number): void {
    const targetIdx = idx + direction;
    if (targetIdx < 0 || targetIdx >= this.activeDimensions.length) return;
    const next = [...this.activeDimensions];
    const temp = next[idx];
    next[idx] = next[targetIdx];
    next[targetIdx] = temp;
    this.activeDimensions = next;
    this.announcement = `Moved axis ${temp.label || temp.key} to position ${targetIdx + 1}`;
  }

  updateBrush(key: string, field: 'min' | 'max', val: any): void {
    const current = this.activeBrushes[key] || { min: this.dimDomains[key]?.rawMin, max: this.dimDomains[key]?.rawMax };
    const num = val === '' || val == null ? null : Number(val);
    this.activeBrushes = {
      ...this.activeBrushes,
      [key]: { ...current, [field]: num }
    };
  }

  clearAllBrushes(): void {
    this.activeBrushes = {};
    this.searchQuery = '';
    this.announcement = 'Cleared all multidimensional brush filters';
  }

  get activeBrushCount(): number {
    return Object.keys(this.activeBrushes).filter(k => this.activeBrushes[k].min != null || this.activeBrushes[k].max != null).length;
  }

  formatVal(val: any, unit: string = ''): string {
    return formatVizValue(val, unit);
  }

  onPointerEnter(record: any, e: PointerEvent): void {
    this.hoveredRecord = record;
    const rect = this.containerRef?.nativeElement?.getBoundingClientRect();
    this.tooltipPos = {
      clientX: e.clientX - (rect?.left || 0),
      clientY: e.clientY - (rect?.top || 0)
    };
  }

  onRecordClickAction(record: any, e: MouseEvent): void {
    this.selectedRecordId = record[this.idKey] || null;
    this.recordClick.emit({ record });
  }

  onKeyDown(e: KeyboardEvent): void {
    if (e.key === 'F11' && e.altKey) {
      e.preventDefault();
      this.showTableModal = !this.showTableModal;
      return;
    }
    if (e.key === 'Escape') {
      if (this.showTableModal) {
        e.preventDefault();
        this.showTableModal = false;
        return;
      }
      if (this.selectedRecordId) {
        e.preventDefault();
        this.selectedRecordId = null;
        this.hoveredRecord = null;
        return;
      }
    }
    if (this.filteredData.length === 0) return;

    if (e.key === 'ArrowDown' || e.key === 'ArrowRight') {
      e.preventDefault();
      this.focusedIndex = (this.focusedIndex + 1) % this.filteredData.length;
      const rec = this.filteredData[this.focusedIndex];
      this.hoveredRecord = rec;
      this.announcement = `Record ${rec[this.labelKey] || rec[this.idKey]}, Cluster: ${rec[this.colorKey] || 'Nominal'}`;
    } else if (e.key === 'ArrowUp' || e.key === 'ArrowLeft') {
      e.preventDefault();
      this.focusedIndex = (this.focusedIndex - 1 + this.filteredData.length) % this.filteredData.length;
      const rec = this.filteredData[this.focusedIndex];
      this.hoveredRecord = rec;
      this.announcement = `Record ${rec[this.labelKey] || rec[this.idKey]}, Cluster: ${rec[this.colorKey] || 'Nominal'}`;
    } else if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      if (this.focusedIndex >= 0 && this.focusedIndex < this.filteredData.length) {
        const rec = this.filteredData[this.focusedIndex];
        this.selectedRecordId = this.selectedRecordId === rec[this.idKey] ? null : rec[this.idKey];
        this.recordClick.emit({ record: rec });
      }
    }
  }
}
