// packages/react/src/components/Drawer/Drawer.tsx
import React, {
  forwardRef,
  useCallback,
  useEffect,
  useRef,
  useId,
  useMemo,
  createContext,
  useContext,
} from 'react';
import { createPortal } from 'react-dom';
import { useFocusTrap } from '../../hooks/useFocusTrap.js';
import './Drawer.css';

export type DrawerPlacement = 'right' | 'left' | 'top' | 'bottom';
export type DrawerSize = 'sm' | 'md' | 'lg' | 'full';

interface DrawerContextValue {
  isOpen: boolean;
  onClose: () => void;
  titleId: string;
  descriptionId: string;
  placement: DrawerPlacement;
  size: DrawerSize;
}

const DrawerContext = createContext<DrawerContextValue | null>(null);

const useDrawerContext = () => {
  const context = useContext(DrawerContext);
  if (!context) {
    throw new Error('Drawer compound components must be used within a <Drawer>');
  }
  return context;
};

export interface DrawerProps {
  open: boolean;
  onOpenChange?: (open: boolean) => void;
  placement?: DrawerPlacement;
  size?: DrawerSize;
  children: React.ReactNode;
  closeOnEsc?: boolean;
  closeOnBackdropClick?: boolean;
  className?: string;
}

export const Drawer: React.FC<DrawerProps> = ({
  open,
  onOpenChange,
  placement = 'right',
  size = 'md',
  children,
  closeOnEsc = true,
  closeOnBackdropClick = true,
  className = '',
}) => {
  const titleId = useId();
  const descriptionId = useId();
  const panelRef = useRef<HTMLDivElement>(null);
  const backdropRef = useRef<HTMLDivElement>(null);
  const allowedRefs = useMemo(() => [backdropRef], [backdropRef]);

  useEffect(() => {
    if (panelRef.current) panelRef.current.inert = !open;
  }, [open]);
  useFocusTrap(panelRef, open, allowedRefs);

  const handleClose = useCallback(() => {
    onOpenChange?.(false);
  }, [onOpenChange]);

  useEffect(() => {
    if (!open) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && closeOnEsc) {
        handleClose();
      }
    };

    const originalOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      document.body.style.overflow = originalOverflow;
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [open, closeOnEsc, handleClose]);

  if (typeof document === 'undefined') return null;

  return createPortal(
    <DrawerContext.Provider
      value={{
        isOpen: open,
        onClose: handleClose,
        titleId,
        descriptionId,
        placement,
        size,
      }}
    >
      <div
        ref={backdropRef}
        className={`ds-drawer-backdrop ${open ? 'ds-drawer-backdrop--open' : ''}`}
        onClick={closeOnBackdropClick ? handleClose : undefined}
        aria-hidden="true"
      />
      <div
        ref={panelRef}
        role="dialog"
        aria-modal={open ? 'true' : undefined}
        aria-hidden={open ? undefined : true}
        aria-labelledby={titleId}
        aria-describedby={descriptionId}
        tabIndex={-1}
        className={`ds-drawer-panel ds-drawer-panel--${placement} ds-drawer-panel--size-${size} ${
          open ? 'ds-drawer-panel--open' : ''
        } ${className}`}
      >
        {children}
      </div>
    </DrawerContext.Provider>,
    document.body
  );
};

Drawer.displayName = 'Drawer';

export interface DrawerHeaderProps extends React.HTMLAttributes<HTMLDivElement> {
  showClose?: boolean;
}

export const DrawerHeader = forwardRef<HTMLDivElement, DrawerHeaderProps>(
  ({ showClose = true, children, className = '', ...props }, ref) => {
    const { onClose } = useDrawerContext();

    return (
      <div ref={ref} className={`ds-drawer-header ${className}`} {...props}>
        <div className="ds-drawer-header-main">{children}</div>
        {showClose && (
          <button
            type="button"
            className="ds-drawer-close"
            onClick={onClose}
            aria-label="Close drawer"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        )}
      </div>
    );
  }
);
DrawerHeader.displayName = 'DrawerHeader';

export interface DrawerTitleProps extends React.HTMLAttributes<HTMLHeadingElement> {
  as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
}

export const DrawerTitle = forwardRef<HTMLHeadingElement, DrawerTitleProps>(
  ({ as = 'h2', children, className = '', ...props }, ref) => {
    const { titleId } = useDrawerContext();
    const HeadingTag = as;

    return (
      <HeadingTag
        ref={ref}
        id={titleId}
        className={`ds-drawer-title ${className}`}
        {...props}
      >
        {children}
      </HeadingTag>
    );
  }
);
DrawerTitle.displayName = 'DrawerTitle';

export interface DrawerDescriptionProps extends React.HTMLAttributes<HTMLParagraphElement> {}

export const DrawerDescription = forwardRef<HTMLParagraphElement, DrawerDescriptionProps>(
  ({ children, className = '', ...props }, ref) => {
    const { descriptionId } = useDrawerContext();

    return (
      <p
        ref={ref}
        id={descriptionId}
        className={`ds-drawer-description ${className}`}
        {...props}
      >
        {children}
      </p>
    );
  }
);
DrawerDescription.displayName = 'DrawerDescription';

export interface DrawerBodyProps extends React.HTMLAttributes<HTMLDivElement> {}

export const DrawerBody = forwardRef<HTMLDivElement, DrawerBodyProps>(
  ({ children, className = '', ...props }, ref) => {
    return (
      <div ref={ref} className={`ds-drawer-body ${className}`} {...props}>
        {children}
      </div>
    );
  }
);
DrawerBody.displayName = 'DrawerBody';

export interface DrawerFooterProps extends React.HTMLAttributes<HTMLDivElement> {}

export const DrawerFooter = forwardRef<HTMLDivElement, DrawerFooterProps>(
  ({ children, className = '', ...props }, ref) => {
    return (
      <div ref={ref} className={`ds-drawer-footer ${className}`} {...props}>
        {children}
      </div>
    );
  }
);
DrawerFooter.displayName = 'DrawerFooter';

// packages/angular/src/components/drawer/drawer.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  HostListener,
  ChangeDetectionStrategy,
  ViewChild, ElementRef, AfterViewChecked, OnDestroy,
  Inject, Optional, SkipSelf, forwardRef,
  ContentChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { useFocusTrap } from '../../utils/focus-trap.js';

export type DrawerPlacement = 'right' | 'left' | 'top' | 'bottom';
export type DrawerSize = 'sm' | 'md' | 'lg' | 'full';

let nextDrawerId = 0;

@Component({
  selector: 'ds-drawer-title',
  standalone: true,
  imports: [CommonModule],
  template: `<h2 [id]="drawer ? drawer.drawerId + '-title' : null" class="ds-drawer-title" [class]="customClass"><ng-content></ng-content></h2>`,
  styleUrls: ['./drawer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDrawerTitleComponent {
  @Input() customClass = '';
  constructor(@Optional() @SkipSelf() @Inject(forwardRef(() => DsDrawerComponent)) public drawer: DsDrawerComponent | null) {}
}

@Component({
  selector: 'ds-drawer-description',
  standalone: true,
  imports: [CommonModule],
  template: `<p [id]="drawer ? drawer.drawerId + '-description' : null" class="ds-drawer-description" [class]="customClass"><ng-content></ng-content></p>`,
  styleUrls: ['./drawer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDrawerDescriptionComponent {
  @Input() customClass = '';
  constructor(@Optional() @SkipSelf() @Inject(forwardRef(() => DsDrawerComponent)) public drawer: DsDrawerComponent | null) {}
}

@Component({
  selector: 'ds-drawer-header',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="ds-drawer-header" [class]="customClass">
      <div class="ds-drawer-header-main">
        <ng-content></ng-content>
      </div>
      <button
        *ngIf="showClose"
        type="button"
        class="ds-drawer-close"
        (click)="close.emit()"
        aria-label="Close drawer"
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <line x1="18" y1="6" x2="6" y2="18"></line>
          <line x1="6" y1="6" x2="18" y2="18"></line>
        </svg>
      </button>
    </div>
  `,
  styleUrls: ['./drawer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDrawerHeaderComponent {
  @Input() showClose = true;
  @Input() customClass = '';
  @Output() close = new EventEmitter<void>();
}

@Component({
  selector: 'ds-drawer-body',
  standalone: true,
  imports: [CommonModule],
  template: `<div class="ds-drawer-body" [class]="customClass"><ng-content></ng-content></div>`,
  styleUrls: ['./drawer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDrawerBodyComponent {
  @Input() customClass = '';
}

@Component({
  selector: 'ds-drawer-footer',
  standalone: true,
  imports: [CommonModule],
  template: `<div class="ds-drawer-footer" [class]="customClass"><ng-content></ng-content></div>`,
  styleUrls: ['./drawer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDrawerFooterComponent {
  @Input() customClass = '';
}

@Component({
  selector: 'ds-drawer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      #backdrop
      class="ds-drawer-backdrop"
      [class.ds-drawer-backdrop--open]="open"
      (click)="onBackdropClick()"
      aria-hidden="true"
    ></div>
    <div
      #panel
      role="dialog"
      [attr.aria-modal]="open ? 'true' : null"
      [attr.aria-hidden]="open ? null : 'true'"
      [attr.inert]="open ? null : ''"
      tabindex="-1"
      [attr.aria-label]="ariaLabel || null"
      [attr.aria-labelledby]="ariaLabel || !drawerTitle ? null : (drawerId + '-title')"
      [attr.aria-describedby]="drawerDescription ? drawerId + '-description' : null"
      class="ds-drawer-panel"
      [class.ds-drawer-panel--right]="placement === 'right'"
      [class.ds-drawer-panel--left]="placement === 'left'"
      [class.ds-drawer-panel--top]="placement === 'top'"
      [class.ds-drawer-panel--bottom]="placement === 'bottom'"
      [class.ds-drawer-panel--size-sm]="size === 'sm'"
      [class.ds-drawer-panel--size-md]="size === 'md'"
      [class.ds-drawer-panel--size-lg]="size === 'lg'"
      [class.ds-drawer-panel--size-full]="size === 'full'"
      [class.ds-drawer-panel--open]="open"
      [class]="customClass"
    >
      <ng-content></ng-content>
    </div>
  `,
  styleUrls: ['./drawer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDrawerComponent implements AfterViewChecked, OnDestroy {
  @ContentChild(DsDrawerTitleComponent, { descendants: true }) drawerTitle?: DsDrawerTitleComponent;
  @ContentChild(DsDrawerDescriptionComponent, { descendants: true }) drawerDescription?: DsDrawerDescriptionComponent;
  @ViewChild('panel') panel?: ElementRef<HTMLElement>;
  @ViewChild('backdrop') backdrop?: ElementRef<HTMLElement>;
  private releaseFocus?: () => void;
  @Input() open = false;
  @Input() ariaLabel?: string;
  @Input() placement: DrawerPlacement = 'right';
  @Input() size: DrawerSize = 'md';
  @Input() closeOnEsc = true;
  @Input() closeOnBackdropClick = true;
  @Input() customClass = '';

  @Output() openChange = new EventEmitter<boolean>();

  drawerId = `ds-drawer-${++nextDrawerId}`;

  ngAfterViewChecked(): void {
    if (this.open && this.panel && !this.releaseFocus) this.releaseFocus = useFocusTrap(this.panel.nativeElement, this.backdrop ? [this.backdrop.nativeElement] : []);
    if (!this.open && this.releaseFocus) { this.releaseFocus(); this.releaseFocus = undefined; }
  }

  ngOnDestroy(): void { this.releaseFocus?.(); }

  @HostListener('window:keydown.escape')
  onEscape(): void {
    if (this.open && this.closeOnEsc) {
      this.close();
    }
  }

  onBackdropClick(): void {
    if (this.closeOnBackdropClick) {
      this.close();
    }
  }

  close(): void {
    this.open = false;
    this.releaseFocus?.();
    this.releaseFocus = undefined;
    this.openChange.emit(false);
  }
}
