// packages/angular/src/components/date-range-picker/date-range-picker.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';

export interface DateRangeData {
  startDate: string;
  endDate: string;
}
let nextDateRangeId = 0;

@Component({
  selector: 'ds-date-range-picker',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="ds-date-range-picker" [class]="customClass" [class.ds-date-range-picker--invalid]="isInvalid">
      <div *ngIf="showPresets" class="ds-date-range-presets">
        <button
          *ngFor="let p of presets"
          type="button"
          (click)="selectPreset(p)"
          class="ds-preset-btn"
          [class.ds-preset-btn--active]="activePreset === p.label"
        >
          {{ p.label }}
        </button>
      </div>

      <div class="ds-date-range-inputs">
        <label class="ds-date-range-sr-only" [attr.for]="startId">Start Date</label>
        <input
          [id]="startId"
          type="text"
          [value]="range.startDate"
          readonly
          placeholder="Start Date"
          [attr.aria-invalid]="isInvalid || errorMessage ? 'true' : null"
          [attr.aria-describedby]="describedByIds"
        />
        <span aria-hidden="true">→</span>
        <label class="ds-date-range-sr-only" [attr.for]="endId">End Date</label>
        <input
          [id]="endId"
          type="text"
          [value]="range.endDate"
          readonly
          placeholder="End Date"
          [attr.aria-invalid]="isInvalid || errorMessage ? 'true' : null"
          [attr.aria-describedby]="describedByIds"
        />
      </div>

      <p *ngIf="helperText" [id]="helperId" class="ds-date-range-helper">{{ helperText }}</p>
      <p *ngIf="errorMessage" [id]="errorId" role="alert" class="ds-date-range-error">{{ errorMessage }}</p>

      <div class="ds-calendar-header">
        <button type="button" class="ds-preset-btn" (click)="prevMonth()" aria-label="Previous month">‹</button>
        <strong>{{ monthNames[currentMonth] }} {{ currentYear }}</strong>
        <button type="button" class="ds-preset-btn" (click)="nextMonth()" aria-label="Next month">›</button>
      </div>

      <div class="ds-calendar-grid">
        <span *ngFor="let d of ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']" class="ds-calendar-day-header">
          {{ d }}
        </span>

        <button
          *ngFor="let day of daysArray"
          type="button"
          (click)="selectDay(day)"
          class="ds-calendar-day"
          [attr.aria-label]="monthNames[currentMonth] + ' ' + day + ', ' + currentYear"
          [attr.aria-pressed]="isDaySelected(day)"
          [class.ds-calendar-day--selected]="isDaySelected(day)"
          [class.ds-calendar-day--in-range]="isDayInRange(day)"
        >
          {{ day }}
        </button>
      </div>
    </div>
  `,
  styleUrls: ['./date-range-picker.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DsDateRangePickerComponent {
  private autoId = `ds-date-range-${++nextDateRangeId}`;
  get startId(): string { return `${this.autoId}-start`; }
  get endId(): string { return `${this.autoId}-end`; }
  get helperId(): string { return `${this.autoId}-helper`; }
  get errorId(): string { return `${this.autoId}-error`; }
  get describedByIds(): string | null { return [this.helperText ? this.helperId : null, this.errorMessage ? this.errorId : null].filter(Boolean).join(' ') || null; }
  @Input() range: DateRangeData = { startDate: '2026-09-15', endDate: '2026-09-22' };
  @Input() showPresets = true;
  @Input() customClass = '';
  @Input() isInvalid: boolean = false;
  @Input() errorMessage?: string;
  @Input() helperText?: string;

  @Output() rangeChange = new EventEmitter<DateRangeData>();

  activePreset = 'Last 7 Days';
  currentMonth = 8; // Sep (0-indexed)
  currentYear = 2026;

  presets = [
    { label: 'Last 24 Hours', days: 1 },
    { label: 'Last 7 Days', days: 7 },
    { label: 'Last 30 Days', days: 30 },
  ];

  monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];

  get daysArray(): number[] {
    const daysInMonth = new Date(this.currentYear, this.currentMonth + 1, 0).getDate();
    return Array.from({ length: daysInMonth }, (_, i) => i + 1);
  }

  selectPreset(preset: { label: string; days: number }): void {
    this.activePreset = preset.label;
    const end = new Date(2026, 8, 22);
    const start = new Date(2026, 8, 22 - preset.days);

    const formatDate = (d: Date) =>
      `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(
        d.getDate()
      ).padStart(2, '0')}`;

    this.range = { startDate: formatDate(start), endDate: formatDate(end) };
    this.rangeChange.emit(this.range);
  }

  selectDay(day: number): void {
    const dateStr = `${this.currentYear}-${String(this.currentMonth + 1).padStart(2, '0')}-${String(
      day
    ).padStart(2, '0')}`;

    if (!this.range.startDate || (this.range.startDate && this.range.endDate)) {
      this.range = { startDate: dateStr, endDate: '' };
      this.activePreset = 'Custom';
    } else {
      let start = this.range.startDate;
      let end = dateStr;
      if (new Date(dateStr) < new Date(start)) {
        end = start;
        start = dateStr;
      }
      this.range = { startDate: start, endDate: end };
      this.activePreset = 'Custom';
      this.rangeChange.emit(this.range);
    }
  }

  isDaySelected(day: number): boolean {
    const dateStr = `${this.currentYear}-${String(this.currentMonth + 1).padStart(2, '0')}-${String(
      day
    ).padStart(2, '0')}`;
    return this.range.startDate === dateStr || this.range.endDate === dateStr;
  }

  isDayInRange(day: number): boolean {
    if (!this.range.startDate || !this.range.endDate) return false;
    const dateStr = `${this.currentYear}-${String(this.currentMonth + 1).padStart(2, '0')}-${String(
      day
    ).padStart(2, '0')}`;
    const d = new Date(dateStr).getTime();
    const s = new Date(this.range.startDate).getTime();
    const e = new Date(this.range.endDate).getTime();
    return d > s && d < e;
  }

  prevMonth(): void {
    if (this.currentMonth === 0) {
      this.currentMonth = 11;
      this.currentYear--;
    } else {
      this.currentMonth--;
    }
  }

  nextMonth(): void {
    if (this.currentMonth === 11) {
      this.currentMonth = 0;
      this.currentYear++;
    } else {
      this.currentMonth++;
    }
  }
}

// packages/react/src/components/DateRangePicker/DateRangePicker.tsx
import React, { forwardRef, useState, useId } from 'react';
import { Button } from '../Button/index.js';
import { Input } from '../Input/index.js';
import './DateRangePicker.css';

export interface DateRange {
  startDate: string;
  endDate: string;
}

export interface DateRangePickerProps {
  value?: DateRange;
  defaultValue?: DateRange;
  onChange?: (range: DateRange) => void;
  onApply?: (range: DateRange) => void;
  onCancel?: () => void;
  showPresets?: boolean;
  className?: string;
  isInvalid?: boolean;
  errorMessage?: string;
  helperText?: string;
}

const presets = [
  { label: 'Last 24 Hours', days: 1 },
  { label: 'Last 7 Days', days: 7 },
  { label: 'Last 30 Days', days: 30 },
  { label: 'Last 90 Days', days: 90 },
];

export const DateRangePicker = forwardRef<HTMLDivElement, DateRangePickerProps>(
  (
    {
      value: controlledValue,
      defaultValue = { startDate: '2026-09-15', endDate: '2026-09-22' },
      onChange,
      onApply,
      onCancel,
      showPresets = true,
      className = '',
      isInvalid = false,
      errorMessage,
      helperText,
    },
    ref
  ) => {
    const generatedId = useId();
    const helperId = helperText ? `ds-drp-${generatedId}-helper` : undefined;
    const errorId = errorMessage ? `ds-drp-${generatedId}-error` : undefined;
    const describedBy = [helperId, errorId].filter(Boolean).join(' ') || undefined;
    const [range, setRange] = useState<DateRange>(controlledValue || defaultValue);
    const [activePreset, setActivePreset] = useState<string>('Last 7 Days');
    const [currentMonth, setCurrentMonth] = useState(8); // September (0-indexed)
    const [currentYear, setCurrentYear] = useState(2026);

    const handlePresetClick = (presetLabel: string, days: number) => {
      setActivePreset(presetLabel);
      const end = new Date(2026, 8, 22);
      const start = new Date(2026, 8, 22 - days);

      const formatDate = (d: Date) =>
        `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(
          d.getDate()
        ).padStart(2, '0')}`;

      const newRange = { startDate: formatDate(start), endDate: formatDate(end) };
      setRange(newRange);
      onChange?.(newRange);
    };

    const handleDayClick = (dayNumber: number) => {
      const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(
        dayNumber
      ).padStart(2, '0')}`;

      if (!range.startDate || (range.startDate && range.endDate)) {
        const newRange = { startDate: dateStr, endDate: '' };
        setRange(newRange);
        setActivePreset('Custom');
        onChange?.(newRange);
      } else {
        let newRange: DateRange;
        if (new Date(dateStr) < new Date(range.startDate)) {
          newRange = { startDate: dateStr, endDate: range.startDate };
        } else {
          newRange = { startDate: range.startDate, endDate: dateStr };
        }
        setRange(newRange);
        setActivePreset('Custom');
        onChange?.(newRange);
      }
    };

    const isSelected = (day: number) => {
      const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(
        day
      ).padStart(2, '0')}`;
      return range.startDate === dateStr || range.endDate === dateStr;
    };

    const isInRange = (day: number) => {
      if (!range.startDate || !range.endDate) return false;
      const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(
        day
      ).padStart(2, '0')}`;
      const d = new Date(dateStr).getTime();
      const s = new Date(range.startDate).getTime();
      const e = new Date(range.endDate).getTime();
      return d > s && d < e;
    };

    const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
    const daysArray = Array.from({ length: daysInMonth }, (_, i) => i + 1);

    const monthNames = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ];

    return (
      <div ref={ref} className={`ds-date-range-picker ${isInvalid ? 'ds-date-range-picker--invalid' : ''} ${className}`}>
        {showPresets && (
          <div className="ds-date-range-presets">
            {presets.map((p) => (
              <Button
                key={p.label}
                variant={activePreset === p.label ? 'primary' : 'secondary'}
                size="sm"
                onClick={() => handlePresetClick(p.label, p.days)}
              >
                {p.label}
              </Button>
            ))}
          </div>
        )}

        <div className="ds-date-range-inputs">
          <Input
            label="Start Date"
            aria-describedby={describedBy}
            size="sm"
            value={range.startDate}
            isInvalid={isInvalid || Boolean(errorMessage)}
            onChange={(e) => setRange({ ...range, startDate: e.target.value })}
          />
          <span className="ds-date-range-separator">→</span>
          <Input
            label="End Date"
            aria-describedby={describedBy}
            size="sm"
            value={range.endDate}
            isInvalid={isInvalid || Boolean(errorMessage)}
            onChange={(e) => setRange({ ...range, endDate: e.target.value })}
          />
        </div>

        {helperText && (
          <p id={helperId} className="ds-date-range-helper">
            {helperText}
          </p>
        )}

        {errorMessage && (
          <p id={errorId} role="alert" className="ds-date-range-error">
            {errorMessage}
          </p>
        )}

        <div className="ds-calendar-header">
          <Button
            variant="ghost"
            size="sm"
            aria-label="Previous month"
            onClick={() => {
              if (currentMonth === 0) {
                setCurrentMonth(11);
                setCurrentYear(currentYear - 1);
              } else {
                setCurrentMonth(currentMonth - 1);
              }
            }}
          >
            ‹
          </Button>
          <span className="ds-calendar-title">
            {monthNames[currentMonth]} {currentYear}
          </span>
          <Button
            variant="ghost"
            size="sm"
            aria-label="Next month"
            onClick={() => {
              if (currentMonth === 11) {
                setCurrentMonth(0);
                setCurrentYear(currentYear + 1);
              } else {
                setCurrentMonth(currentMonth + 1);
              }
            }}
          >
            ›
          </Button>
        </div>

        <div className="ds-calendar-grid">
          {['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'].map((d) => (
            <span key={d} className="ds-calendar-day-header">
              {d}
            </span>
          ))}

          {daysArray.map((day) => (
            <button
              key={day}
              type="button"
              aria-label={`${monthNames[currentMonth]} ${day}, ${currentYear}`}
              aria-pressed={isSelected(day)}
              onClick={() => handleDayClick(day)}
              className={`ds-calendar-day ${
                isSelected(day) ? 'ds-calendar-day--selected' : ''
              } ${isInRange(day) ? 'ds-calendar-day--in-range' : ''}`}
            >
              {day}
            </button>
          ))}
        </div>

        <div className="ds-date-range-footer">
          {onCancel && (
            <Button variant="secondary" size="sm" onClick={onCancel}>
              Cancel
            </Button>
          )}
          <Button
            variant="primary"
            size="sm"
            onClick={() => onApply?.(range)}
          >
            Apply Range
          </Button>
        </div>
      </div>
    );
  }
);

DateRangePicker.displayName = 'DateRangePicker';
